# GATE DA Student Progress Analytics

This notebook is a full student-account analytics and recommendation-replay notebook.

Use it when you want to:
- inspect one student's profile, streak, account metadata, and activity
- review completed tests with per-question right/wrong outcomes
- reconstruct question timelines from `review_payload`
- compute report-style thresholds, weak-topic flags, rapid-guess thresholds, and score bands
- replay the adaptive recommendation engine step by step
- render an interactive graph over the complete project question dataset with the student's path overlaid

It reads:
- `profiles`
- `test_history`
- `user_progress`
- `answered_questions`
- `activity_events`

and exports the complete project question inventory from:
- practice bank
- adaptive subject-wise bank
- adaptive mix bank
- full GATE/mock papers

If row-level security blocks the request, paste a valid Supabase session token in the config cell below.
You can also provide email/password and let the notebook fetch a fresh session automatically.

In [1]:
import base64
import json
import math
import os
import re
import subprocess
import uuid
from collections import Counter, defaultdict, deque
from pathlib import Path
from urllib.parse import urlencode

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import requests

from IPython.display import HTML, display
from matplotlib.gridspec import GridSpec

try:
    import plotly.graph_objects as go
    PLOTLY_AVAILABLE = True
except Exception:
    PLOTLY_AVAILABLE = False

ROOT = Path.cwd()
ENV_PATH = ROOT / ".env"
EXPORTER = ROOT / "tools" / "export_question_bank.mjs"
EXPORT_JSON = ROOT / "tmp_question_bank_export.json"

WEAK_TOPIC_THRESHOLD_REPORT = 0.60
REMEDIATION_STEPS_REPORT = 3
REMEDIATION_ACCURACY_REPORT = 0.75
PREDICTOR_UNLOCK_ELO_REPORT = 2500
PREDICTOR_UNLOCK_COMPLETION_REPORT = 0.70
PREDICTOR_UNLOCK_COMPLETION_UI = 1.00
REPORT_SCORE_WEIGHTS = {"accuracy": 0.40, "elo": 0.30, "consistency": 0.20, "improvement": 0.10}

DIFF_ORDER = {"easy": 0, "medium": 1, "hard": 2}
DIFF_SYMBOL = {"easy": "circle", "medium": "diamond", "hard": "square"}
STATUS_COLORS = {
    "correct": "#2ea043",
    "wrong": "#f85149",
    "unseen": "#8b949e",
    "current": "#58a6ff",
    "pending": "#f2cc60",
}
EDGE_KIND_COLORS = {"same-topic": "#3fb950", "subject-flow": "#58a6ff", "subject-bridge": "#f2cc60"}


def read_env_file(path: Path) -> dict:
    env = {}
    if not path.exists():
        return env
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


ENV = {**read_env_file(ENV_PATH), **os.environ}
SUPABASE_URL = ENV.get("VITE_STUDENT_SUPABASE_URL")
SUPABASE_KEY = ENV.get("VITE_STUDENT_SUPABASE_PUBLISHABLE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("Missing Supabase URL or publishable key in .env")

In [2]:
# ============================================================
# 1. CONFIG
# ============================================================

# Paste the student UUID you want to analyze here.
# You can also set STUDENT_ID in .env or define STUDENT_ID before running this cell.
DEFAULT_STUDENT_ID = "12efa469-0330-42e1-bc64-82bed3402ae8"
STUDENT_ID_INPUT = globals().get("STUDENT_ID", ENV.get("STUDENT_ID", DEFAULT_STUDENT_ID))

# Set this to True if you prefer a notebook input box when running interactively.
# Keep it False for nbconvert / automated execution.
PROMPT_FOR_STUDENT_ID = bool(globals().get("PROMPT_FOR_STUDENT_ID", False))

STUDENT_ID = STUDENT_ID_INPUT
if PROMPT_FOR_STUDENT_ID:
    typed_student_id = input(f"Student UUID [{STUDENT_ID_INPUT}]: ").strip()
    STUDENT_ID = typed_student_id or STUDENT_ID_INPUT

# For real private student rows, Supabase RLS requires a signed-in session.
# Set these in .env, environment variables, or the notebook kernel before running.
# The publishable key alone is not an admin credential and will not bypass RLS.
SUPABASE_ACCESS_TOKEN = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjA2YTZmZDQ4LWI2MDYtNGMwNS04YzZmLTk2MDFiZWE2MWM1NyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3VraXV4ZWN2eWJ3dm5nd2lyanF0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxMmVmYTQ2OS0wMzMwLTQyZTEtYmM2NC04MmJlZDM0MDJhZTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc3NjM1NjkxLCJpYXQiOjE3Nzc2MzIwOTEsImVtYWlsIjoic29udW5haWsxMjM2a0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoic29udW5haWsxMjM2a0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiU3VuaWwiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInJvbGUiOiJzdHVkZW50Iiwic3ViIjoiMTJlZmE0NjktMDMzMC00MmUxLWJjNjQtODJiZWQzNDAyYWU4In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzczOTYwMDZ9XSwic2Vzc2lvbl9pZCI6ImJjMTVmNDE5LTMyYWQtNGNiYi1iZDVkLTY3MGI1ZGZhNWI0MiIsImlzX2Fub255bW91cyI6ZmFsc2V9.OXXT1WY0r3MTLz7GR0o_6JmYOGglHGEuGoYL0S4hLwiajcNPJIDXuuXChRxwEs8ly_p6Z38lGLN-SmrJacw3uQ"
LOGIN_EMAIL = "sonunaik1236k@gmail.com"
LOGIN_PASSWORD = "sunilnaik"


# Optional: paste a test id to focus the replay/graph.
# Accepts either website_test_id/test_history.id, or recorded_test_id such as a full mock paper id.
SELECTED_TEST_ID_INPUT = globals().get(
    "SELECTED_TEST_ID",
    globals().get("SIMULATION_TEST_ID", ENV.get("SELECTED_TEST_ID", None)),
)
SIMULATION_TEST_ID = str(SELECTED_TEST_ID_INPUT).strip() if SELECTED_TEST_ID_INPUT else None
SIMULATION_START_ELO = int(globals().get("SIMULATION_START_ELO", 1600))
SIMULATION_BANK_MODE = str(globals().get("SIMULATION_BANK_MODE", "complete")).strip().lower()
SIMULATION_STEPS_AHEAD = int(globals().get("SIMULATION_STEPS_AHEAD", 8))
SIMULATION_MODE = str(globals().get("SIMULATION_MODE", ENV.get("SIMULATION_MODE", "auto"))).strip().lower()
if SIMULATION_MODE not in {"auto", "off", "force"}:
    print(f"Unknown SIMULATION_MODE={SIMULATION_MODE!r}; using 'auto' instead.")
    SIMULATION_MODE = "auto"
SIMULATION_SESSION_COUNT = int(globals().get("SIMULATION_SESSION_COUNT", 3))
SIMULATION_SESSION_LENGTH = int(globals().get("SIMULATION_SESSION_LENGTH", 12))
SIMULATION_SUBJECT_ID = globals().get("SIMULATION_SUBJECT_ID", None)


def validate_student_id(student_id: str) -> str:
    student_id = str(student_id or "").strip()
    if not student_id:
        raise ValueError("A valid STUDENT_ID is required. Set STUDENT_ID in the first config cell or in .env.")
    try:
        uuid.UUID(student_id)
    except Exception as exc:
        raise ValueError(f"STUDENT_ID is not a valid UUID: {student_id}") from exc
    return student_id


def decode_jwt_payload(token: str | None):
    if not token or not isinstance(token, str) or token.count(".") < 2:
        return None
    try:
        payload = token.split(".")[1]
        payload += "=" * (-len(payload) % 4)
        return json.loads(base64.urlsafe_b64decode(payload.encode("utf-8")).decode("utf-8"))
    except Exception:
        return None


def fetch_access_token_with_password(email: str, password: str) -> str:
    response = requests.post(
        f"{SUPABASE_URL}/auth/v1/token?grant_type=password",
        headers={
            "apikey": SUPABASE_KEY,
            "Content-Type": "application/json",
        },
        json={"email": email, "password": password},
        timeout=30,
    )
    if not response.ok:
        detail = response.text
        try:
            detail = response.json().get("msg") or response.json().get("message") or detail
        except Exception:
            pass
        if response.status_code == 400 and "invalid_credentials" in response.text:
            raise RuntimeError(
                "Supabase login failed because LOGIN_EMAIL or LOGIN_PASSWORD is invalid. "
                "Update those values, or clear them and provide a fresh SUPABASE_ACCESS_TOKEN instead."
            )
        raise RuntimeError(f"Supabase login failed: {response.status_code} {detail}")
    body = response.json()
    access_token = body.get("access_token")
    if not access_token:
        raise RuntimeError("Supabase login succeeded but no access token was returned.")
    return access_token


def auth_headers(access_token: str | None = None):
    bearer = access_token or SUPABASE_ACCESS_TOKEN or SUPABASE_KEY
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {bearer}",
        "Accept": "application/json",
    }


def supabase_select(table: str, or_filter: str | None = None, **filters):
    global SUPABASE_ACCESS_TOKEN
    params = {"select": "*"}
    if or_filter:
        params["or"] = or_filter
    for key, value in filters.items():
        params[key] = f"eq.{value}"
    url = f"{SUPABASE_URL}/rest/v1/{table}?{urlencode(params)}"
    try:
        response = requests.get(url, headers=auth_headers(), timeout=30)
    except requests.RequestException as exc:
        raise RuntimeError(f"Supabase query failed for {table}: {exc}") from exc
    if (
        response.status_code == 401
        and "JWT expired" in response.text
        and LOGIN_EMAIL
        and LOGIN_PASSWORD
    ):
        SUPABASE_ACCESS_TOKEN = fetch_access_token_with_password(LOGIN_EMAIL, LOGIN_PASSWORD)
        try:
            response = requests.get(url, headers=auth_headers(SUPABASE_ACCESS_TOKEN), timeout=30)
        except requests.RequestException as exc:
            raise RuntimeError(f"Supabase query failed for {table}: {exc}") from exc
    if not response.ok:
        if response.status_code == 401 and "JWT expired" in response.text:
            raise RuntimeError(
                "Supabase JWT expired. Clear SUPABASE_ACCESS_TOKEN and either paste a fresh token "
                "or set LOGIN_EMAIL and LOGIN_PASSWORD so the notebook can fetch a new session."
            )
        raise RuntimeError(
            f"Supabase query failed for {table}: {response.status_code} {response.text}"
        )
    return response.json()


def safe_supabase_select(
    table: str,
    *,
    allow_missing_table: bool = False,
    allow_network_failure: bool = False,
    **filters,
):
    try:
        return supabase_select(table, **filters)
    except RuntimeError as exc:
        message = str(exc)
        if allow_missing_table and (
            "PGRST205" in message
            or "Could not find the table" in message
            or f"for {table}: 404" in message
        ):
            print(
                f"Table '{table}' is not available yet. Skipping it for now. "
                "Apply the latest Supabase migration if you want this data."
            )
            return []
        if allow_network_failure and (
            "Max retries exceeded" in message
            or "Name or service not known" in message
            or "Failed to establish a new connection" in message
            or "ConnectionError" in message
            or "HTTPSConnectionPool" in message
            or "Connection aborted" in message
            or "ConnectionResetError" in message
            or "forcibly closed" in message
        ):
            print(
                f"Supabase network access failed for '{table}'. "
                "Continuing with empty rows. Recorded-test graph/video mode will not generate replacement attempts."
            )
            return []
        raise

In [3]:
# ============================================================
# 2. EXPORT COMPLETE QUESTION DATASET + LOAD STUDENT TABLES
# ============================================================

jwt_payload = decode_jwt_payload(SUPABASE_ACCESS_TOKEN)
if not STUDENT_ID and jwt_payload and jwt_payload.get("sub"):
    STUDENT_ID = jwt_payload.get("sub")
STUDENT_ID = validate_student_id(STUDENT_ID)
print("Using STUDENT_ID:", STUDENT_ID)

if jwt_payload:
    token_sub = jwt_payload.get("sub")
    token_email = jwt_payload.get("email")
    token_exp = jwt_payload.get("exp")
    print("JWT subject:", token_sub)
    print("JWT email:", token_email)
    if token_sub and token_sub != STUDENT_ID:
        print("Warning: the JWT subject does not match STUDENT_ID. RLS may block this student's rows.")
    if token_exp:
        exp_ts = pd.to_datetime(int(token_exp), unit="s", utc=True)
        print("JWT expiry (UTC):", exp_ts)
        if exp_ts <= pd.Timestamp.now(tz="UTC"):
            print("Warning: the provided JWT is expired; attempting a credential refresh if LOGIN_EMAIL/LOGIN_PASSWORD are set.")
            SUPABASE_ACCESS_TOKEN = None

if not SUPABASE_ACCESS_TOKEN and LOGIN_EMAIL and LOGIN_PASSWORD:
    try:
        SUPABASE_ACCESS_TOKEN = fetch_access_token_with_password(LOGIN_EMAIL, LOGIN_PASSWORD)
        print("Authenticated with email/password and obtained a session token.")
    except RuntimeError as exc:
        raise RuntimeError(
            "Notebook authentication failed before loading student data. "
            "Either set valid LOGIN_EMAIL/LOGIN_PASSWORD, or clear them and paste a fresh "
            "SUPABASE_ACCESS_TOKEN in the config cell."
        ) from exc
elif not SUPABASE_ACCESS_TOKEN:
    raise RuntimeError(
        "Supabase RLS requires an authenticated session for private student rows. "
        "Set SUPABASE_ACCESS_TOKEN or LOGIN_EMAIL/LOGIN_PASSWORD; the publishable key alone cannot read test_history."
    )

try:
    subprocess.run(["node", str(EXPORTER), str(EXPORT_JSON)], check=True, cwd=ROOT)
    print(f"Exported latest question dataset to {EXPORT_JSON.name}.")
except Exception as exc:
    if EXPORT_JSON.exists():
        print(
            f"Question export refresh failed ({exc}). "
            f"Using cached {EXPORT_JSON.name} instead."
        )
    else:
        raise RuntimeError(
            f"Question export failed and no cached {EXPORT_JSON.name} file is available."
        ) from exc
export_payload = json.loads(EXPORT_JSON.read_text(encoding="utf-8"))

subjects_meta = export_payload.get("subjects", [])
subject_lookup = {item.get("id"): item for item in subjects_meta}
topic_lookup = {
    (subject.get("id"), topic.get("id")): topic
    for subject in subjects_meta
    for topic in subject.get("topics", [])
}


def get_subject_name(subject_id: str | None) -> str:
    subject = subject_lookup.get(subject_id or "")
    return subject.get("name") if subject else (subject_id or "unknown-subject")


def get_topic_name(subject_id: str | None, topic_id: str | None) -> str:
    topic = topic_lookup.get((subject_id or "", topic_id or ""))
    return topic.get("name") if topic else (topic_id or "unknown-topic")


def normalize_question_record(question: dict, source_tag: str, source_group: str) -> dict:
    row = dict(question)
    row["source_tag"] = source_tag
    row["source_group"] = source_group
    row["subjectName"] = get_subject_name(row.get("subjectId"))
    row["topicName"] = get_topic_name(row.get("subjectId"), row.get("topicId"))
    return row


question_rows = []
for item in export_payload.get("questions", []):
    question_rows.append(normalize_question_record(item, "practice-bank", "practice"))
for item in export_payload.get("adaptiveQuestions", []):
    question_rows.append(normalize_question_record(item, "adaptive-subject-bank", "adaptive"))
for item in export_payload.get("adaptiveMixQuestions", []):
    question_rows.append(normalize_question_record(item, "adaptive-mix-bank", "adaptive"))
for test in export_payload.get("tests", []):
    for question in test.get("questions", []):
        row = normalize_question_record(question, f"full-test::{test.get('id')}", "full-test")
        row["fullTestId"] = test.get("id")
        row["fullTestLabel"] = test.get("label")
        question_rows.append(row)

question_bank_full = pd.DataFrame(question_rows)
if question_bank_full.empty:
    raise RuntimeError("The project question export is empty.")

for column, default_value in {
    "difficulty": "medium",
    "eloRating": 1400,
    "marks": 1,
    "negativeMarks": 0,
    "type": "mcq",
}.items():
    if column not in question_bank_full.columns:
        question_bank_full[column] = default_value

question_bank_full["difficulty"] = question_bank_full["difficulty"].fillna("medium").str.lower()
question_bank_full["eloRating"] = pd.to_numeric(question_bank_full["eloRating"], errors="coerce").fillna(1400)
question_bank_full["marks"] = pd.to_numeric(question_bank_full["marks"], errors="coerce").fillna(1)
question_bank_full["negativeMarks"] = pd.to_numeric(question_bank_full["negativeMarks"], errors="coerce").fillna(0)

question_bank_full = (
    question_bank_full.sort_values(["id", "source_tag"])
    .groupby("id", as_index=False)
    .agg(
        {
            "subjectId": "first",
            "topicId": "first",
            "subjectName": "first",
            "topicName": "first",
            "question": "first",
            "options": "first",
            "correctAnswer": "first",
            "correctAnswers": "first" if "correctAnswers" in question_bank_full.columns else lambda values: None,
            "correctNat": "first" if "correctNat" in question_bank_full.columns else lambda values: None,
            "type": "first",
            "explanation": "first",
            "difficulty": "first",
            "eloRating": "first",
            "marks": "first",
            "negativeMarks": "first",
            "source_tag": lambda values: sorted(set(str(value) for value in values if pd.notna(value))),
            "source_group": lambda values: sorted(set(str(value) for value in values if pd.notna(value))),
            "fullTestId": lambda values: sorted(set(str(value) for value in values if pd.notna(value))),
            "fullTestLabel": lambda values: sorted(set(str(value) for value in values if pd.notna(value))),
        }
    )
)

adaptive_live_ids = {
    item.get("id")
    for item in export_payload.get("adaptiveMixQuestions", []) + export_payload.get("adaptiveQuestions", [])
    if item.get("id")
}
question_bank_full["is_live_adaptive_eligible"] = question_bank_full["id"].isin(adaptive_live_ids)
question_lookup = {row["id"]: row for row in question_bank_full.to_dict("records")}

profiles_df = pd.DataFrame(
    safe_supabase_select("profiles", user_id=STUDENT_ID)
)
test_history_df = pd.DataFrame(
    safe_supabase_select("test_history", user_id=STUDENT_ID)
)
user_progress_df = pd.DataFrame(
    safe_supabase_select("user_progress", user_id=STUDENT_ID)
)
answered_df = pd.DataFrame(
    safe_supabase_select("answered_questions", user_id=STUDENT_ID)
)
activity_df = pd.DataFrame(
    safe_supabase_select(
        "activity_events",
        allow_missing_table=True,
        or_filter=f"(actor_id.eq.{STUDENT_ID},target_user_id.eq.{STUDENT_ID})",
    )
)

if profiles_df.empty and test_history_df.empty and user_progress_df.empty and answered_df.empty and activity_df.empty:
    raise RuntimeError(
        "No visible rows were returned for STUDENT_ID=" + str(STUDENT_ID) + ". "
        "Check that the student UUID is correct and that the session token belongs to the student, "
        "an enrolled teacher, or an admin JWT allowed by RLS. No generated data will be used."
    )

for df_name, date_columns in [
    ("profiles_df", ["created_at", "updated_at", "last_active"]),
    ("test_history_df", ["completed_at"]),
    ("user_progress_df", ["last_practiced"]),
    ("answered_df", ["answered_at"]),
    ("activity_df", ["created_at"]),
]:
    df = globals()[df_name]
    if df.empty:
        continue
    for column in date_columns:
        if column in df.columns:
            df[column] = pd.to_datetime(df[column], errors="coerce", utc=True)

def parse_review_payload(value):
    if value is None:
        return None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return json.loads(text)
        except Exception:
            return None
    if isinstance(value, dict):
        return value
    return None


def get_payload_value(payload, *keys, default=None):
    if not isinstance(payload, dict):
        return default
    for key in keys:
        if key in payload and payload.get(key) is not None:
            return payload.get(key)
    return default


def normalize_test_type_label(test_type):
    text = str(test_type or "practice").strip().lower()
    if text == "full-mock":
        return "Full GATE paper"
    if text == "topic-wise":
        return "Topic-wise test"
    if text == "adaptive":
        return "Adaptive test (advanced)"
    if text.startswith("assignment"):
        return "Assignment"
    return text.replace("-", " ").title()


def enrich_test_history_frame(frame):
    if frame.empty:
        return frame
    enriched = frame.copy()
    enriched["review_payload_parsed"] = enriched.get("review_payload", pd.Series([None] * len(enriched))).apply(parse_review_payload)
    enriched["website_test_id"] = enriched["id"].astype(str)
    enriched["full_gate_paper_id"] = enriched["review_payload_parsed"].apply(
        lambda payload: get_payload_value(payload, "full_test_id", "fullTestId")
    )
    enriched["attempt_kind"] = enriched["review_payload_parsed"].apply(
        lambda payload: get_payload_value(payload, "attemptKind", "attempt_kind")
    )
    enriched["review_metadata"] = enriched["review_payload_parsed"].apply(
        lambda payload: get_payload_value(payload, "reviewMetadata", "review_metadata", default={}) or {}
    )
    enriched["recorded_test_id"] = np.where(
        enriched["full_gate_paper_id"].notna() & (enriched["full_gate_paper_id"].astype(str).str.strip() != ""),
        enriched["full_gate_paper_id"].astype(str),
        enriched["website_test_id"],
    )
    enriched["test_label"] = enriched["test_type"].apply(normalize_test_type_label)
    enriched["accuracy_pct"] = np.where(
        enriched["total_questions"] > 0,
        100 * enriched["correct_answers"] / enriched["total_questions"],
        np.nan,
    )
    enriched["score_pct"] = np.where(
        enriched["max_score"] > 0,
        100 * enriched["score"] / enriched["max_score"],
        np.nan,
    )
    enriched["subject_name"] = enriched["subject_id"].apply(get_subject_name) if "subject_id" in enriched.columns else None
    enriched["topic_name"] = enriched.apply(
        lambda row: get_topic_name(row.get("subject_id"), row.get("topic_id")), axis=1
    ) if {"subject_id", "topic_id"}.issubset(enriched.columns) else None
    return enriched.sort_values(["completed_at", "id"]).reset_index(drop=True)


if not test_history_df.empty:
    test_history_df = enrich_test_history_frame(test_history_df)


def is_unanswered_answer(answer):
    if answer is None:
        return True
    if isinstance(answer, float) and pd.isna(answer):
        return True
    if isinstance(answer, str) and not answer.strip():
        return True
    if isinstance(answer, list) and len(answer) == 0:
        return True
    return False


def normalize_answer(answer):
    if isinstance(answer, list):
        return [item for item in answer if item is not None]
    return answer


def is_question_correct(question_record: dict | None, answer):
    if question_record is None or is_unanswered_answer(answer):
        return False

    answer = normalize_answer(answer)
    qtype = question_record.get("type", "mcq")

    if qtype == "mcq":
        return answer == question_record.get("correctAnswer")

    if qtype == "msq":
        correct_answers = question_record.get("correctAnswers") or []
        return sorted(answer) == sorted(correct_answers) if isinstance(answer, list) else False

    if qtype == "nat":
        correct_nat = question_record.get("correctNat") or {}
        try:
            numeric_value = float(answer)
        except Exception:
            return False
        minimum = correct_nat.get("min")
        maximum = correct_nat.get("max")
        if minimum is None or maximum is None:
            return False
        return float(minimum) <= numeric_value <= float(maximum)

    return False


def get_review_state(question_record: dict | None, answer):
    if is_unanswered_answer(answer):
        return "unanswered"
    return "correct" if is_question_correct(question_record, answer) else "wrong"


def resolve_question_record(question_id: str, snapshot_by_id: dict | None = None):
    if snapshot_by_id and question_id in snapshot_by_id:
        return snapshot_by_id[question_id]
    return question_lookup.get(question_id)


QUESTION_TIMELINE_COLUMNS = [
    "test_id",
    "test_type",
    "completed_at",
    "subject_id",
    "topic_id",
    "score",
    "max_score",
    "step_number",
    "question_id",
    "question_text",
    "question_type",
    "difficulty",
    "question_elo",
    "marks",
    "subjectId",
    "topicId",
    "subjectName",
    "topicName",
    "answer",
    "answer_state",
    "answered",
    "correct",
    "time_spent_seconds",
    "rapid_guess_warning",
    "rapid_guess_threshold_seconds",
    "elo_adjustment",
    "warning_text",
    "remediation_for_question_id",
]

question_timeline_rows = []
for row in test_history_df.itertuples(index=False):
    payload = parse_review_payload(getattr(row, "review_payload", None))
    if not payload:
        continue

    question_ids = payload.get("question_ids") or payload.get("questionIds") or []
    answers = payload.get("answers") or []
    question_reviews = payload.get("question_reviews") or payload.get("questionReviews") or []
    question_snapshots = payload.get("question_snapshots") or payload.get("questionSnapshots") or []
    graph_path = payload.get("graph_path") or payload.get("graphPath") or {}
    graph_steps = graph_path.get("steps") if isinstance(graph_path, dict) and isinstance(graph_path.get("steps"), list) else []
    graph_question_path = (
        graph_path.get("question_path") or graph_path.get("questionPath") or []
        if isinstance(graph_path, dict)
        else []
    )
    if not question_ids and isinstance(graph_question_path, list):
        question_ids = [item for item in graph_question_path if isinstance(item, str)]
    if not question_ids and isinstance(question_snapshots, list):
        question_ids = [item.get("id") for item in question_snapshots if isinstance(item, dict) and item.get("id")]

    snapshot_by_id = {
        item.get("id"): {
            **item,
            "subjectName": get_subject_name(item.get("subjectId")),
            "topicName": get_topic_name(item.get("subjectId"), item.get("topicId")),
        }
        for item in question_snapshots
        if isinstance(item, dict) and item.get("id")
    }
    review_by_id = {
        item.get("questionId"): item
        for item in question_reviews
        if isinstance(item, dict) and item.get("questionId")
    }
    graph_step_by_id = {
        (item.get("question_id") or item.get("questionId")): item
        for item in graph_steps
        if isinstance(item, dict) and (item.get("question_id") or item.get("questionId"))
    }

    for index, question_id in enumerate(question_ids, start=1):
        question_record = resolve_question_record(question_id, snapshot_by_id)
        answer = answers[index - 1] if index - 1 < len(answers) else None
        graph_step = graph_step_by_id.get(question_id, {})
        review = {**graph_step, **review_by_id.get(question_id, {})}

        correct_value = review.get("correct")
        if correct_value is None:
            correct_value = is_question_correct(question_record, answer) if question_record else None

        question_timeline_rows.append(
            {
                "test_id": row.id,
                "test_type": row.test_type,
                "completed_at": row.completed_at,
                "subject_id": row.subject_id,
                "topic_id": row.topic_id,
                "score": row.score,
                "max_score": row.max_score,
                "step_number": int(review.get("order") or index),
                "question_id": question_id,
                "question_text": question_record.get("question") if question_record else question_id,
                "question_type": question_record.get("type") if question_record else None,
                "difficulty": question_record.get("difficulty") if question_record else None,
                "question_elo": float(question_record.get("eloRating", np.nan)) if question_record else np.nan,
                "marks": float(question_record.get("marks", np.nan)) if question_record else np.nan,
                "subjectId": question_record.get("subjectId") if question_record else None,
                "topicId": question_record.get("topicId") if question_record else None,
                "subjectName": question_record.get("subjectName") if question_record else get_subject_name(row.subject_id),
                "topicName": question_record.get("topicName") if question_record else get_topic_name(row.subject_id, row.topic_id),
                "answer": answer,
                "answer_state": get_review_state(question_record, answer),
                "answered": not is_unanswered_answer(answer),
                "correct": bool(correct_value) if correct_value is not None else None,
                "time_spent_seconds": review.get("timeSpentSeconds", review.get("time_spent_seconds")),
                "rapid_guess_warning": review.get("rapidGuessWarning", review.get("rapid_guess_warning")),
                "rapid_guess_threshold_seconds": review.get(
                    "rapidGuessThresholdSeconds", review.get("rapid_guess_threshold_seconds")
                ),
                "elo_adjustment": review.get("eloAdjustment", review.get("elo_adjustment")),
                "warning_text": review.get("warningText", review.get("warning_text")),
                "remediation_for_question_id": review.get(
                    "remediationForQuestionId", review.get("remediation_for_question_id")
                ),
            }
        )

student_question_timeline_df = pd.DataFrame(question_timeline_rows, columns=QUESTION_TIMELINE_COLUMNS)
if not student_question_timeline_df.empty:
    student_question_timeline_df["completed_at"] = pd.to_datetime(
        student_question_timeline_df["completed_at"], errors="coerce", utc=True
    )
    student_question_timeline_df = student_question_timeline_df.sort_values(
        ["completed_at", "test_id", "step_number"]
    ).reset_index(drop=True)


def parse_activity_metadata(value):
    parsed = parse_review_payload(value)
    return parsed if isinstance(parsed, dict) else {}


def get_nested_value(mapping, *keys, default=None):
    if not isinstance(mapping, dict):
        return default
    for key in keys:
        if key in mapping and mapping.get(key) is not None:
            return mapping.get(key)
    return default


def bool_or_none(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered == "true":
            return True
        if lowered == "false":
            return False
    return None


def build_live_activity_timeline(activity_frame):
    if activity_frame.empty or "event_type" not in activity_frame.columns:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    graph_events = activity_frame[
        activity_frame["event_type"].isin(["graph_path_progress", "graph_path_completed"])
    ].copy()
    if graph_events.empty or "metadata" not in graph_events.columns:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    graph_events["metadata_parsed"] = graph_events["metadata"].apply(parse_activity_metadata)
    if "created_at" in graph_events.columns:
        graph_events["created_at"] = pd.to_datetime(graph_events["created_at"], errors="coerce", utc=True)
        graph_events = graph_events.sort_values(["created_at", "event_type"], na_position="last")

    latest_rows = []
    for _, group in graph_events.groupby(
        graph_events["metadata_parsed"].apply(lambda item: get_nested_value(item, "session_id", "sessionId", default="")),
        dropna=False,
    ):
        completed = group[group["event_type"] == "graph_path_completed"]
        latest_rows.append((completed if not completed.empty else group).iloc[-1])

    timeline_rows = []
    for event_row in latest_rows:
        metadata = event_row.get("metadata_parsed", {}) or {}
        test_type = get_nested_value(metadata, "test_type", "testType", default=event_row.get("test_type", "adaptive"))
        if str(test_type or "").strip().lower() != "adaptive":
            continue

        session_id = get_nested_value(
            metadata,
            "test_history_id",
            "website_test_id",
            "testHistoryId",
            "websiteTestId",
            "session_id",
            "sessionId",
        )
        if not session_id:
            session_id = f"activity::{event_row.get('id', len(timeline_rows))}"
        session_id = str(session_id)
        completed_at = event_row.get("created_at", pd.NaT)
        subject_id = get_nested_value(metadata, "subject_id", "subjectId", default=event_row.get("subject_id"))
        topic_id = get_nested_value(metadata, "topic_id", "topicId", default=event_row.get("topic_id"))
        steps = get_nested_value(metadata, "steps", default=[]) or []
        if not steps:
            steps = [
                {"order": index, "question_id": question_id}
                for index, question_id in enumerate(
                    get_nested_value(metadata, "question_path", "questionPath", default=[]) or [],
                    start=1,
                )
            ]

        for index, step in enumerate(steps, start=1):
            if not isinstance(step, dict):
                continue
            question_id = get_nested_value(step, "question_id", "questionId")
            if not question_id:
                continue
            question_record = resolve_question_record(str(question_id))
            correct_value = bool_or_none(get_nested_value(step, "correct"))
            answered = correct_value is not None
            row_subject_id = get_nested_value(step, "subject_id", "subjectId", default=subject_id)
            row_topic_id = get_nested_value(step, "topic_id", "topicId", default=topic_id)
            timeline_rows.append(
                {
                    "test_id": session_id,
                    "test_type": "adaptive",
                    "completed_at": completed_at,
                    "subject_id": subject_id,
                    "topic_id": topic_id,
                    "score": np.nan,
                    "max_score": np.nan,
                    "step_number": int(get_nested_value(step, "order", default=index) or index),
                    "question_id": str(question_id),
                    "question_text": question_record.get("question") if question_record else str(question_id),
                    "question_type": question_record.get("type") if question_record else None,
                    "difficulty": question_record.get("difficulty") if question_record else get_nested_value(step, "difficulty"),
                    "question_elo": float(question_record.get("eloRating", np.nan)) if question_record else np.nan,
                    "marks": float(question_record.get("marks", np.nan)) if question_record else np.nan,
                    "subjectId": question_record.get("subjectId") if question_record else row_subject_id,
                    "topicId": question_record.get("topicId") if question_record else row_topic_id,
                    "subjectName": question_record.get("subjectName") if question_record else get_subject_name(row_subject_id),
                    "topicName": question_record.get("topicName") if question_record else get_topic_name(row_subject_id, row_topic_id),
                    "answer": None,
                    "answer_state": "correct" if correct_value is True else "wrong" if correct_value is False else "unanswered",
                    "answered": answered,
                    "correct": correct_value,
                    "time_spent_seconds": get_nested_value(step, "time_spent_seconds", "timeSpentSeconds"),
                    "rapid_guess_warning": get_nested_value(step, "rapid_guess_warning", "rapidGuessWarning"),
                    "rapid_guess_threshold_seconds": get_nested_value(
                        step, "rapid_guess_threshold_seconds", "rapidGuessThresholdSeconds"
                    ),
                    "elo_adjustment": get_nested_value(step, "elo_adjustment", "eloAdjustment"),
                    "warning_text": get_nested_value(step, "warning_text", "warningText"),
                    "remediation_for_question_id": get_nested_value(
                        step, "remediation_for_question_id", "remediationForQuestionId"
                    ),
                }
            )

    return pd.DataFrame(timeline_rows, columns=QUESTION_TIMELINE_COLUMNS)


def build_question_answer_activity_timeline(activity_frame, history_df, existing_timeline_df, match_window_seconds=900):
    if activity_frame.empty or history_df.empty or "event_type" not in activity_frame.columns:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    answer_events = activity_frame[activity_frame["event_type"] == "question_answered"].copy()
    if answer_events.empty or "question_id" not in answer_events.columns:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    answer_events["created_at"] = pd.to_datetime(answer_events.get("created_at"), errors="coerce", utc=True)
    answer_events = answer_events[answer_events["created_at"].notna()].sort_values(["created_at", "question_id"])
    if answer_events.empty:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    answer_events["metadata_parsed"] = answer_events.get("metadata", pd.Series([{}] * len(answer_events))).apply(parse_activity_metadata)
    history = history_df.copy()
    history["completed_at"] = pd.to_datetime(history.get("completed_at"), errors="coerce", utc=True)
    history = history[history["completed_at"].notna()].sort_values(["completed_at", "id"]).reset_index(drop=True)
    if history.empty:
        return pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)

    existing_ids = set()
    if not existing_timeline_df.empty and "test_id" in existing_timeline_df.columns:
        existing_ids = set(existing_timeline_df["test_id"].dropna().astype(str))

    used_event_indices = set()
    timeline_rows = []
    for history_index, history_row in history.iterrows():
        history_id = str(history_row.get("id"))
        if not history_id or history_id in existing_ids:
            continue

        completed_at = history_row.get("completed_at")
        next_completed_at = (
            history.iloc[history_index + 1].get("completed_at")
            if history_index + 1 < len(history)
            else pd.NaT
        )
        window_start = completed_at - pd.Timedelta(seconds=90)
        window_end = completed_at + pd.Timedelta(seconds=match_window_seconds)
        if pd.notna(next_completed_at):
            window_end = min(window_end, next_completed_at - pd.Timedelta(seconds=1))

        candidate_events = answer_events[
            (answer_events["created_at"] >= window_start)
            & (answer_events["created_at"] <= window_end)
            & (~answer_events.index.isin(used_event_indices))
        ].copy()
        if candidate_events.empty:
            continue

        expected_attempts = history_row.get("questions_attempted")
        try:
            expected_attempts = int(expected_attempts) if pd.notna(expected_attempts) else None
        except Exception:
            expected_attempts = None
        if expected_attempts is not None and expected_attempts > 0:
            candidate_events = candidate_events.head(expected_attempts)
        if candidate_events.empty:
            continue

        used_event_indices.update(candidate_events.index.tolist())
        for step_number, (_, event_row) in enumerate(candidate_events.iterrows(), start=1):
            question_id = str(event_row.get("question_id") or "").strip()
            if not question_id:
                continue
            metadata = event_row.get("metadata_parsed", {}) or {}
            question_record = resolve_question_record(question_id)
            correct_value = bool_or_none(get_nested_value(metadata, "was_correct", "correct", "is_correct", "isCorrect"))
            row_subject_id = history_row.get("subject_id") if pd.notna(history_row.get("subject_id")) else event_row.get("subject_id")
            row_topic_id = history_row.get("topic_id") if pd.notna(history_row.get("topic_id")) else event_row.get("topic_id")
            timeline_rows.append(
                {
                    "test_id": history_id,
                    "test_type": history_row.get("test_type"),
                    "completed_at": completed_at,
                    "subject_id": row_subject_id,
                    "topic_id": row_topic_id,
                    "score": history_row.get("score"),
                    "max_score": history_row.get("max_score"),
                    "step_number": step_number,
                    "question_id": question_id,
                    "question_text": question_record.get("question") if question_record else question_id,
                    "question_type": question_record.get("type") if question_record else None,
                    "difficulty": question_record.get("difficulty") if question_record else None,
                    "question_elo": float(question_record.get("eloRating", np.nan)) if question_record else np.nan,
                    "marks": float(question_record.get("marks", np.nan)) if question_record else np.nan,
                    "subjectId": question_record.get("subjectId") if question_record else row_subject_id,
                    "topicId": question_record.get("topicId") if question_record else row_topic_id,
                    "subjectName": question_record.get("subjectName") if question_record else get_subject_name(row_subject_id),
                    "topicName": question_record.get("topicName") if question_record else get_topic_name(row_subject_id, row_topic_id),
                    "answer": None,
                    "answer_state": "correct" if correct_value is True else "wrong" if correct_value is False else "unanswered",
                    "answered": correct_value is not None,
                    "correct": correct_value,
                    "time_spent_seconds": None,
                    "rapid_guess_warning": None,
                    "rapid_guess_threshold_seconds": None,
                    "elo_adjustment": None,
                    "warning_text": "Recovered from question_answered activity event",
                    "remediation_for_question_id": None,
                }
            )

    return pd.DataFrame(timeline_rows, columns=QUESTION_TIMELINE_COLUMNS)


def alias_live_activity_sessions_to_test_history(activity_timeline_df, history_df, existing_timeline_df, match_window_seconds=900):
    if activity_timeline_df.empty or history_df.empty or "id" not in history_df.columns:
        return activity_timeline_df

    adaptive_candidates = history_df.copy()
    if "test_type" in adaptive_candidates.columns:
        adaptive_candidates = adaptive_candidates[
            adaptive_candidates["test_type"].astype(str).str.lower() == "adaptive"
        ].copy()
    if adaptive_candidates.empty or "completed_at" not in adaptive_candidates.columns:
        return activity_timeline_df

    mapped = activity_timeline_df.copy()
    adaptive_candidates["_completed_at"] = pd.to_datetime(
        adaptive_candidates["completed_at"], errors="coerce", utc=True
    )
    adaptive_candidates = adaptive_candidates[adaptive_candidates["_completed_at"].notna()].copy()
    if adaptive_candidates.empty:
        return mapped

    history_ids = set(adaptive_candidates["id"].dropna().astype(str))
    used_history_ids = set()
    if not existing_timeline_df.empty and "test_id" in existing_timeline_df.columns:
        used_history_ids.update(
            set(existing_timeline_df["test_id"].dropna().astype(str)) & history_ids
        )

    for activity_session_id, group in mapped.groupby("test_id", dropna=False):
        activity_session_id = str(activity_session_id)
        if activity_session_id in history_ids:
            used_history_ids.add(activity_session_id)
            continue

        group_completed_at = pd.to_datetime(group["completed_at"], errors="coerce", utc=True).max()
        if pd.isna(group_completed_at):
            continue

        open_candidates = adaptive_candidates[
            ~adaptive_candidates["id"].astype(str).isin(used_history_ids)
        ].copy()
        if open_candidates.empty:
            continue

        group_subjects = {
            str(value).strip()
            for value in group.get("subject_id", pd.Series(dtype=object)).dropna().tolist()
            if str(value).strip()
        }
        subject_matched = open_candidates
        if group_subjects and "subject_id" in open_candidates.columns:
            candidate_subjects = open_candidates["subject_id"].astype(str).str.strip()
            scoped = open_candidates[candidate_subjects.isin(group_subjects)].copy()
            if not scoped.empty:
                subject_matched = scoped

        subject_matched["_delta_seconds"] = (
            subject_matched["_completed_at"] - group_completed_at
        ).dt.total_seconds().abs()
        closest = subject_matched.sort_values(["_delta_seconds", "_completed_at"]).iloc[0]
        if float(closest["_delta_seconds"]) > float(match_window_seconds):
            continue

        history_id = str(closest["id"])
        mapped.loc[group.index, "test_id"] = history_id
        used_history_ids.add(history_id)
        print(
            f"Linked graph activity session {activity_session_id!r} to website_test_id/test_history.id "
            f"{history_id!r} for live replay."
        )

    return mapped


live_activity_timeline_df = build_live_activity_timeline(activity_df)
live_activity_timeline_df = alias_live_activity_sessions_to_test_history(
    live_activity_timeline_df,
    test_history_df,
    student_question_timeline_df,
)
question_answer_activity_timeline_df = build_question_answer_activity_timeline(
    activity_df,
    test_history_df,
    student_question_timeline_df,
)
if not question_answer_activity_timeline_df.empty:
    before_rows = len(student_question_timeline_df)
    student_question_timeline_df = pd.concat(
        [student_question_timeline_df, question_answer_activity_timeline_df],
        ignore_index=True,
    )
    student_question_timeline_df["completed_at"] = pd.to_datetime(
        student_question_timeline_df["completed_at"], errors="coerce", utc=True
    )
    student_question_timeline_df = (
        student_question_timeline_df.sort_values(["completed_at", "test_id", "step_number"], na_position="last")
        .drop_duplicates(["test_id", "step_number", "question_id"], keep="first")
        .reset_index(drop=True)
    )
    print(
        "Question-answer activity fallback rows added:",
        len(student_question_timeline_df) - before_rows,
        "from question_answered activity events.",
    )

if not live_activity_timeline_df.empty:
    before_rows = len(student_question_timeline_df)
    student_question_timeline_df = pd.concat(
        [student_question_timeline_df, live_activity_timeline_df],
        ignore_index=True,
    )
    student_question_timeline_df["completed_at"] = pd.to_datetime(
        student_question_timeline_df["completed_at"], errors="coerce", utc=True
    )
    student_question_timeline_df = (
        student_question_timeline_df.sort_values(["completed_at", "test_id", "step_number"], na_position="last")
        .drop_duplicates(["test_id", "step_number", "question_id"], keep="first")
        .reset_index(drop=True)
    )
    print(
        "Live activity replay rows added:",
        len(student_question_timeline_df) - before_rows,
        "from graph_path activity events.",
    )

    activity_session_rows = []
    for session_id, group in live_activity_timeline_df.groupby("test_id", dropna=False):
        answered_group = group[group["answered"] == True]
        correct_count = int(answered_group["correct"].fillna(False).sum()) if not answered_group.empty else 0
        total_questions = int(group["question_id"].nunique())
        score_value = float(correct_count)
        max_score_value = float(total_questions)
        activity_session_rows.append(
            {
                "id": str(session_id),
                "user_id": STUDENT_ID,
                "test_type": "adaptive",
                "subject_id": group["subject_id"].dropna().iloc[-1] if group["subject_id"].notna().any() else None,
                "topic_id": group["topic_id"].dropna().iloc[-1] if group["topic_id"].notna().any() else None,
                "score": score_value,
                "max_score": max_score_value,
                "questions_attempted": int(len(answered_group)),
                "correct_answers": correct_count,
                "total_questions": total_questions,
                "duration_seconds": np.nan,
                "completed_at": group["completed_at"].max(),
                "review_payload": None,
                "review_payload_parsed": None,
                "website_test_id": str(session_id),
                "full_gate_paper_id": None,
                "attempt_kind": "adaptive",
                "review_metadata": {"source": "activity_events"},
                "recorded_test_id": str(session_id),
                "test_label": normalize_test_type_label("adaptive"),
                "accuracy_pct": 100 * correct_count / max(total_questions, 1),
                "score_pct": 100 * score_value / max(max_score_value, 1),
                "subject_name": get_subject_name(group["subject_id"].dropna().iloc[-1]) if group["subject_id"].notna().any() else None,
                "topic_name": (
                    get_topic_name(group["subject_id"].dropna().iloc[-1], group["topic_id"].dropna().iloc[-1])
                    if group["subject_id"].notna().any() and group["topic_id"].notna().any()
                    else None
                ),
            }
        )

    activity_sessions_df = pd.DataFrame(activity_session_rows)
    if not activity_sessions_df.empty:
        existing_history_ids = (
            set(test_history_df["id"].dropna().astype(str))
            if not test_history_df.empty and "id" in test_history_df.columns
            else set()
        )
        activity_sessions_df = activity_sessions_df[
            ~activity_sessions_df["id"].astype(str).isin(existing_history_ids)
        ]
        if not activity_sessions_df.empty:
            test_history_df = pd.concat([test_history_df, activity_sessions_df], ignore_index=True, sort=False)
            print("Live adaptive activity sessions added to test_history_df:", len(activity_sessions_df))

session_scope_rows = []
if not student_question_timeline_df.empty:
    for test_id, group in student_question_timeline_df.groupby("test_id", dropna=False):
        subject_ids = sorted(
            {
                str(value).strip()
                for value in group["subjectId"].dropna().tolist()
                if str(value).strip()
            }
        )
        topic_ids = sorted(
            {
                str(value).strip()
                for value in group["topicId"].dropna().tolist()
                if str(value).strip()
            }
        )
        session_scope_rows.append(
            {
                "test_id": test_id,
                "derived_subject_id": subject_ids[0] if len(subject_ids) == 1 else None,
                "derived_topic_id": topic_ids[0] if len(topic_ids) == 1 else None,
                "derived_subject_scope": (
                    get_subject_name(subject_ids[0])
                    if len(subject_ids) == 1
                    else "Mixed subjects"
                    if len(subject_ids) > 1
                    else None
                ),
                "derived_topic_scope": (
                    get_topic_name(subject_ids[0], topic_ids[0])
                    if len(subject_ids) == 1 and len(topic_ids) == 1
                    else "Mixed topics"
                    if len(topic_ids) > 1
                    else None
                ),
            }
        )

session_scope_df = pd.DataFrame(
    session_scope_rows,
    columns=[
        "test_id",
        "derived_subject_id",
        "derived_topic_id",
        "derived_subject_scope",
        "derived_topic_scope",
    ],
)

if not test_history_df.empty:
    test_history_df = test_history_df.merge(session_scope_df, left_on="id", right_on="test_id", how="left")
    test_history_df = test_history_df.drop(columns=["test_id"], errors="ignore")
    if "subject_id" in test_history_df.columns:
        subject_series = test_history_df["subject_id"]
        missing_subject_mask = subject_series.isna() | (subject_series.astype(str).str.strip() == "")
        test_history_df.loc[missing_subject_mask, "subject_id"] = test_history_df.loc[
            missing_subject_mask, "derived_subject_id"
        ]
    if "topic_id" in test_history_df.columns:
        topic_series = test_history_df["topic_id"]
        missing_topic_mask = topic_series.isna() | (topic_series.astype(str).str.strip() == "")
        test_history_df.loc[missing_topic_mask, "topic_id"] = test_history_df.loc[
            missing_topic_mask, "derived_topic_id"
        ]
    test_history_df = enrich_test_history_frame(test_history_df)

if not answered_df.empty:
    answered_enriched_df = answered_df.merge(
        question_bank_full[
            ["id", "subjectId", "topicId", "subjectName", "topicName", "difficulty", "eloRating", "marks", "type"]
        ],
        left_on="question_id",
        right_on="id",
        how="left",
    )
else:
    answered_enriched_df = answered_df.copy()

print("Unique questions in consolidated dataset:", len(question_bank_full))
print("Adaptive-eligible questions in live banks:", int(question_bank_full["is_live_adaptive_eligible"].sum()))
print("Tests loaded for student:", len(test_history_df))
print("Unique website test ids:", test_history_df["website_test_id"].nunique() if "website_test_id" in test_history_df.columns else 0)
if "test_label" in test_history_df.columns:
    print("Tests by type:", test_history_df["test_label"].value_counts().to_dict())
print("Question timeline rows available for replay:", len(student_question_timeline_df))

display(profiles_df)
display(test_history_df[[column for column in ["website_test_id", "recorded_test_id", "test_label", "completed_at", "score", "max_score", "score_pct", "accuracy_pct", "subject_name", "topic_name"] if column in test_history_df.columns]].tail(20))
display(student_question_timeline_df.head(20))
display(activity_df.head(20))

Using STUDENT_ID: 12efa469-0330-42e1-bc64-82bed3402ae8
JWT subject: 12efa469-0330-42e1-bc64-82bed3402ae8
JWT email: sonunaik1236k@gmail.com
JWT expiry (UTC): 2026-05-01 11:41:31+00:00
Warning: the provided JWT is expired; attempting a credential refresh if LOGIN_EMAIL/LOGIN_PASSWORD are set.
Authenticated with email/password and obtained a session token.
Exported latest question dataset to tmp_question_bank_export.json.
Live activity replay rows added: 0 from graph_path activity events.
Unique questions in consolidated dataset: 999
Adaptive-eligible questions in live banks: 804
Tests loaded for student: 78
Unique website test ids: 78
Tests by type: {'Topic-wise test': 38, 'Adaptive test (advanced)': 31, 'Full GATE paper': 5, 'Assignment': 4}
Question timeline rows available for replay: 98

C:\Users\sunil\AppData\Local\Temp\ipykernel_29852\1762973310.py:829: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  correct_count = int(answered_group["correct"].fillna(False).sum()) if not answered_group.empty else 0

,id,user_id,full_name,avatar_url,elo_rating,streak_count,last_active,study_goal,theme,created_at,updated_at,email,role
0,c047e80e-28aa-44bd-b4ae-0e2f376c14a6,12efa469-0330-42e1-bc64-82bed3402ae8,Sunil,None,1500,0,2026-04-08 21:54:59.023003+00:00,crack_gate,system,2026-04-08 21:54:59.023003+00:00,2026-04-08 21:54:59.023003+00:00,sonunaik1236k@gmail.com,student

,website_test_id,recorded_test_id,test_label,completed_at,score,max_score,score_pct,accuracy_pct,subject_name,topic_name
58,83a6e533-df2e-4bba-b8d0-6c148c570073,83a6e533-df2e-4bba-b8d0-6c148c570073,Topic-wise test,2026-04-23 16:13:26.928000+00:00,0.03,13,0.230769,20.000000,Machine Learning,NaN
59,4d7a5b89-9efd-4dd7-9ac3-1926cae001fe,4d7a5b89-9efd-4dd7-9ac3-1926cae001fe,Adaptive test (advanced),2026-04-23 16:31:52.703000+00:00,-0.62,20,-3.100000,20.000000,NaN,NaN
60,78084fff-2d88-440e-be02-d3a265a0761d,78084fff-2d88-440e-be02-d3a265a0761d,Topic-wise test,2026-04-23 16:45:38.136000+00:00,-2.63,18,-14.611111,10.000000,Artificial Intelligence,NaN
61,67f89dfa-d791-4479-b416-6b35a19e6738,67f89dfa-d791-4479-b416-6b35a19e6738,Adaptive test (advanced),2026-04-23 17:51:18.843000+00:00,-4.62,17,-27.176471,0.000000,Probability & Statistics,NaN
62,3e4a12f3-e844-4dcd-9b36-111f6ec19a8a,3e4a12f3-e844-4dcd-9b36-111f6ec19a8a,Topic-wise test,2026-04-23 18:17:39.358000+00:00,6.00,17,35.294118,40.000000,Calculus & Optimization,NaN
63,d9ada535-0a26-4a0e-ae52-8747ce5cd81f,d9ada535-0a26-4a0e-ae52-8747ce5cd81f,Adaptive test (advanced),2026-04-23 18:25:40.711000+00:00,-0.62,20,-3.100000,20.000000,NaN,NaN
64,71f0d469-e80b-4636-a66d-6a21bfc885b2,71f0d469-e80b-4636-a66d-6a21bfc885b2,Topic-wise test,2026-04-23 18:49:15.657000+00:00,-1.32,18,-7.333333,0.000000,Calculus & Optimization,NaN
65,313a698f-9591-462a-b01f-0caad762f73c,313a698f-9591-462a-b01f-0caad762f73c,Topic-wise test,2026-04-23 21:04:23.544000+00:00,1.01,18,5.611111,10.000000,Calculus & Optimization,NaN
66,3d7741fb-6ae7-43fa-a42e-1377d31bbeaa,3d7741fb-6ae7-43fa-a42e-1377d31bbeaa,Topic-wise test,2026-04-24 03:38:40.078000+00:00,-0.98,14,-7.000000,10.000000,Probability & Statistics,NaN
67,74f52ef7-cc23-41b8-8f1b-0c5b31b6fa72,74f52ef7-cc23-41b8-8f1b-0c5b31b6fa72,Topic-wise test,2026-04-24 05:52:56.629000+00:00,6.68,16,41.750000,40.000000,Probability & Statistics,Probability Basics
68,ee6622d6-f8de-4df3-9bf2-377c7ca07523,ee6622d6-f8de-4df3-9bf2-377c7ca07523,Full GATE paper,2026-04-27 06:38:05.363000+00:00,29.05,100,29.050000,33.846154,NaN,NaN
69,f20a3d65-2335-4a93-a8ee-7724bd75e7a0,f20a3d65-2335-4a93-a8ee-7724bd75e7a0,Topic-wise test,2026-04-27 06:52:56.750000+00:00,10.68,16,66.750000,70.000000,Linear Algebra,Matrices & Determinants
70,cb4afea2-e651-444c-9f17-8cfb716e5a27,cb4afea2-e651-444c-9f17-8cfb716e5a27,Adaptive test (advanced),2026-04-27 06:58:16.045000+00:00,15.34,20,76.700000,80.000000,Linear Algebra,NaN
71,847dd981-819f-444c-8298-fdf4a63d9b6b,847dd981-819f-444c-8298-fdf4a63d9b6b,Assignment,2026-04-28 05:07:11.959000+00:00,1.71,22,7.772727,33.333333,Programming & DSA,Complexity Analysis
72,fbd2839c-11c5-48cf-aa97-1309d724cf77,fbd2839c-11c5-48cf-aa97-1309d724cf77,Adaptive test (advanced),2026-04-30 22:09:16.294000+00:00,21.46,84,25.547619,40.476190,NaN,NaN
73,ba88a15f-581b-4542-b995-700db9284098,ba88a15f-581b-4542-b995-700db9284098,Topic-wise test,2026-04-30 22:48:40.477000+00:00,-1.98,17,-11.647059,0.000000,Linear Algebra,NaN
74,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,Adaptive test (advanced),2026-05-01 11:13:36.384000+00:00,-3.94,20,-19.700000,10.000000,Calculus & Optimization,unknown-topic
75,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,Adaptive test (advanced),2026-05-01 12:08:49.217000+00:00,23.87,109,21.899083,40.000000,unknown-subject,unknown-topic
76,c5eb3955-1aed-4b7f-8332-96fe30752eb5,c5eb3955-1aed-4b7f-8332-96fe30752eb5,Topic-wise test,2026-05-07 18:46:50.345000+00:00,2.68,17,15.764706,30.000000,Database Management Systems,Normalization
77,b362dfde-97c4-4e67-95cf-4b99cae00c20,b362dfde-97c4-4e67-95cf-4b99cae00c20,Adaptive test (advanced),2026-05-13 05:11:08.970000+00:00,8.70,26,33.461538,46.153846,Calculus & Optimization,unknown-topic

,test_id,test_type,completed_at,subject_id,topic_id,score,max_score,step_number,question_id,question_text,...,answer,answer_state,answered,correct,time_spent_seconds,rapid_guess_warning,rapid_guess_threshold_seconds,elo_adjustment,warning_text,remediation_for_question_id
0,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,1,co-44,Changing order of integration requires?,...,1,wrong,True,False,2,False,41.0,0,None,None
1,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,2,co-40,Integration by parts formula is?,...,1,wrong,True,False,2,False,26.0,0,None,None
2,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,3,co-45,The integral ∫_0^∞ e^-x dx equals?,...,0,wrong,True,False,1,False,26.0,0,None,None
3,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,4,co-46,Triple integral represents?,...,2,wrong,True,False,1,False,26.0,0,None,None
4,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,5,co-33,Fundamental theorem of calculus connects?,...,1,wrong,True,False,2,False,42.0,0,None,None
5,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,6,co-34,If ∫ f(x)dx = F(x) then F'(x)=?,...,0,correct,True,True,1,True,26.0,9,Solved in 1s against an estimated minimum of 2...,None
6,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,7,co-37,The integral ∫_0^π sin x dx equals?,...,1,wrong,True,False,1,False,26.0,0,None,None
7,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,8,co-38,If f(x) is odd then ∫_-a^a f(x)dx equals?,...,2,wrong,True,False,1,False,26.0,0,None,None
8,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,9,co-39,If f(x) is even then ∫_-a^a f(x)dx equals?,...,0,wrong,True,False,1,False,26.0,0,None,None
9,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,adaptive,2026-05-01 11:13:36.384000+00:00,None,None,-3.94,20.0,10,co-5,"If f(x,y)=x^2+y^2, then grad f at (1,2) is:",...,2,wrong,True,False,3,False,26.0,0,None,None
10,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,1,co-44,Changing order of integration requires?,...,2,wrong,True,False,43,False,41.0,0,None,None
11,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,2,co-40,Integration by parts formula is?,...,1,wrong,True,False,25,False,26.0,0,None,None
12,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,3,mock2-q8,Consider the series ∑_{n=1}^∞ 1/n(n+1). Which ...,...,[1],wrong,True,False,8,False,27.0,0,None,None
13,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,4,mock3-q8,Consider the series ∑_{n=2}^∞ 1/(n ln n). Whic...,...,"[0, 1]",wrong,True,False,3,False,28.0,0,None,None
14,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,5,co-33,Fundamental theorem of calculus connects?,...,1,wrong,True,False,3,False,42.0,0,None,None
15,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,6,co-37,The integral ∫_0^π sin x dx equals?,...,0,wrong,True,False,2,False,26.0,0,None,None
16,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,7,co-38,If f(x) is odd then ∫_-a^a f(x)dx equals?,...,2,wrong,True,False,5,False,26.0,0,None,None
17,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,8,co-39,If f(x) is even then ∫_-a^a f(x)dx equals?,...,0,wrong,True,False,7,False,26.0,0,None,None
18,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,9,co-5,"If f(x,y)=x^2+y^2, then grad f at (1,2) is:",...,1,correct,True,True,4,True,26.0,9,Solved in 4s against an estimated minimum of 2...,None
19,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,adaptive,2026-05-01 12:08:49.217000+00:00,None,None,23.87,109.0,10,co-2,"Let f(x, y) = x²y + xy². What is ∂²f / ∂x∂y?",...,0,correct,True,True,1,True,41.0,10,Solved in 1s against an estimated minimum of 4...,None

,id,actor_id,actor_role,actor_name,event_type,target_user_id,course_id,assignment_id,question_id,subject_id,topic_id,metadata,created_at
0,a338e250-16ce-4ec2-9beb-d71c53790f2d,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-44,None,None,"{'steps': [{'order': 1, 'correct': None, 'topi...",2026-05-01 11:13:16.970827+00:00
1,cb70d4e8-daf8-48d1-8cfa-a45e9e0c758b,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-44,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:17.787619+00:00
2,a01bf80a-a370-44cb-aaf6-3ba5ba8e4641,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-40,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:19.210581+00:00
3,7366be6b-8c5e-461a-b7ab-99ffbe9456d4,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-40,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:20.131258+00:00
4,f47f8f3c-790c-491e-8531-eccfe98d2cf0,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-45,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:21.368022+00:00
5,5b9863d7-ba93-4eeb-bd06-b0ff02e476c3,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-45,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:22.252028+00:00
6,6ae66c31-af42-4f34-a516-e846570892ed,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,mock3-q10,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 12:08:14.746679+00:00
7,1cfc456c-a963-4c03-b072-3f888d8f4a56,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,mock6-q7,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 12:08:23.256738+00:00
8,308a9a1d-072a-45d7-a04a-4a615cc53905,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,mock2-q1,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 12:08:30.645652+00:00
9,69559ded-6990-44c4-804b-93fc499cf093,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-46,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:23.222246+00:00
10,3d61e812-890b-4c07-a39e-4ab1a77718db,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-33,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:26.048965+00:00
11,fae16107-f90a-407a-bbc4-b497423aa820,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-37,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:28.206772+00:00
12,314682d5-2fd0-4540-899d-49ae9567f33d,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-38,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:29.946746+00:00
13,e5d0f907-5856-48a7-915a-9693b9aaf13a,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-5,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:32.749137+00:00
14,3d1faec3-321f-4797-be9b-37774fdfb7b0,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,question_answered,None,None,None,co-44,None,None,{'was_correct': False},2026-05-01 11:13:36.700014+00:00
15,3f80169f-96a0-4a92-abd2-e0a3e0e36164,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,question_answered,None,None,None,co-34,None,None,{'was_correct': True},2026-05-01 11:13:36.738481+00:00
16,b6001fed-7292-486f-b82c-9df13c15b7af,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,question_answered,None,None,None,co-33,None,None,{'was_correct': False},2026-05-01 11:13:36.877570+00:00
17,75190dbb-0cd5-43c9-b614-679f84d41611,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,test_completed,None,None,None,None,None,None,"{'score': -3.940000000000001, 'max_score': 20,...",2026-05-01 11:13:37.007219+00:00
18,3e4636ea-679c-4553-8855-b3cf020fe328,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-46,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:23.736700+00:00
19,17ad80d3-aa17-4785-b32a-69a6bc98bc8f,12efa469-0330-42e1-bc64-82bed3402ae8,student,Sunil,graph_path_progress,None,None,None,co-34,None,None,"{'steps': [{'order': 1, 'correct': False, 'top...",2026-05-01 11:13:26.977472+00:00

In [4]:
# ============================================================
# 3. ACCOUNT, PERFORMANCE, THRESHOLDS, AND REPORT-STYLE SCORE MODEL
# ============================================================

profile = profiles_df.iloc[0].to_dict() if not profiles_df.empty else {}
current_elo = int(profile.get("elo_rating", 1500) or 1500)

question_attempts_df = student_question_timeline_df.copy()
answered_attempts_df = (
    question_attempts_df[question_attempts_df["answered"] == True].copy()
    if not question_attempts_df.empty
    else pd.DataFrame()
)
correct_attempts_df = (
    answered_attempts_df[answered_attempts_df["correct"] == True].copy()
    if not answered_attempts_df.empty
    else pd.DataFrame()
)
wrong_attempts_df = (
    answered_attempts_df[answered_attempts_df["correct"] == False].copy()
    if not answered_attempts_df.empty
    else pd.DataFrame()
)

account_summary_df = pd.DataFrame(
    [
        {
            "student_user_id": STUDENT_ID,
            "profile_row_id": profile.get("id"),
            "full_name": profile.get("full_name"),
            "email": profile.get("email"),
            "role": profile.get("role"),
            "elo_rating": current_elo,
            "streak_count": profile.get("streak_count"),
            "study_goal": profile.get("study_goal"),
            "theme": profile.get("theme"),
            "last_active": profile.get("last_active"),
            "created_at": profile.get("created_at"),
            "updated_at": profile.get("updated_at"),
        }
    ]
)

test_summary_df = (
    test_history_df.groupby("test_type", dropna=False)
    .agg(
        tests_completed=("id", "count"),
        total_questions=("total_questions", "sum"),
        questions_attempted=("questions_attempted", "sum"),
        correct_answers=("correct_answers", "sum"),
        mean_accuracy_pct=("accuracy_pct", "mean"),
        mean_score_pct=("score_pct", "mean"),
        total_duration_seconds=("duration_seconds", "sum"),
    )
    .reset_index()
    .sort_values(["tests_completed", "mean_accuracy_pct"], ascending=[False, False])
    if not test_history_df.empty
    else pd.DataFrame(
        columns=[
            "test_type",
            "tests_completed",
            "total_questions",
            "questions_attempted",
            "correct_answers",
            "mean_accuracy_pct",
            "mean_score_pct",
            "total_duration_seconds",
        ]
    )
)

if not user_progress_df.empty:
    user_progress_df["accuracy_pct"] = np.where(
        user_progress_df["total"] > 0,
        100 * user_progress_df["correct"] / user_progress_df["total"],
        np.nan,
    )

subject_progress_df = (
    user_progress_df[(user_progress_df["topic_id"].isna()) | (user_progress_df["topic_id"] == "__overall__")].copy()
    if not user_progress_df.empty
    else pd.DataFrame()
)

if not subject_progress_df.empty:
    subject_progress_df["subjectName"] = subject_progress_df["subject_id"].map(get_subject_name)
    subject_progress_df = subject_progress_df.rename(
        columns={"subject_id": "subjectId", "correct": "correctAnswers", "total": "totalAnswers"}
    )
else:
    if answered_attempts_df.empty:
        subject_progress_df = pd.DataFrame(
            columns=["subjectId", "subjectName", "correctAnswers", "totalAnswers", "accuracy_pct"]
        )
    else:
        subject_progress_df = (
            answered_attempts_df.groupby(["subjectId", "subjectName"], dropna=False)["correct"]
            .agg(["count", "sum"])
            .reset_index()
            .rename(columns={"count": "totalAnswers", "sum": "correctAnswers"})
        )
        subject_progress_df["accuracy_pct"] = np.where(
            subject_progress_df["totalAnswers"] > 0,
            100 * subject_progress_df["correctAnswers"] / subject_progress_df["totalAnswers"],
            np.nan,
        )

topic_progress_df = (
    user_progress_df[
        user_progress_df["topic_id"].notna() & (user_progress_df["topic_id"] != "__overall__")
    ].copy()
    if not user_progress_df.empty
    else pd.DataFrame()
)
if not topic_progress_df.empty:
    topic_progress_df["subjectName"] = topic_progress_df["subject_id"].map(get_subject_name)
    topic_progress_df["topicName"] = topic_progress_df.apply(
        lambda row: get_topic_name(row["subject_id"], row["topic_id"]), axis=1
    )
    topic_progress_df = topic_progress_df.rename(
        columns={
            "subject_id": "subjectId",
            "topic_id": "topicId",
            "correct": "correctAnswers",
            "total": "totalAnswers",
        }
    )
else:
    if answered_attempts_df.empty:
        topic_progress_df = pd.DataFrame(
            columns=[
                "subjectId",
                "topicId",
                "subjectName",
                "topicName",
                "correctAnswers",
                "totalAnswers",
                "accuracy_pct",
            ]
        )
    else:
        topic_progress_df = (
            answered_attempts_df.groupby(["subjectId", "topicId", "subjectName", "topicName"], dropna=False)["correct"]
            .agg(["count", "sum"])
            .reset_index()
            .rename(columns={"count": "totalAnswers", "sum": "correctAnswers"})
        )

if not topic_progress_df.empty and "accuracy_pct" not in topic_progress_df.columns:
    topic_progress_df["accuracy_pct"] = np.where(
        topic_progress_df["totalAnswers"] > 0,
        100 * topic_progress_df["correctAnswers"] / topic_progress_df["totalAnswers"],
        np.nan,
    )

weak_topics_report_df = (
    topic_progress_df[topic_progress_df["accuracy_pct"] < WEAK_TOPIC_THRESHOLD_REPORT * 100]
    .sort_values(["accuracy_pct", "totalAnswers"], ascending=[True, False])
    .reset_index(drop=True)
    if not topic_progress_df.empty
    else pd.DataFrame(columns=topic_progress_df.columns)
)

question_outcome_summary_df = pd.DataFrame(
    [
        {"metric": "tests_completed", "value": int(len(test_history_df))},
        {"metric": "unique_tests_completed", "value": int(test_history_df["id"].nunique()) if not test_history_df.empty else 0},
        {"metric": "questions_answered", "value": int(len(answered_attempts_df)) if not answered_attempts_df.empty else 0},
        {"metric": "correct_answers", "value": int(len(correct_attempts_df)) if not correct_attempts_df.empty else 0},
        {"metric": "wrong_answers", "value": int(len(wrong_attempts_df)) if not wrong_attempts_df.empty else 0},
        {
            "metric": "unique_questions_attempted",
            "value": int(answered_attempts_df["question_id"].nunique()) if not answered_attempts_df.empty else 0,
        },
        {
            "metric": "coverage_percent_of_full_dataset",
            "value": round(
                100
                * (
                    answered_attempts_df["question_id"].nunique() / max(len(question_bank_full), 1)
                    if not answered_attempts_df.empty
                    else 0
                ),
                2,
            ),
        },
        {
            "metric": "rapid_guess_flags",
            "value": int(
                question_attempts_df["rapid_guess_warning"].fillna(False).astype(bool).sum()
            )
            if not question_attempts_df.empty
            else 0,
        },
    ]
)

activity_summary_df = (
    activity_df.groupby("event_type").size().reset_index(name="count").sort_values("count", ascending=False)
    if not activity_df.empty
    else pd.DataFrame(columns=["event_type", "count"])
)

available_full_tests_count = len(export_payload.get("tests", []))
available_topic_count = sum(len(subject.get("topics", [])) for subject in subjects_meta)
available_subject_count = len(subjects_meta)

full_mock_completion_live = (
    min(
        1.0,
        test_history_df[test_history_df["test_type"] == "full-mock"]["id"].nunique() / max(available_full_tests_count, 1),
    )
    if not test_history_df.empty
    else 0.0
)
topic_wise_completion_live = (
    min(
        1.0,
        test_history_df[
            (test_history_df["test_type"] == "topic-wise") & test_history_df["topic_id"].notna()
        ]["topic_id"].nunique()
        / max(available_topic_count, 1),
    )
    if not test_history_df.empty
    else 0.0
)
adaptive_completion_live = (
    min(
        1.0,
        test_history_df[
            (test_history_df["test_type"] == "adaptive") & test_history_df["subject_id"].notna()
        ]["subject_id"].nunique()
        / max(available_subject_count, 1),
    )
    if not test_history_df.empty
    else 0.0
)

accuracy_raw = (
    len(correct_attempts_df) / max(len(answered_attempts_df), 1)
    if not answered_attempts_df.empty
    else 0.0
)
accuracy_norm = max(0.0, min(1.0, (accuracy_raw - 0.50) / 0.35))
elo_norm = max(0.0, min(1.0, (current_elo - 1600) / 1200))

subject_accuracy_values = (
    (subject_progress_df["accuracy_pct"].dropna() / 100).tolist()
    if not subject_progress_df.empty
    else []
)
if subject_accuracy_values:
    subject_mean = float(np.mean(subject_accuracy_values))
    subject_std = float(np.std(subject_accuracy_values))
    consistency_raw = 1 - subject_std / max(subject_mean + 0.01, 0.01)
    consistency_norm = max(0.0, min(1.0, consistency_raw))
else:
    subject_mean = np.nan
    subject_std = np.nan
    consistency_raw = np.nan
    consistency_norm = 0.0

if not answered_attempts_df.empty and "completed_at" in answered_attempts_df.columns:
    latest_answered_at = answered_attempts_df["completed_at"].max()
    recent_cutoff = latest_answered_at - pd.Timedelta(days=14)
    recent_df = answered_attempts_df[answered_attempts_df["completed_at"] >= recent_cutoff]
    prior_df = answered_attempts_df[answered_attempts_df["completed_at"] < recent_cutoff]
    recent_accuracy = len(recent_df[recent_df["correct"] == True]) / max(len(recent_df), 1) if len(recent_df) > 0 else accuracy_raw
    prior_accuracy = len(prior_df[prior_df["correct"] == True]) / max(len(prior_df), 1) if len(prior_df) > 0 else accuracy_raw
    improvement_delta = recent_accuracy - prior_accuracy
else:
    recent_accuracy = accuracy_raw
    prior_accuracy = accuracy_raw
    improvement_delta = 0.0

improvement_raw = min(0.15, improvement_delta) if improvement_delta > 0 else max(-0.15, improvement_delta)
improvement_norm = max(0.0, min(1.0, (improvement_raw + 0.15) / 0.30))

score_basis = (
    REPORT_SCORE_WEIGHTS["accuracy"] * accuracy_norm
    + REPORT_SCORE_WEIGHTS["elo"] * elo_norm
    + REPORT_SCORE_WEIGHTS["consistency"] * consistency_norm
    + REPORT_SCORE_WEIGHTS["improvement"] * improvement_norm
)
expected_score_report = 40 + 50 * score_basis
minimum_score_report = expected_score_report - 10 * (1 - score_basis)
maximum_score_report = expected_score_report + 10 * score_basis
completion_rate_all = (
    answered_attempts_df["question_id"].nunique() / max(len(question_bank_full), 1)
    if not answered_attempts_df.empty
    else 0.0
)
confidence_report = max(0.50, min(1.00, 0.50 + 0.40 * score_basis + 0.10 * completion_rate_all))

predictor_unlocked_report = (
    current_elo >= PREDICTOR_UNLOCK_ELO_REPORT
    and full_mock_completion_live >= PREDICTOR_UNLOCK_COMPLETION_REPORT
    and topic_wise_completion_live >= PREDICTOR_UNLOCK_COMPLETION_REPORT
    and adaptive_completion_live >= PREDICTOR_UNLOCK_COMPLETION_REPORT
)
predictor_unlocked_ui = (
    current_elo >= PREDICTOR_UNLOCK_ELO_REPORT
    and full_mock_completion_live >= PREDICTOR_UNLOCK_COMPLETION_UI
    and topic_wise_completion_live >= PREDICTOR_UNLOCK_COMPLETION_UI
    and adaptive_completion_live >= PREDICTOR_UNLOCK_COMPLETION_UI
)

threshold_summary_df = pd.DataFrame(
    [
        {"threshold_area": "weak_topic_report", "value": "60%", "notes": "Topic accuracy below 60% is treated as weak in the report."},
        {"threshold_area": "rapid_guess_alpha_0", "value": "10s", "notes": "Baseline minimum solve time."},
        {"threshold_area": "rapid_guess_alpha_1", "value": "0.02", "notes": "Seconds per question-stem character."},
        {"threshold_area": "rapid_guess_alpha_2", "value": "0.01", "notes": "Seconds per option-set character."},
        {"threshold_area": "rapid_guess_alpha_3", "value": "30s", "notes": "Extra time for high-complexity questions."},
        {"threshold_area": "remediation_steps_report", "value": REMEDIATION_STEPS_REPORT, "notes": "Report remediation step threshold."},
        {"threshold_area": "remediation_accuracy_report", "value": REMEDIATION_ACCURACY_REPORT, "notes": "Report remediation accuracy threshold."},
        {"threshold_area": "predictor_unlock_report_completion", "value": "70%", "notes": "Report unlock requirement for full-mock/topic-wise/adaptive coverage."},
        {"threshold_area": "predictor_unlock_ui_completion", "value": "100%", "notes": "Current UI component threshold in GateScorePrediction.tsx."},
        {"threshold_area": "predictor_unlock_elo", "value": PREDICTOR_UNLOCK_ELO_REPORT, "notes": "Report and UI both use 2500 ELO for unlock."},
    ]
)

score_formula_df = pd.DataFrame(
    [
        {"component": "accuracy_raw", "value": round(accuracy_raw, 4)},
        {"component": "accuracy_norm", "value": round(accuracy_norm, 4)},
        {"component": "elo_norm", "value": round(elo_norm, 4)},
        {"component": "consistency_raw", "value": round(consistency_raw, 4) if pd.notna(consistency_raw) else np.nan},
        {"component": "consistency_norm", "value": round(consistency_norm, 4)},
        {"component": "recent_accuracy", "value": round(recent_accuracy, 4)},
        {"component": "prior_accuracy", "value": round(prior_accuracy, 4)},
        {"component": "improvement_delta", "value": round(improvement_delta, 4)},
        {"component": "improvement_norm", "value": round(improvement_norm, 4)},
        {"component": "score_basis", "value": round(score_basis, 4)},
        {"component": "expected_score_report", "value": round(expected_score_report, 2)},
        {"component": "minimum_score_report", "value": round(minimum_score_report, 2)},
        {"component": "maximum_score_report", "value": round(maximum_score_report, 2)},
        {"component": "confidence_report", "value": round(confidence_report, 4)},
        {"component": "completion_rate_all", "value": round(completion_rate_all, 4)},
        {"component": "full_mock_completion_live", "value": round(full_mock_completion_live, 4)},
        {"component": "topic_wise_completion_live", "value": round(topic_wise_completion_live, 4)},
        {"component": "adaptive_completion_live", "value": round(adaptive_completion_live, 4)},
        {"component": "predictor_unlocked_report", "value": predictor_unlocked_report},
        {"component": "predictor_unlocked_ui", "value": predictor_unlocked_ui},
    ]
)

rapid_guess_rows_df = (
    question_attempts_df[question_attempts_df["rapid_guess_warning"].fillna(False) == True]
    .sort_values(["completed_at", "step_number"])
    .reset_index(drop=True)
    if not question_attempts_df.empty
    else pd.DataFrame()
)

display(account_summary_df)
display(test_summary_df)
display(question_outcome_summary_df)
display(subject_progress_df.head(20))
display(topic_progress_df.head(20))
display(weak_topics_report_df.head(20))
display(activity_summary_df.head(20))
display(threshold_summary_df)
display(score_formula_df)
if not rapid_guess_rows_df.empty:
    display(
        rapid_guess_rows_df[
            [
                "completed_at",
                "test_id",
                "step_number",
                "question_id",
                "question_text",
                "time_spent_seconds",
                "rapid_guess_threshold_seconds",
                "warning_text",
            ]
        ].head(20)
    )

,student_user_id,profile_row_id,full_name,email,role,elo_rating,streak_count,study_goal,theme,last_active,created_at,updated_at
0,12efa469-0330-42e1-bc64-82bed3402ae8,c047e80e-28aa-44bd-b4ae-0e2f376c14a6,Sunil,sonunaik1236k@gmail.com,student,1500,0,crack_gate,system,2026-04-08 21:54:59.023003+00:00,2026-04-08 21:54:59.023003+00:00,2026-04-08 21:54:59.023003+00:00

,test_type,tests_completed,total_questions,questions_attempted,correct_answers,mean_accuracy_pct,mean_score_pct,total_duration_seconds
4,topic-wise,38,374,227,86,23.815789,17.084818,1373.0
0,adaptive,31,399,262,95,19.248690,6.790876,1616.0
3,full-mock,5,322,116,77,23.692308,21.876612,907.0
2,assignment-test,2,12,12,7,75.000000,74.423077,77.0
1,assignment-homework,2,25,25,7,26.666667,2.732517,80.0

                             metric  value
0                   tests_completed  78.00
1            unique_tests_completed  78.00
2                questions_answered  92.00
3                   correct_answers  36.00
4                     wrong_answers  56.00
5        unique_questions_attempted  71.00
6  coverage_percent_of_full_dataset   7.11
7                 rapid_guess_flags  36.00

,subjectId,subjectName,totalAnswers,correctAnswers,accuracy_pct
0,calculus-optimization,Calculus & Optimization,44,14,31.818182
1,dbms,Database Management Systems,5,3,60.0
2,general-aptitude,General Aptitude,13,3,23.076923
3,linear-algebra,Linear Algebra,18,12,66.666667
4,probability-statistics,Probability & Statistics,12,4,33.333333

,id,user_id,subjectId,topicId,correctAnswers,totalAnswers,last_practiced,accuracy_pct,subjectName,topicName
0,7e838c26-6755-405a-9b99-9b4e338714dc,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ai-logic,0,4,2026-04-30 22:09:16.295000+00:00,0.000000,Artificial Intelligence,Propositional & Predicate Logic
1,133b7b53-3661-4331-bc8a-a3658e42b818,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ai-search,3,8,2026-04-30 22:09:16.295000+00:00,37.500000,Artificial Intelligence,Search Algorithms
2,aa15f3fa-23d7-443a-b358-3d98511ab983,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ml-logic,0,1,2026-04-27 06:38:05.365000+00:00,0.000000,Artificial Intelligence,ml-logic
3,9d974a40-ea2d-45db-a33a-85476d186417,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-differentiation,4,16,2026-05-01 12:08:49.218000+00:00,25.000000,Calculus & Optimization,Differentiation
4,47b705d0-070e-45c0-94cc-f5aba25352fa,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-integration,3,18,2026-05-13 05:11:08.970000+00:00,16.666667,Calculus & Optimization,Integration
5,38188ab7-769f-48e2-8b3a-80b3d3840010,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-optimization,3,9,2026-05-13 05:11:08.971000+00:00,33.333333,Calculus & Optimization,Optimization
6,e2c28bfd-6adf-43ff-a631-9c9560a22d90,12efa469-0330-42e1-bc64-82bed3402ae8,dbms,data-warehousing-olap,1,1,2026-04-27 06:38:05.365000+00:00,100.000000,Database Management Systems,data-warehousing-olap
7,de53bfad-8d08-4c0a-8127-13508682f0d1,12efa469-0330-42e1-bc64-82bed3402ae8,dbms,dbms-normalization,4,5,2026-05-07 18:46:50.346000+00:00,80.000000,Database Management Systems,Normalization
8,938a564b-0556-4c22-bc8a-81769946300a,12efa469-0330-42e1-bc64-82bed3402ae8,dbms,dbms-sql,1,2,2026-04-30 22:09:16.297000+00:00,50.000000,Database Management Systems,SQL & Relational Algebra
9,a7c9f5b0-2894-4ad3-92ec-f3bf9baadb54,12efa469-0330-42e1-bc64-82bed3402ae8,general-aptitude,ga-logical-reasoning,1,4,2026-05-01 12:08:49.220000+00:00,25.000000,General Aptitude,Logical Reasoning
10,090a01a9-4bb4-44a8-89be-fa5efba0965d,12efa469-0330-42e1-bc64-82bed3402ae8,general-aptitude,ga-quantitative-aptitude,1,2,2026-05-01 12:08:49.220000+00:00,50.000000,General Aptitude,Quantitative Aptitude
11,6122ba3c-ea09-43ad-ac3c-6caf9c67666b,12efa469-0330-42e1-bc64-82bed3402ae8,general-aptitude,ga-verbal-reasoning,3,4,2026-05-01 12:08:49.220000+00:00,75.000000,General Aptitude,Verbal Reasoning
12,ab4c4235-7f93-4588-8399-cf7055aaf381,12efa469-0330-42e1-bc64-82bed3402ae8,linear-algebra,la-eigenvalues,4,12,2026-05-01 12:08:49.220000+00:00,33.333333,Linear Algebra,Eigenvalues & Eigenvectors
13,7ef4b9a6-4aeb-4023-95d6-43af220a59d5,12efa469-0330-42e1-bc64-82bed3402ae8,linear-algebra,la-matrices,6,8,2026-05-01 12:08:49.220000+00:00,75.000000,Linear Algebra,Matrices & Determinants
14,df3887f8-1b82-44eb-b2e3-a7467f89eddc,12efa469-0330-42e1-bc64-82bed3402ae8,linear-algebra,la-vector-spaces,2,2,2026-05-01 12:08:49.219000+00:00,100.000000,Linear Algebra,Vector Spaces
15,e3d69aa0-2860-46aa-8f53-20ad9658a425,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-evaluation,1,2,2026-04-23 16:31:52.704000+00:00,50.000000,Machine Learning,Model Evaluation
16,18cb8d97-dbfb-4d8a-b8ed-b78a263578f0,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-supervised,3,9,2026-04-30 22:09:16.297000+00:00,33.333333,Machine Learning,Supervised Learning
17,19c370c0-8db8-4caf-9073-b821c57c9e65,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-unsupervised,0,2,2026-04-27 06:38:05.364000+00:00,0.000000,Machine Learning,Unsupervised Learning
18,1a268d07-14bf-43db-b891-f2de22e06b2f,12efa469-0330-42e1-bc64-82bed3402ae8,probability-statistics,ps-distributions,1,6,2026-05-01 12:08:49.219000+00:00,16.666667,Probability & Statistics,Probability Distributions
19,973a954b-b599-46ed-a2af-df6274e16b73,12efa469-0330-42e1-bc64-82bed3402ae8,probability-statistics,ps-hypothesis,1,5,2026-05-01 12:08:49.219000+00:00,20.000000,Probability & Statistics,Hypothesis Testing

,id,user_id,subjectId,topicId,correctAnswers,totalAnswers,last_practiced,accuracy_pct,subjectName,topicName
0,7e838c26-6755-405a-9b99-9b4e338714dc,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ai-logic,0,4,2026-04-30 22:09:16.295000+00:00,0.000000,Artificial Intelligence,Propositional & Predicate Logic
1,19c370c0-8db8-4caf-9073-b821c57c9e65,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-unsupervised,0,2,2026-04-27 06:38:05.364000+00:00,0.000000,Machine Learning,Unsupervised Learning
2,aa15f3fa-23d7-443a-b358-3d98511ab983,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ml-logic,0,1,2026-04-27 06:38:05.365000+00:00,0.000000,Artificial Intelligence,ml-logic
3,47b705d0-070e-45c0-94cc-f5aba25352fa,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-integration,3,18,2026-05-13 05:11:08.970000+00:00,16.666667,Calculus & Optimization,Integration
4,1a268d07-14bf-43db-b891-f2de22e06b2f,12efa469-0330-42e1-bc64-82bed3402ae8,probability-statistics,ps-distributions,1,6,2026-05-01 12:08:49.219000+00:00,16.666667,Probability & Statistics,Probability Distributions
5,973a954b-b599-46ed-a2af-df6274e16b73,12efa469-0330-42e1-bc64-82bed3402ae8,probability-statistics,ps-hypothesis,1,5,2026-05-01 12:08:49.219000+00:00,20.000000,Probability & Statistics,Hypothesis Testing
6,a2bce0fe-5754-47e8-869c-3c6fc7e77d71,12efa469-0330-42e1-bc64-82bed3402ae8,programming-dsa,dsa-trees,2,9,2026-04-30 22:09:16.297000+00:00,22.222222,Programming & DSA,Trees & Graphs
7,5bb5105c-ea1e-4281-a6d6-9ad484208742,12efa469-0330-42e1-bc64-82bed3402ae8,probability-statistics,ps-probability,3,13,2026-05-01 12:08:49.219000+00:00,23.076923,Probability & Statistics,Probability Basics
8,9d974a40-ea2d-45db-a33a-85476d186417,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-differentiation,4,16,2026-05-01 12:08:49.218000+00:00,25.000000,Calculus & Optimization,Differentiation
9,a7c9f5b0-2894-4ad3-92ec-f3bf9baadb54,12efa469-0330-42e1-bc64-82bed3402ae8,general-aptitude,ga-logical-reasoning,1,4,2026-05-01 12:08:49.220000+00:00,25.000000,General Aptitude,Logical Reasoning
10,ab4c4235-7f93-4588-8399-cf7055aaf381,12efa469-0330-42e1-bc64-82bed3402ae8,linear-algebra,la-eigenvalues,4,12,2026-05-01 12:08:49.220000+00:00,33.333333,Linear Algebra,Eigenvalues & Eigenvectors
11,38188ab7-769f-48e2-8b3a-80b3d3840010,12efa469-0330-42e1-bc64-82bed3402ae8,calculus-optimization,co-optimization,3,9,2026-05-13 05:11:08.971000+00:00,33.333333,Calculus & Optimization,Optimization
12,18cb8d97-dbfb-4d8a-b8ed-b78a263578f0,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-supervised,3,9,2026-04-30 22:09:16.297000+00:00,33.333333,Machine Learning,Supervised Learning
13,133b7b53-3661-4331-bc8a-a3658e42b818,12efa469-0330-42e1-bc64-82bed3402ae8,artificial-intelligence,ai-search,3,8,2026-04-30 22:09:16.295000+00:00,37.500000,Artificial Intelligence,Search Algorithms
14,2d67efd8-1155-430d-8824-3c68d182b68a,12efa469-0330-42e1-bc64-82bed3402ae8,programming-dsa,dsa-complexity,6,14,2026-04-30 22:09:16.297000+00:00,42.857143,Programming & DSA,Complexity Analysis
15,9078bf1d-a933-4179-9e07-0e91e5ae07d4,12efa469-0330-42e1-bc64-82bed3402ae8,programming-dsa,dsa-arrays,2,4,2026-04-30 22:09:16.296000+00:00,50.000000,Programming & DSA,Arrays & Strings
16,938a564b-0556-4c22-bc8a-81769946300a,12efa469-0330-42e1-bc64-82bed3402ae8,dbms,dbms-sql,1,2,2026-04-30 22:09:16.297000+00:00,50.000000,Database Management Systems,SQL & Relational Algebra
17,090a01a9-4bb4-44a8-89be-fa5efba0965d,12efa469-0330-42e1-bc64-82bed3402ae8,general-aptitude,ga-quantitative-aptitude,1,2,2026-05-01 12:08:49.220000+00:00,50.000000,General Aptitude,Quantitative Aptitude
18,e3d69aa0-2860-46aa-8f53-20ad9658a425,12efa469-0330-42e1-bc64-82bed3402ae8,machine-learning,ml-evaluation,1,2,2026-04-23 16:31:52.704000+00:00,50.000000,Machine Learning,Model Evaluation

                  event_type  count
2        graph_path_progress    186
3          question_answered     92
5             test_completed      4
0    adaptive_test_completed      3
1       graph_path_completed      3
4          student_signed_in      1
6  topic-wise_test_completed      1

,threshold_area,value,notes
0,weak_topic_report,60%,Topic accuracy below 60% is treated as weak in...
1,rapid_guess_alpha_0,10s,Baseline minimum solve time.
2,rapid_guess_alpha_1,0.02,Seconds per question-stem character.
3,rapid_guess_alpha_2,0.01,Seconds per option-set character.
4,rapid_guess_alpha_3,30s,Extra time for high-complexity questions.
5,remediation_steps_report,3,Report remediation step threshold.
6,remediation_accuracy_report,0.75,Report remediation accuracy threshold.
7,predictor_unlock_report_completion,70%,Report unlock requirement for full-mock/topic-...
8,predictor_unlock_ui_completion,100%,Current UI component threshold in GateScorePre...
9,predictor_unlock_elo,2500,Report and UI both use 2500 ELO for unlock.

                     component   value
0                 accuracy_raw  0.3913
1                accuracy_norm     0.0
2                     elo_norm     0.0
3              consistency_raw  0.6109
4             consistency_norm  0.6109
5              recent_accuracy  0.3913
6               prior_accuracy  0.3913
7            improvement_delta     0.0
8             improvement_norm     0.5
9                  score_basis  0.1722
10       expected_score_report   48.61
11        minimum_score_report   40.33
12        maximum_score_report   50.33
13           confidence_report   0.576
14         completion_rate_all  0.0711
15   full_mock_completion_live     0.5
16  topic_wise_completion_live  0.3636
17    adaptive_completion_live   0.875
18   predictor_unlocked_report   False
19       predictor_unlocked_ui   False

,completed_at,test_id,step_number,question_id,question_text,time_spent_seconds,rapid_guess_threshold_seconds,warning_text
0,2026-05-01 11:13:36.384000+00:00,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,6,co-34,If ∫ f(x)dx = F(x) then F'(x)=?,1,26.0,Solved in 1s against an estimated minimum of 2...
1,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,9,co-5,"If f(x,y)=x^2+y^2, then grad f at (1,2) is:",4,26.0,Solved in 4s against an estimated minimum of 2...
2,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,10,co-2,"Let f(x, y) = x²y + xy². What is ∂²f / ∂x∂y?",1,41.0,Solved in 1s against an estimated minimum of 4...
3,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,11,co-14,Chain rule states?,7,26.0,Solved in 7s against an estimated minimum of 2...
4,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,12,co-24,If f is differentiable then it is?,1,26.0,Solved in 1s against an estimated minimum of 2...
5,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,15,co-58,Lagrange multiplier is used for?,1,26.0,Solved in 1s against an estimated minimum of 2...
6,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,17,co-61,If function is convex then any local minimum is?,1,26.0,Solved in 1s against an estimated minimum of 2...
7,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,19,co-46,Triple integral represents?,1,26.0,Solved in 1s against an estimated minimum of 2...
8,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,23,mock4-q23,Kurtosis measures:,1,27.0,Solved in 1s against an estimated minimum of 2...
9,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,27,ps-37,Mean of Exponential distribution is?,2,26.0,Solved in 2s against an estimated minimum of 2...
10,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,28,ps-6,"For Binomial(n, p), variance is:",4,41.0,Solved in 4s against an estimated minimum of 4...
11,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,34,mock4-q30,A 95% confidence interval means:,1,43.0,Solved in 1s against an estimated minimum of 4...
12,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,36,mock4-q32,The null space (kernel) of a matrix A consists...,2,27.0,Solved in 2s against an estimated minimum of 2...
13,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,38,la-16,Let A be an n×n matrix. A new matrix B is form...,16,44.0,Solved in 16s against an estimated minimum of ...
14,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,40,la-24,A matrix is said to have full rank when its ra...,1,44.0,Solved in 1s against an estimated minimum of 4...
15,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,41,la-22,Let A be a non-singular square matrix. Using a...,3,43.0,Solved in 3s against an estimated minimum of 4...
16,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,42,la-31,"For a square matrix A, eigenvalues are obtaine...",1,43.0,Solved in 1s against an estimated minimum of 4...
17,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,43,la-32,"Let A be an n×n matrix with eigenvalues λ₁, λ₂...",2,43.0,Solved in 2s against an estimated minimum of 4...
18,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,44,la-7,"Let v₁ = (1, 0, 1), v₂ = (0, 1, 1), v₃ = (1, 1...",5,43.0,Solved in 5s against an estimated minimum of 4...
19,2026-05-01 12:08:49.217000+00:00,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,45,la-33,Consider a square matrix A with eigenvalues λ₁...,5,43.0,Solved in 5s against an estimated minimum of 4...

In [8]:
# ============================================================
# 4. LIVE ADAPTIVE ENGINE REPLAY HELPERS
# ============================================================


GRAPH_NEIGHBOR_WEIGHT = 34
GRAPH_FALLBACK_WEIGHT = 14

RAPID_GUESS_ALPHA_0 = 10
RAPID_GUESS_ALPHA_1 = 0.02
RAPID_GUESS_ALPHA_2 = 0.01
RAPID_GUESS_ALPHA_3 = 30
RAPID_GUESS_MAX_PENALTY = 20
MULTI_STEP_PATTERN = re.compile(
    r"\b(select all that apply|which of the following statements|using the following|based on the following)\b",
    re.IGNORECASE,
)
COMPUTATION_PATTERN = re.compile(
    r"\b(calculate|compute|determine|evaluate|solve|derive|trace|determinant|eigenvalue|probability|expected value|variance|standard deviation|time complexity|space complexity)\b",
    re.IGNORECASE,
)


def clamp(value, minimum, maximum):
    return max(minimum, min(maximum, value))


def round_num(value, decimals=4):
    return float(np.round(value, decimals))


def get_topic_label(topic_id: str | None) -> str:
    if not topic_id:
        return "general"
    topic_name = None
    for (subject_id, lookup_topic_id), topic in topic_lookup.items():
        if lookup_topic_id == topic_id:
            topic_name = topic.get("name")
            break
    return topic_name or str(topic_id).replace("-", " ")


def choose_anchor_question(question_records):
    if not question_records:
        return None
    average_elo = np.mean([item.get("eloRating", 1400) for item in question_records])

    def anchor_score(item):
        if item.get("difficulty") == "medium":
            penalty = 0
        elif item.get("difficulty") == "easy":
            penalty = 20
        else:
            penalty = 30
        return abs(item.get("eloRating", 1400) - average_elo) + penalty, item.get("id")

    return sorted(question_records, key=anchor_score)[0]


def get_transition_weight(from_question, to_question):
    if from_question.get("id") == to_question.get("id"):
        return 0.0
    if from_question.get("subjectId") != to_question.get("subjectId"):
        return 0.0

    same_topic = from_question.get("topicId") == to_question.get("topicId")
    difficulty_gap = DIFF_ORDER.get(to_question.get("difficulty"), 1) - DIFF_ORDER.get(from_question.get("difficulty"), 1)
    elo_delta = float(to_question.get("eloRating", 1400)) - float(from_question.get("eloRating", 1400))
    elo_closeness = 1 - clamp(abs(elo_delta) / 320, 0, 1)
    progression_fit = 1 - clamp(abs(elo_delta - 35) / 320, 0, 1)
    if difficulty_gap == 0:
        difficulty_fit = 0.92
    elif difficulty_gap == 1:
        difficulty_fit = 1.0
    elif difficulty_gap == -1:
        difficulty_fit = 0.72
    else:
        difficulty_fit = 0.35
    type_fit = 1.0 if from_question.get("type") == to_question.get("type") else 0.68
    mark_fit = 1.0 if from_question.get("marks") == to_question.get("marks") else 0.8

    return round_num(
        clamp(
            (0.46 if same_topic else 0.16)
            + elo_closeness * 0.20
            + progression_fit * 0.12
            + difficulty_fit * 0.10
            + type_fit * 0.07
            + mark_fit * 0.05,
            0.05,
            0.99,
        )
    )


def create_graph_edge(source_id, target_id, weight, kind, same_topic):
    return {
        "sourceId": source_id,
        "targetId": target_id,
        "weight": round_num(weight),
        "kind": kind,
        "sameTopic": same_topic,
    }


def upsert_graph_edge(edge_buckets, edge):
    source_bucket = edge_buckets[edge["sourceId"]]
    existing = source_bucket.get(edge["targetId"])
    if (
        existing is None
        or edge["weight"] > existing["weight"]
        or (
            edge["weight"] == existing["weight"]
            and edge["kind"] == "same-topic"
            and existing["kind"] != "same-topic"
        )
    ):
        source_bucket[edge["targetId"]] = edge


def build_question_recommendation_graph(question_records):
    edge_buckets = defaultdict(dict)
    question_by_id = {item["id"]: item for item in question_records}
    subject_map = defaultdict(list)
    for question in question_records:
        subject_map[question.get("subjectId")].append(question)

    sorted_subject_ids = sorted(subject_map.keys(), key=lambda value: str(value))
    subject_anchors = []

    for subject_id in sorted_subject_ids:
        subject_questions = subject_map.get(subject_id, [])
        topic_map = defaultdict(list)
        for question in subject_questions:
            topic_map[question.get("topicId")].append(question)

        topic_anchors = []
        for topic_id, topic_questions in sorted(topic_map.items(), key=lambda item: str(item[0])):
            anchor_question = choose_anchor_question(topic_questions)
            if anchor_question:
                topic_anchors.append({"topicId": topic_id, "question": anchor_question})

        subject_anchor = choose_anchor_question(subject_questions)
        if subject_anchor:
            subject_anchors.append({"subjectId": subject_id, "questionId": subject_anchor["id"]})

        for topic_anchor in topic_anchors:
            anchor_question = topic_anchor["question"]
            if not subject_anchor or subject_anchor["id"] == anchor_question["id"]:
                continue
            bridge_weight = round_num((get_transition_weight(subject_anchor, anchor_question) + 0.22) / 2)
            upsert_graph_edge(
                edge_buckets,
                create_graph_edge(subject_anchor["id"], anchor_question["id"], bridge_weight, "subject-flow", False),
            )
            upsert_graph_edge(
                edge_buckets,
                create_graph_edge(anchor_question["id"], subject_anchor["id"], bridge_weight, "subject-flow", False),
            )

        for index in range(1, len(topic_anchors)):
            previous_anchor = topic_anchors[index - 1]["question"]
            next_anchor = topic_anchors[index]["question"]
            bridge_weight = round_num((get_transition_weight(previous_anchor, next_anchor) + 0.18) / 2)
            upsert_graph_edge(
                edge_buckets,
                create_graph_edge(previous_anchor["id"], next_anchor["id"], bridge_weight, "subject-flow", False),
            )
            upsert_graph_edge(
                edge_buckets,
                create_graph_edge(next_anchor["id"], previous_anchor["id"], bridge_weight, "subject-flow", False),
            )

        topic_anchor_by_id = {item["topicId"]: item["question"] for item in topic_anchors}

        for question in subject_questions:
            same_topic_candidates = []
            cross_topic_candidates = []
            for candidate in subject_questions:
                if candidate["id"] == question["id"]:
                    continue
                weight = get_transition_weight(question, candidate)
                bucket = same_topic_candidates if candidate.get("topicId") == question.get("topicId") else cross_topic_candidates
                bucket.append({"candidate": candidate, "weight": weight})

            same_topic_candidates = sorted(same_topic_candidates, key=lambda item: item["weight"], reverse=True)[:4]
            cross_topic_candidates = sorted(cross_topic_candidates, key=lambda item: item["weight"], reverse=True)[:2]

            for item in same_topic_candidates:
                upsert_graph_edge(
                    edge_buckets,
                    create_graph_edge(question["id"], item["candidate"]["id"], item["weight"], "same-topic", True),
                )
            for item in cross_topic_candidates:
                upsert_graph_edge(
                    edge_buckets,
                    create_graph_edge(question["id"], item["candidate"]["id"], item["weight"], "subject-flow", False),
                )

            topic_anchor = topic_anchor_by_id.get(question.get("topicId"))
            if topic_anchor and topic_anchor["id"] != question["id"]:
                upsert_graph_edge(
                    edge_buckets,
                    create_graph_edge(question["id"], topic_anchor["id"], 0.50, "same-topic", True),
                )

            if subject_anchor and subject_anchor["id"] != question["id"]:
                upsert_graph_edge(
                    edge_buckets,
                    create_graph_edge(question["id"], subject_anchor["id"], 0.34, "subject-flow", False),
                )

    for index in range(1, len(subject_anchors)):
        previous_question = question_by_id.get(subject_anchors[index - 1]["questionId"])
        next_question = question_by_id.get(subject_anchors[index]["questionId"])
        if not previous_question or not next_question:
            continue
        upsert_graph_edge(
            edge_buckets,
            create_graph_edge(previous_question["id"], next_question["id"], 0.24, "subject-bridge", False),
        )
        upsert_graph_edge(
            edge_buckets,
            create_graph_edge(next_question["id"], previous_question["id"], 0.24, "subject-bridge", False),
        )

    edges_by_source = {}
    edges = []
    for source_id, bucket in edge_buckets.items():
        sorted_edges = sorted(bucket.values(), key=lambda item: item["weight"], reverse=True)
        edges_by_source[source_id] = sorted_edges
        edges.extend(sorted_edges)

    return {
        "nodes": [
            {
                "id": question["id"],
                "questionId": question["id"],
                "subjectId": question.get("subjectId"),
                "topicId": question.get("topicId"),
                "difficulty": question.get("difficulty", "medium"),
                "eloRating": question.get("eloRating", 1400),
                "type": question.get("type", "mcq"),
            }
            for question in question_records
        ],
        "edges": edges,
        "edgesBySource": edges_by_source,
    }


def get_recent_reward_signal(session_attempts):
    recent_attempts = session_attempts[-4:]
    if not recent_attempts:
        return 0.0

    total = 0.0
    for attempt in recent_attempts:
        reward = 1.05 if attempt.get("correct") else -1.0
        if attempt.get("correct") and attempt.get("difficulty") == "hard":
            reward += 0.28
        if (not attempt.get("correct")) and attempt.get("difficulty") == "easy":
            reward -= 0.20
        if attempt.get("remediationForQuestionId") and attempt.get("correct"):
            reward += 0.18
        if attempt.get("rapidGuessWarning"):
            reward -= 0.42
        total += reward
    return round_num(total)


def get_momentum(session_attempts):
    last_three = session_attempts[-3:]
    last_two = session_attempts[-2:]
    reward_signal = get_recent_reward_signal(session_attempts)

    if len(last_three) == 3 and all(item.get("correct") for item in last_three) and reward_signal >= 1.4:
        return "hot"
    if (len(last_two) == 2 and all(not item.get("correct") for item in last_two)) or reward_signal <= -1.35:
        return "cold"
    return "steady"


def get_target_elo(student_elo, attempts, momentum):
    last_attempt = attempts[-1] if attempts else None
    target_elo = float(student_elo)
    reward_signal = get_recent_reward_signal(attempts)
    if momentum == "hot":
        target_elo += 75
    if momentum == "cold":
        target_elo -= 90
    if last_attempt:
        target_elo += 35 if last_attempt.get("correct") else -60
    target_elo += reward_signal * 24
    return int(clamp(round(target_elo), 1100, 1800))


def get_target_difficulty(target_elo):
    if target_elo < 1300:
        return "easy"
    if target_elo < 1500:
        return "medium"
    return "hard"


def get_topic_stats(session_attempts):
    stats = defaultdict(lambda: {"correct": 0, "total": 0})
    for attempt in session_attempts:
        current = stats[attempt.get("topicId")]
        current["correct"] += 1 if attempt.get("correct") else 0
        current["total"] += 1
    return stats


def get_recent_topic_count(session_attempts, topic_id):
    return sum(1 for attempt in session_attempts[-3:] if attempt.get("topicId") == topic_id)


def get_focus_topic_id(session_attempts):
    topic_stats = get_topic_stats(session_attempts)
    focus_topic_id = session_attempts[-1].get("topicId") if session_attempts else "general"
    lowest_accuracy = float("inf")
    for topic_id, stats in topic_stats.items():
        accuracy = stats["correct"] / max(stats["total"], 1)
        if accuracy < lowest_accuracy:
            lowest_accuracy = accuracy
            focus_topic_id = topic_id
    return focus_topic_id or "general"


def get_adaptive_policy_state(session_attempts):
    return {
        "momentum": get_momentum(session_attempts),
        "focusTopicId": get_focus_topic_id(session_attempts),
    }


def get_question_graph_neighbors_within_hops(source_question_id, available_by_id, max_hops, graph):
    visited = {source_question_id}
    queue = deque([{"questionId": source_question_id, "hopDistance": 0}])
    best_by_question_id = {}

    while queue:
        current = queue.popleft()
        if current["hopDistance"] >= max_hops:
            continue

        for edge in graph["edgesBySource"].get(current["questionId"], []):
            next_hop_distance = current["hopDistance"] + 1
            candidate_question = available_by_id.get(edge["targetId"])
            if candidate_question is not None:
                existing = best_by_question_id.get(edge["targetId"])
                if (
                    existing is None
                    or next_hop_distance < existing["hopDistance"]
                    or (
                        next_hop_distance == existing["hopDistance"]
                        and edge["weight"] > (existing["edge"]["weight"] if existing["edge"] else 0)
                    )
                ):
                    best_by_question_id[edge["targetId"]] = {
                        "question": candidate_question,
                        "edge": edge,
                        "hopDistance": next_hop_distance,
                    }

            if edge["targetId"] not in visited and next_hop_distance < max_hops:
                visited.add(edge["targetId"])
                queue.append({"questionId": edge["targetId"], "hopDistance": next_hop_distance})

    return sorted(
        best_by_question_id.values(),
        key=lambda item: (item["hopDistance"], -(item["edge"]["weight"] if item["edge"] else 0)),
    )


def get_remediation_target(session_attempts):
    unresolved_question_id = None
    for attempt in session_attempts:
        if attempt.get("correct"):
            if attempt.get("questionId") == unresolved_question_id:
                unresolved_question_id = None
            continue
        unresolved_question_id = attempt.get("questionId")
    if not unresolved_question_id:
        return None
    for attempt in reversed(session_attempts):
        if attempt.get("questionId") == unresolved_question_id:
            return attempt
    return None


def get_remediation_progress(session_attempts, target_question_id):
    attempts = [item for item in session_attempts if item.get("remediationForQuestionId") == target_question_id]
    return {
        "attempts": attempts,
        "stepsCompleted": len(attempts),
        "accuracy": sum(1 for item in attempts if item.get("correct")) / max(len(attempts), 1) if attempts else 0.0,
        "rapidGuessHits": sum(1 for item in attempts if item.get("rapidGuessWarning")),
    }


def get_preferred_neighbor_hop(momentum, reward_signal, last_attempt_correct, hop_limit):
    if not last_attempt_correct:
        return 1
    if momentum == "hot" and reward_signal >= 2.25:
        return min(3, hop_limit)
    if momentum == "hot" or reward_signal >= 0.9:
        return min(2, hop_limit)
    return 1


def get_question_graph_edge(source_question_id, target_question_id, graph):
    return next(
        (edge for edge in graph["edgesBySource"].get(source_question_id, []) if edge["targetId"] == target_question_id),
        None,
    )


def score_candidate(
    candidate,
    target_elo,
    target_difficulty,
    session_attempts,
    topic_stats,
    remediation_target_question_id=None,
    reward_signal=0.0,
):
    last_attempt = session_attempts[-1] if session_attempts else None
    elo_distance = abs(float(candidate.get("eloRating", 1400)) - float(target_elo))
    score = 120 - elo_distance / 12

    difficulty_gap = abs(
        DIFF_ORDER.get(candidate.get("difficulty"), 1) - DIFF_ORDER.get(target_difficulty, 1)
    )
    score += 14 if difficulty_gap == 0 else 4 if difficulty_gap == 1 else -10

    candidate_topic_stats = topic_stats.get(candidate.get("topicId"))
    if candidate_topic_stats:
        accuracy = candidate_topic_stats["correct"] / max(candidate_topic_stats["total"], 1)
        score += (1 - accuracy) * 26
    else:
        score += 5

    if not last_attempt:
        score += 3 if candidate.get("difficulty") == "medium" else 0
        return score

    recent_topic_count = get_recent_topic_count(session_attempts, candidate.get("topicId"))
    if candidate.get("topicId") == last_attempt.get("topicId"):
        score += 14 if last_attempt.get("correct") else 24
        if last_attempt.get("correct") and candidate.get("eloRating", 1400) > last_attempt.get("eloRating", 1400):
            score += 16
        if (not last_attempt.get("correct")) and candidate.get("eloRating", 1400) <= last_attempt.get("eloRating", 1400):
            score += 18
    else:
        score += 8 if recent_topic_count == 0 else 0

    if recent_topic_count >= 2 and last_attempt.get("correct") and candidate.get("topicId") == last_attempt.get("topicId"):
        score -= 12

    if candidate.get("type") != "mcq" and target_difficulty != "easy":
        score += 2

    if remediation_target_question_id:
        remediation_attempts = [
            item for item in session_attempts if item.get("remediationForQuestionId") == remediation_target_question_id
        ]
        rapid_guess_hits = sum(1 for item in remediation_attempts if item.get("rapidGuessWarning"))
        if rapid_guess_hits > 0 and candidate.get("type") == "mcq":
            score -= 3

    if reward_signal >= 1.4:
        score += 7 if candidate.get("eloRating", 1400) >= target_elo else 2
        if candidate.get("difficulty") == "hard":
            score += 3
    elif reward_signal <= -1:
        if candidate.get("difficulty") == "easy":
            score += 7
        elif candidate.get("difficulty") == "medium":
            score += 2
        else:
            score -= 8
        if candidate.get("eloRating", 1400) > target_elo:
            score -= 6

    return score


def build_reasons(
    candidate,
    target_elo,
    target_difficulty,
    momentum,
    session_attempts,
    topic_stats,
    policy_state,
    graph_metadata,
    remediation_target_question_id=None,
    reward_signal=0.0,
):
    reasons = [f"Targets your current level around ELO {target_elo} with a {target_difficulty} question."]
    last_attempt = session_attempts[-1] if session_attempts else None
    topic_label = get_topic_label(candidate.get("topicId"))
    topic_performance = topic_stats.get(candidate.get("topicId"))
    focus_topic_label = get_topic_label(policy_state.get("focusTopicId"))

    if graph_metadata and graph_metadata.get("mode") == "retry" and remediation_target_question_id == candidate.get("id"):
        reasons.append("This question is returning after enough related follow-up work to retry it with better context.")
    elif not last_attempt:
        reasons.append(f"Starts with a balanced entry point in {topic_label}.")
    elif candidate.get("topicId") == last_attempt.get("topicId") and last_attempt.get("correct"):
        reasons.append("Builds on your last correct answer by pushing the same topic one step further.")
    elif candidate.get("topicId") == last_attempt.get("topicId") and not last_attempt.get("correct"):
        reasons.append(f"Reinforces {topic_label} immediately after a miss so the concept settles before moving on.")
    else:
        reasons.append(f"Rotates to {topic_label} to keep the test challenging without repeating the same pattern.")

    if topic_performance:
        accuracy = topic_performance["correct"] / max(topic_performance["total"], 1)
        if accuracy < 0.6:
            reasons.append(f"{topic_label} is still a weak spot in this session, so it gets extra priority.")

    if policy_state.get("focusTopicId") != "general":
        reasons.append(f"The current session focus is {focus_topic_label} based on your recent attempts.")

    if graph_metadata and graph_metadata.get("mode") == "remediation" and graph_metadata.get("remediationForQuestionId"):
        reasons.append("This is part of a short remediation path connected to the question you just missed.")
    elif graph_metadata and graph_metadata.get("mode") == "retry" and graph_metadata.get("remediationForQuestionId"):
        reasons.append("The engine is bringing back the original missed question after enough progress on related steps.")
    elif graph_metadata and graph_metadata.get("mode") == "neighbor" and graph_metadata.get("fromQuestionId"):
        reasons.append("The next question stays on a neighboring node in the recommendation graph.")
    elif graph_metadata and graph_metadata.get("mode") == "fallback":
        reasons.append("The engine widened the graph search because the closest neighboring nodes were already used.")
    elif graph_metadata and graph_metadata.get("mode") == "seed":
        reasons.append(f"This node acts as the graph entry point for {topic_label}.")

    if graph_metadata and graph_metadata.get("hopDistance") and graph_metadata.get("hopDistance") > 1:
        reasons.append(
            f"It sits on circle {graph_metadata['hopDistance']} of the graph path, so the engine is still following the same learning trail."
        )

    if momentum == "hot":
        reasons.append("Your recent streak is strong, so the engine is raising the challenge slightly.")
    elif momentum == "cold":
        reasons.append("Recent misses lowered the difficulty target a bit to help you recover faster.")

    if reward_signal >= 1.4:
        reasons.append("Recent reward signals are positive, so the engine is comfortable stretching you a bit further.")
    elif reward_signal <= -1:
        reasons.append("Recent penalties pulled the recommendation back toward recovery and steadier accuracy.")

    return reasons


def recommend_next_best_adaptive_question(
    *,
    student_elo,
    question_bank_records,
    graph,
    subject_id=None,
    topic_id=None,
    current_question_id=None,
    constrain_to_topic=False,
    answered_question_ids=None,
    session_question_ids=None,
    session_attempts=None,
    hop_limit=3,
):
    session_attempts = session_attempts or []
    answered_question_ids = answered_question_ids or set()
    session_question_ids = session_question_ids or set()

    policy_state = get_adaptive_policy_state(session_attempts)
    momentum = policy_state["momentum"]
    reward_signal = get_recent_reward_signal(session_attempts)
    target_elo = get_target_elo(student_elo, session_attempts, momentum)
    target_difficulty = get_target_difficulty(target_elo)
    topic_stats = get_topic_stats(session_attempts)
    current_question_id = current_question_id or (session_attempts[-1]["questionId"] if session_attempts else None)
    hop_limit = int(clamp(hop_limit, 1, 3))

    remediation_target = get_remediation_target(session_attempts)
    remediation_target_question = (
        next((item for item in question_bank_records if item["id"] == remediation_target["questionId"]), None)
        if remediation_target
        else None
    )
    remediation_progress = (
        get_remediation_progress(session_attempts, remediation_target["questionId"])
        if remediation_target
        else None
    )
    retry_eligible = bool(
        remediation_target
        and remediation_progress
        and remediation_progress["stepsCompleted"] >= hop_limit
        and remediation_progress["accuracy"] >= 0.34
    )

    excluded_ids = set(answered_question_ids) | set(session_question_ids)
    if retry_eligible and remediation_target:
        excluded_ids.discard(remediation_target["questionId"])

    available = [
        question
        for question in question_bank_records
        if (not subject_id or question.get("subjectId") == subject_id)
        and question["id"] not in excluded_ids
        and (not constrain_to_topic or not topic_id or question.get("topicId") == topic_id)
    ]
    available_by_id = {item["id"]: item for item in available}

    candidate_pool = list(available)
    graph_mode = "fallback" if current_question_id else "seed"
    graph_neighbor_count = 0
    graph_edge_by_question_id = {}
    hop_distance_by_question_id = {}

    if retry_eligible and remediation_target and remediation_target_question and remediation_target["questionId"] in available_by_id:
        retry_question = available_by_id[remediation_target["questionId"]]
        graph_mode = "retry"
        candidate_pool = [retry_question]
        hop_distance_by_question_id[retry_question["id"]] = 0
    elif remediation_target and remediation_target_question:
        remediation_neighbors = [
            item
            for item in get_question_graph_neighbors_within_hops(
                remediation_target["questionId"], available_by_id, hop_limit, graph
            )
            if item["question"]["id"] != remediation_target["questionId"]
        ]
        remediation_neighbors = sorted(
            remediation_neighbors,
            key=lambda item: (
                0 if item["question"].get("topicId") == remediation_target_question.get("topicId") else 1,
                item["hopDistance"],
                -(item["edge"]["weight"] if item["edge"] else 0),
            ),
        )

        if remediation_neighbors:
            graph_mode = "remediation"
            graph_neighbor_count = len(remediation_neighbors)
            preferred_circle = int(
                clamp(remediation_progress["stepsCompleted"] + 1 if remediation_progress else 1, 1, hop_limit)
            )
            circle_scoped_neighbors = [item for item in remediation_neighbors if item["hopDistance"] == preferred_circle]
            remediation_pool = circle_scoped_neighbors if circle_scoped_neighbors else remediation_neighbors
            candidate_pool = []
            for item in remediation_pool:
                if item["edge"]:
                    graph_edge_by_question_id[item["question"]["id"]] = item["edge"]
                hop_distance_by_question_id[item["question"]["id"]] = item["hopDistance"]
                candidate_pool.append(item["question"])

    if (graph_mode in {"fallback", "seed"}) and current_question_id:
        graph_neighbors = get_question_graph_neighbors_within_hops(
            current_question_id, available_by_id, hop_limit, graph
        )
        graph_neighbor_count = len(graph_neighbors)
        if graph_neighbors:
            preferred_circle = get_preferred_neighbor_hop(
                momentum,
                reward_signal,
                session_attempts[-1].get("correct") if session_attempts else None,
                hop_limit,
            )
            circle_scoped_neighbors = [item for item in graph_neighbors if item["hopDistance"] == preferred_circle]
            neighbor_pool = circle_scoped_neighbors if circle_scoped_neighbors else graph_neighbors
            graph_mode = "neighbor"
            candidate_pool = []
            for item in neighbor_pool:
                if item["edge"]:
                    graph_edge_by_question_id[item["question"]["id"]] = item["edge"]
                hop_distance_by_question_id[item["question"]["id"]] = item["hopDistance"]
                candidate_pool.append(item["question"])

    if not available or not candidate_pool:
        return {
            "question": None,
            "reasons": [],
            "targetDifficulty": target_difficulty,
            "targetElo": target_elo,
            "momentum": momentum,
            "graph": None,
            "ranked_candidates": [],
        }

    heuristic_ranked = []
    for candidate in candidate_pool:
        heuristic_score = score_candidate(
            candidate,
            target_elo,
            target_difficulty,
            session_attempts,
            topic_stats,
            remediation_target["questionId"] if remediation_target else None,
            reward_signal,
        )
        heuristic_ranked.append({"candidate": candidate, "heuristicScore": heuristic_score})
    heuristic_ranked = sorted(
        heuristic_ranked,
        key=lambda item: (-item["heuristicScore"], item["candidate"]["id"]),
    )

    ranked_candidates = []
    for item in heuristic_ranked:
        candidate = item["candidate"]
        graph_edge = graph_edge_by_question_id.get(candidate["id"]) or (
            get_question_graph_edge(current_question_id, candidate["id"], graph) if current_question_id else None
        )
        graph_boost = (
            graph_edge["weight"] * (GRAPH_NEIGHBOR_WEIGHT if graph_mode == "neighbor" else GRAPH_FALLBACK_WEIGHT)
            if graph_edge
            else 0
        )
        ranked_candidates.append(
            {
                "candidate": candidate,
                "heuristicScore": item["heuristicScore"],
                "graphBoost": graph_boost,
                "combinedScore": item["heuristicScore"] + graph_boost,
                "graphEdge": graph_edge,
                "hopDistance": hop_distance_by_question_id.get(candidate["id"]),
            }
        )

    ranked_candidates = sorted(
        ranked_candidates,
        key=lambda item: (
            -item["combinedScore"],
            -item["graphBoost"],
            -item["heuristicScore"],
            abs(float(item["candidate"].get("eloRating", 1400)) - target_elo),
        ),
    )

    selected = ranked_candidates[0]
    graph_metadata = {
        "mode": graph_mode,
        "fromQuestionId": current_question_id,
        "edgeWeight": selected["graphEdge"]["weight"] if selected["graphEdge"] else None,
        "edgeKind": selected["graphEdge"]["kind"] if selected["graphEdge"] else None,
        "neighborCount": graph_neighbor_count,
        "hopDistance": selected["hopDistance"],
        "remediationForQuestionId": remediation_target["questionId"] if remediation_target else None,
    }

    return {
        "question": selected["candidate"],
        "reasons": build_reasons(
            selected["candidate"],
            target_elo,
            target_difficulty,
            momentum,
            session_attempts,
            topic_stats,
            policy_state,
            graph_metadata,
            remediation_target["questionId"] if remediation_target else None,
            reward_signal,
        ),
        "targetDifficulty": target_difficulty,
        "targetElo": target_elo,
        "momentum": momentum,
        "graph": graph_metadata,
        "ranked_candidates": ranked_candidates,
        "rewardSignal": reward_signal,
    }


def get_stem_length(question):
    return len(str(question.get("question", "")).strip())


def get_options_length(question):
    return sum(len(str(option).strip()) for option in (question.get("options") or []))


def get_rapid_guess_complexity_index(question):
    combined_text = " ".join([str(question.get("question", ""))] + [str(option) for option in (question.get("options") or [])])
    complexity_index = 0
    if question.get("difficulty") == "medium" or question.get("type") == "msq":
        complexity_index = max(complexity_index, 0.5)
    if (
        question.get("difficulty") == "hard"
        or question.get("type") == "nat"
        or MULTI_STEP_PATTERN.search(str(question.get("question", "")))
        or COMPUTATION_PATTERN.search(combined_text)
    ):
        complexity_index = 1
    return complexity_index


def get_rapid_guess_threshold_seconds(question):
    raw_threshold = (
        RAPID_GUESS_ALPHA_0
        + RAPID_GUESS_ALPHA_1 * get_stem_length(question)
        + RAPID_GUESS_ALPHA_2 * get_options_length(question)
        + RAPID_GUESS_ALPHA_3 * get_rapid_guess_complexity_index(question)
    )
    return max(RAPID_GUESS_ALPHA_0, round(raw_threshold))


def get_rapid_guess_penalty(question, time_spent_seconds):
    threshold = get_rapid_guess_threshold_seconds(question)
    if time_spent_seconds >= threshold:
        return 0
    severity = 1 - time_spent_seconds / max(threshold, 1)
    return max(0, round(severity * RAPID_GUESS_MAX_PENALTY))


def get_standard_elo_gain(student_elo, question_elo):
    expected = 1 / (1 + math.pow(10, (float(question_elo) - float(student_elo)) / 400))
    return max(0, round(32 * (1 - expected)))


def get_rapid_guess_adjusted_elo_gain(student_elo, question, time_spent_seconds, correct):
    if not correct:
        return {"standardGain": 0, "penalty": 0, "appliedPenalty": 0, "adjustedGain": 0}
    standard_gain = get_standard_elo_gain(student_elo, question.get("eloRating", 1400))
    penalty = get_rapid_guess_penalty(question, time_spent_seconds)
    adjusted_gain = max(0, standard_gain - penalty)
    return {
        "standardGain": standard_gain,
        "penalty": penalty,
        "appliedPenalty": standard_gain - adjusted_gain,
        "adjustedGain": adjusted_gain,
    }


FULL_GRAPH = build_question_recommendation_graph(question_bank_full.to_dict("records"))

In [6]:
for s in subjects_meta:
    print(s.get("id"), "→", s.get("name"))

general-aptitude → General Aptitude
linear-algebra → Linear Algebra
probability-statistics → Probability & Statistics
calculus-optimization → Calculus & Optimization
machine-learning → Machine Learning
artificial-intelligence → Artificial Intelligence
programming-dsa → Programming & DSA
dbms → Database Management Systems

In [9]:
# ============================================================
# 5. REPLAY ADAPTIVE SESSIONS AND EXPLAIN EVERY RECOMMENDATION STEP
# ============================================================

SIMULATION_SUBJECT_ID = None  # None = all subjects

SIMULATION_TEST_ID="b362dfde-97c4-4e67-95cf-4b99cae00c20"

selected_session_id = None
selected_session_steps_df = pd.DataFrame()
simulation_sessions_df = pd.DataFrame()
simulation_steps_df = pd.DataFrame()
simulation_candidates_df = pd.DataFrame()
future_recommendations_df = pd.DataFrame()
simulation_summary_df = pd.DataFrame()
simulation_data_source = "live"
adaptive_history_df = (
    test_history_df[test_history_df["test_type"] == "adaptive"].copy()
    if not test_history_df.empty
    else pd.DataFrame()
)

# Generated adaptive attempts have been removed. This section only replays recorded website attempts.

adaptive_timeline_test_ids = set()
if not student_question_timeline_df.empty and {"test_id", "test_type"}.issubset(student_question_timeline_df.columns):
    adaptive_timeline_test_ids = set(
        student_question_timeline_df[
            student_question_timeline_df["test_type"] == "adaptive"
        ]["test_id"].dropna().astype(str).tolist()
    )

live_replay_session_ids = (
    adaptive_history_df[adaptive_history_df["id"].astype(str).isin(adaptive_timeline_test_ids)]["id"]
    .astype(str)
    .tolist()
    if not adaptive_history_df.empty and adaptive_timeline_test_ids
    else []
)



def resolve_requested_test_history_id(history_df, requested_id):
    requested = str(requested_id or "").strip()
    if not requested or history_df.empty:
        return None, pd.DataFrame()

    candidates = history_df.copy()
    match_mask = pd.Series(False, index=candidates.index)
    for column in ["id", "website_test_id", "recorded_test_id", "full_gate_paper_id"]:
        if column in candidates.columns:
            match_mask = match_mask | (candidates[column].astype(str) == requested)

    matches = candidates[match_mask].copy()
    if matches.empty:
        return None, matches
    if "completed_at" in matches.columns:
        matches = matches.sort_values(["completed_at", "id"])
    else:
        matches = matches.sort_values(["id"])
    return str(matches.iloc[-1]["id"]), matches


requested_session_id, requested_session_matches_df = resolve_requested_test_history_id(
    test_history_df,
    SIMULATION_TEST_ID,
)
if SIMULATION_TEST_ID:
    if requested_session_id:
        print(
            f"Selected test input {SIMULATION_TEST_ID!r} resolved to website_test_id/test_history.id "
            f"{requested_session_id!r}."
        )
        if len(requested_session_matches_df) > 1:
            print(
                f"The input matched {len(requested_session_matches_df)} attempts; using the latest completed attempt."
            )
    else:
        print(
            f"Selected test input {SIMULATION_TEST_ID!r} was not found in visible test_history rows. "
            "Check STUDENT_ID/auth, or paste the website_test_id from the live dashboard table."
        )

# Recorded-test mode only: never create generated sessions.
# If the selected test has no visible per-question path, stop with a clear message
# instead of silently replacing it with generated attempts.
use_simulation_fallback = False
if SIMULATION_MODE == "force":
    print("SIMULATION_MODE='force' ignored: recorded-test graph/video mode only uses recorded attempts.")

# Force session_subject_id to None so all subjects are included
session_subject_id = None

if adaptive_history_df.empty:
    adaptive_history_df = pd.DataFrame(
        columns=[
            "id",
            "completed_at",
            "subject_id",
            "topic_id",
            "derived_subject_scope",
            "derived_topic_scope",
            "score",
            "max_score",
            "correct_answers",
            "total_questions",
            "duration_seconds",
        ]
    )
else:
    adaptive_history_df = adaptive_history_df.sort_values(
        [column for column in ["completed_at", "id"] if column in adaptive_history_df.columns]
    ).reset_index(drop=True)
simulation_sessions_df = adaptive_history_df[
    [
        column
        for column in [
            "id",
            "completed_at",
            "subject_id",
            "topic_id",
            "derived_subject_scope",
            "derived_topic_scope",
            "score",
            "max_score",
            "correct_answers",
            "total_questions",
            "duration_seconds",
        ]
        if column in adaptive_history_df.columns
    ]
].copy()
display(simulation_sessions_df)

replayable_history_df = adaptive_history_df[
    adaptive_history_df["id"].astype(str).isin(set(live_replay_session_ids))
].copy()

recorded_steps_df = pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)
if requested_session_id and not student_question_timeline_df.empty and "test_id" in student_question_timeline_df.columns:
    recorded_steps_df = (
        student_question_timeline_df[
            student_question_timeline_df["test_id"].astype(str) == str(requested_session_id)
        ]
        .sort_values(["step_number", "question_id"])
        .reset_index(drop=True)
    )

if requested_session_id and not recorded_steps_df.empty:
    selected_session_id = requested_session_id
    if not requested_session_matches_df.empty:
        selected_session_row = requested_session_matches_df.sort_values(
            [column for column in ["completed_at", "id"] if column in requested_session_matches_df.columns]
        ).iloc[-1]
    else:
        selected_matches = test_history_df[
            test_history_df["id"].astype(str) == str(requested_session_id)
        ].copy()
        selected_session_row = selected_matches.iloc[-1] if not selected_matches.empty else None
    selected_session_steps_df = recorded_steps_df
    simulation_data_source = "recorded"
    print(
        f"Using recorded question path for selected test {selected_session_id!r}: "
        f"{len(selected_session_steps_df)} steps. No generated fallback path will be used."
    )
elif requested_session_id:
    selected_session_id = None
    selected_session_row = None
    selected_session_steps_df = pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)
    print(
        f"Selected test {requested_session_id!r} was found in test_history, but no per-question "
        "path was visible in review_payload, graph_path activity, or question_answered activity. "
        "No generated fallback path will be used, so there is no generated replacement path to graph. "
        "Re-run the website test after review_payload or graph_path_completed activity is being saved, "
        "or authenticate the notebook with the same student account so RLS exposes those rows."
    )
elif not replayable_history_df.empty:
    selected_session_id = str(replayable_history_df.iloc[-1]["id"])
    selected_session_row = replayable_history_df[replayable_history_df["id"].astype(str) == selected_session_id].iloc[0]
    selected_session_steps_df = (
        student_question_timeline_df[student_question_timeline_df["test_id"].astype(str) == selected_session_id]
        .sort_values(["step_number", "question_id"])
        .reset_index(drop=True)
    )
    simulation_data_source = "recorded"
    print(
        f"Using latest replayable recorded adaptive session {selected_session_id!r}: "
        f"{len(selected_session_steps_df)} steps."
    )
else:
    selected_session_id = None
    selected_session_row = None
    selected_session_steps_df = pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)
    print(
        "No replayable recorded adaptive sessions were visible. No generated fallback path will be used, "
        "so the graph/video cells will not invent a path."
    )

prior_attempts_df = (
    student_question_timeline_df[
        (student_question_timeline_df["completed_at"] < selected_session_row["completed_at"])
        & (student_question_timeline_df["answered"] == True)
    ].copy()
    if selected_session_row is not None
    else pd.DataFrame(columns=QUESTION_TIMELINE_COLUMNS)
)
prior_answered_ids = set(prior_attempts_df["question_id"].tolist())

if SIMULATION_BANK_MODE == "live":
    simulation_bank_df = question_bank_full[question_bank_full["is_live_adaptive_eligible"]].copy()
else:
    simulation_bank_df = question_bank_full.copy()

# session_subject_id is already None (all subjects)

simulation_bank_records = simulation_bank_df.to_dict("records")
running_elo = float(SIMULATION_START_ELO)
session_attempts = []
session_served_ids = set()
step_rows = []
candidate_rows = []

for row in selected_session_steps_df.itertuples(index=False):
    recommendation = recommend_next_best_adaptive_question(
        student_elo=running_elo,
        question_bank_records=simulation_bank_records,
        graph=FULL_GRAPH,
        subject_id=None,  # all subjects
        topic_id=None,
        current_question_id=session_attempts[-1]["questionId"] if session_attempts else None,
        constrain_to_topic=False,
        answered_question_ids=prior_answered_ids,
        session_question_ids=session_served_ids,
        session_attempts=session_attempts,
        hop_limit=3,
    )

    actual_question = question_lookup.get(row.question_id, {})
    actual_question_fallback = {
        "id": row.question_id,
        "subjectId": row.subjectId,
        "topicId": row.topicId,
        "difficulty": row.difficulty,
        "eloRating": row.question_elo if pd.notna(row.question_elo) else 1400,
        "type": row.question_type,
        "question": row.question_text,
        "options": [],
        "marks": row.marks if pd.notna(row.marks) else 1,
        "negativeMarks": 0,
    }
    if not actual_question:
        actual_question = actual_question_fallback

    recommended_question = recommendation.get("question")
    recommended_question_id = recommended_question.get("id") if recommended_question else None
    reasons_text = " | ".join(recommendation.get("reasons", []))

    ranked_candidates = recommendation.get("ranked_candidates", [])
    for rank, candidate_info in enumerate(ranked_candidates[:8], start=1):
        candidate = candidate_info["candidate"]
        candidate_rows.append(
            {
                "test_id": selected_session_id,
                "step_number": row.step_number,
                "rank": rank,
                "candidate_question_id": candidate.get("id"),
                "candidate_subject": candidate.get("subjectId"),
                "candidate_topic": candidate.get("topicId"),
                "candidate_difficulty": candidate.get("difficulty"),
                "candidate_elo": candidate.get("eloRating"),
                "heuristic_score": round(candidate_info.get("heuristicScore", 0), 4),
                "graph_boost": round(candidate_info.get("graphBoost", 0), 4),
                "combined_score": round(candidate_info.get("combinedScore", 0), 4),
                "graph_edge_kind": candidate_info.get("graphEdge", {}).get("kind") if candidate_info.get("graphEdge") else None,
                "graph_edge_weight": candidate_info.get("graphEdge", {}).get("weight") if candidate_info.get("graphEdge") else None,
                "hop_distance": candidate_info.get("hopDistance"),
                "selected": candidate.get("id") == recommended_question_id,
            }
        )

    step_rows.append(
        {
            "test_id": selected_session_id,
            "completed_at": row.completed_at,
            "step_number": row.step_number,
            "student_elo_before_step": round(running_elo, 2),
            "actual_question_id": row.question_id,
            "actual_question_text": row.question_text,
            "actual_subject": row.subjectName,
            "actual_topic": row.topicName,
            "actual_difficulty": row.difficulty,
            "actual_question_elo": row.question_elo,
            "answered": row.answered,
            "correct": row.correct,
            "time_spent_seconds": row.time_spent_seconds,
            "rapid_guess_warning": row.rapid_guess_warning,
            "rapid_guess_threshold_seconds": row.rapid_guess_threshold_seconds,
            "recommended_question_id": recommended_question_id,
            "recommended_question_text": recommended_question.get("question") if recommended_question else None,
            "recommended_matches_actual": recommended_question_id == row.question_id,
            "target_elo": recommendation.get("targetElo"),
            "target_difficulty": recommendation.get("targetDifficulty"),
            "momentum": recommendation.get("momentum"),
            "reward_signal": recommendation.get("rewardSignal"),
            "graph_mode": recommendation.get("graph", {}).get("mode") if recommendation.get("graph") else None,
            "graph_from_question_id": recommendation.get("graph", {}).get("fromQuestionId") if recommendation.get("graph") else None,
            "graph_edge_kind": recommendation.get("graph", {}).get("edgeKind") if recommendation.get("graph") else None,
            "graph_edge_weight": recommendation.get("graph", {}).get("edgeWeight") if recommendation.get("graph") else None,
            "graph_hop_distance": recommendation.get("graph", {}).get("hopDistance") if recommendation.get("graph") else None,
            "graph_neighbor_count": recommendation.get("graph", {}).get("neighborCount") if recommendation.get("graph") else None,
            "remediation_for_question_id": row.remediation_for_question_id,
            "reasons": reasons_text,
        }
    )

    time_spent_seconds = row.time_spent_seconds if pd.notna(row.time_spent_seconds) else 0
    elo_outcome = get_rapid_guess_adjusted_elo_gain(
        running_elo,
        actual_question,
        time_spent_seconds,
        bool(row.correct),
    )
    running_elo += elo_outcome["adjustedGain"]

    if row.answered:
        prior_answered_ids.add(row.question_id)
    session_served_ids.add(row.question_id)
    session_attempts.append(
        {
            "questionId": row.question_id,
            "topicId": row.topicId,
            "difficulty": row.difficulty,
            "eloRating": actual_question.get("eloRating", row.question_elo if pd.notna(row.question_elo) else 1400),
            "correct": bool(row.correct),
            "rapidGuessWarning": bool(row.rapid_guess_warning) if pd.notna(row.rapid_guess_warning) else False,
            "remediationForQuestionId": row.remediation_for_question_id,
        }
    )

simulation_steps_df = pd.DataFrame(step_rows)
simulation_candidates_df = pd.DataFrame(candidate_rows)

all_adaptive_steps_df = (
    student_question_timeline_df[student_question_timeline_df["test_type"] == "adaptive"]
    .sort_values(["completed_at", "test_id", "step_number"])
    .reset_index(drop=True)
)
forecast_attempts = []
forecast_answered_ids = set(
    student_question_timeline_df[student_question_timeline_df["answered"] == True]["question_id"].tolist()
)
forecast_served_ids = set()
forecast_running_elo = float(SIMULATION_START_ELO)
for row in all_adaptive_steps_df.itertuples(index=False):
    question_record = question_lookup.get(row.question_id)
    if question_record:
        outcome = get_rapid_guess_adjusted_elo_gain(
            forecast_running_elo,
            question_record,
            row.time_spent_seconds if pd.notna(row.time_spent_seconds) else 0,
            bool(row.correct),
        )
        forecast_running_elo += outcome["adjustedGain"]
    forecast_attempts.append(
        {
            "questionId": row.question_id,
            "topicId": row.topicId,
            "difficulty": row.difficulty,
            "eloRating": question_record.get("eloRating", row.question_elo if pd.notna(row.question_elo) else 1400)
            if question_record
            else 1400,
            "correct": bool(row.correct),
            "rapidGuessWarning": bool(row.rapid_guess_warning) if pd.notna(row.rapid_guess_warning) else False,
            "remediationForQuestionId": row.remediation_for_question_id,
        }
    )

future_rows = []
for future_step in range(1, SIMULATION_STEPS_AHEAD + 1):
    recommendation = recommend_next_best_adaptive_question(
        student_elo=forecast_running_elo if forecast_attempts else current_elo,
        question_bank_records=simulation_bank_records,
        graph=FULL_GRAPH,
        subject_id=None,  # all subjects
        topic_id=None,
        current_question_id=forecast_attempts[-1]["questionId"] if forecast_attempts else None,
        constrain_to_topic=False,
        answered_question_ids=forecast_answered_ids,
        session_question_ids=forecast_served_ids,
        session_attempts=forecast_attempts,
        hop_limit=3,
    )
    future_question = recommendation.get("question")
    if not future_question:
        break

    future_rows.append(
        {
            "forecast_step": future_step,
            "question_id": future_question.get("id"),
            "subject": get_subject_name(future_question.get("subjectId")),
            "topic": get_topic_name(future_question.get("subjectId"), future_question.get("topicId")),
            "difficulty": future_question.get("difficulty"),
            "question_elo": future_question.get("eloRating"),
            "target_elo": recommendation.get("targetElo"),
            "target_difficulty": recommendation.get("targetDifficulty"),
            "momentum": recommendation.get("momentum"),
            "graph_mode": recommendation.get("graph", {}).get("mode") if recommendation.get("graph") else None,
            "graph_edge_kind": recommendation.get("graph", {}).get("edgeKind") if recommendation.get("graph") else None,
            "graph_hop_distance": recommendation.get("graph", {}).get("hopDistance") if recommendation.get("graph") else None,
            "reasons": " | ".join(recommendation.get("reasons", [])),
        }
    )

    forecast_served_ids.add(future_question["id"])
    forecast_answered_ids.add(future_question["id"])
    forecast_attempts.append(
        {
            "questionId": future_question["id"],
            "topicId": future_question.get("topicId"),
            "difficulty": future_question.get("difficulty"),
            "eloRating": future_question.get("eloRating", 1400),
            "correct": True,
            "rapidGuessWarning": False,
            "remediationForQuestionId": recommendation.get("graph", {}).get("remediationForQuestionId"),
        }
    )
    forecast_running_elo += get_standard_elo_gain(forecast_running_elo, future_question.get("eloRating", 1400))

future_recommendations_df = pd.DataFrame(future_rows)

simulation_summary_df = pd.DataFrame(
    [
        {
            "selected_session_id": selected_session_id,
            "simulation_bank_mode": SIMULATION_BANK_MODE,
            "simulation_start_elo": SIMULATION_START_ELO,
            "session_steps": len(simulation_steps_df),
            "recommended_matches_actual_pct": round(
                100 * simulation_steps_df["recommended_matches_actual"].mean(), 2
            )
            if not simulation_steps_df.empty
            else np.nan,
            "session_accuracy_pct": round(
                100 * simulation_steps_df["correct"].fillna(False).mean(), 2
            )
            if not simulation_steps_df.empty
            else np.nan,
        }
    ]
)

display(simulation_summary_df)
display(simulation_steps_df)
display(simulation_candidates_df.head(80))
display(future_recommendations_df)

Selected test input 'b362dfde-97c4-4e67-95cf-4b99cae00c20' resolved to website_test_id/test_history.id 'b362dfde-97c4-4e67-95cf-4b99cae00c20'.

,id,completed_at,subject_id,topic_id,derived_subject_scope,derived_topic_scope,score,max_score,correct_answers,total_questions,duration_seconds
0,a3f0e115-3151-4924-af8a-d4c91b018f26,2026-04-10 09:38:47.672000+00:00,artificial-intelligence,NaN,NaN,NaN,6.70,20,5,10,NaN
1,8a413ac3-996b-4ea0-9d70-325688b8a42c,2026-04-13 19:38:44.960000+00:00,programming-dsa,NaN,NaN,NaN,1.36,12,2,10,NaN
2,4ee7ece4-8182-453d-9121-b402b1c6c3dd,2026-04-13 19:40:44.223000+00:00,calculus-optimization,NaN,NaN,NaN,-0.66,2,0,10,NaN
3,96a915f1-fd41-48ff-9fb9-c36a1d21774a,2026-04-14 17:16:41.122000+00:00,artificial-intelligence,NaN,NaN,NaN,4.00,18,2,10,0.0
4,06f4c5d8-fb9e-420e-8793-6a429f2a8729,2026-04-14 17:20:08.721000+00:00,machine-learning,NaN,NaN,NaN,0.00,13,0,10,0.0
5,ed50f3e9-7e4b-4ca1-95d8-8834e5f1a9fe,2026-04-14 17:20:09.419000+00:00,machine-learning,NaN,NaN,NaN,0.00,13,0,10,0.0
6,02e8d2d1-64d6-4d6e-801c-c17a89a3bcfb,2026-04-14 17:20:10.004000+00:00,machine-learning,NaN,NaN,NaN,0.00,13,0,10,0.0
7,95cb2009-6a36-4c34-81a7-62f68c46214f,2026-04-15 11:19:41.650000+00:00,programming-dsa,NaN,NaN,NaN,-0.33,13,0,10,0.0
8,3bf6d287-46de-43c8-ad04-908f0a158a33,2026-04-18 05:33:34.144000+00:00,probability-statistics,NaN,NaN,NaN,-0.95,19,2,10,NaN
9,90d39ac9-d6b7-4278-8820-f34dfdf9367f,2026-04-18 21:59:23.076000+00:00,probability-statistics,NaN,NaN,NaN,0.01,14,1,10,0.0
10,ac6e4fe6-e072-4908-9368-1e6c01ba1779,2026-04-18 22:13:57.494000+00:00,NaN,NaN,NaN,NaN,6.67,18,4,10,0.0
11,0ada2a79-42f8-452a-b97b-86c6a6d89c90,2026-04-19 11:24:03.407000+00:00,NaN,NaN,NaN,NaN,2.00,18,1,10,0.0
12,dd05402e-65f8-4043-be68-98961d7b9a17,2026-04-19 18:08:04.178000+00:00,NaN,NaN,NaN,NaN,1.02,17,2,10,51.0
13,c432448c-efbe-48bf-a029-e2b204ae00dc,2026-04-21 15:47:59.723000+00:00,dbms,NaN,NaN,NaN,0.00,18,0,10,142.0
14,4b85b226-ff23-4c92-b189-cf66849f6495,2026-04-22 07:05:33.849000+00:00,NaN,NaN,NaN,NaN,1.01,14,2,10,20.0
15,1ca940fd-587d-4342-96a4-f522f96d0ada,2026-04-22 23:40:10.013000+00:00,NaN,NaN,NaN,NaN,-0.31,17,1,10,12.0
16,06c9aeec-940b-4dab-b926-8c6b441e75d0,2026-04-22 23:41:15.695000+00:00,NaN,NaN,NaN,NaN,-1.32,6,0,3,5.0
17,e3bd6c25-96b6-4770-a18d-1d646909e436,2026-04-22 23:41:46.773000+00:00,NaN,NaN,NaN,NaN,0.70,18,2,9,16.0
18,4db22b82-cc7d-477b-b95e-9a92433462aa,2026-04-22 23:43:41.213000+00:00,probability-statistics,NaN,NaN,NaN,1.34,14,2,10,16.0
19,a67efb00-a019-45c6-86a6-317dd7d0cfda,2026-04-23 14:54:54.266000+00:00,calculus-optimization,NaN,NaN,NaN,2.70,20,3,10,25.0
20,60cd466b-92e1-41d0-842a-03c19e3346f0,2026-04-23 14:58:01.417000+00:00,machine-learning,NaN,NaN,NaN,-1.65,13,0,10,27.0
21,23f0ca44-d89c-4a8e-a425-747854545a98,2026-04-23 14:58:46.072000+00:00,machine-learning,NaN,NaN,NaN,-0.32,28,1,20,27.0
22,63bd0d7c-7b22-41a4-a702-be8a00d7d811,2026-04-23 16:10:43.407000+00:00,linear-algebra,NaN,NaN,NaN,4.02,14,3,7,11.0
23,4d7a5b89-9efd-4dd7-9ac3-1926cae001fe,2026-04-23 16:31:52.703000+00:00,NaN,NaN,NaN,NaN,-0.62,20,2,10,16.0
24,67f89dfa-d791-4479-b416-6b35a19e6738,2026-04-23 17:51:18.843000+00:00,probability-statistics,NaN,NaN,NaN,-4.62,17,0,10,13.0
25,d9ada535-0a26-4a0e-ae52-8747ce5cd81f,2026-04-23 18:25:40.711000+00:00,NaN,NaN,NaN,NaN,-0.62,20,2,10,17.0
26,cb4afea2-e651-444c-9f17-8cfb716e5a27,2026-04-27 06:58:16.045000+00:00,linear-algebra,NaN,NaN,NaN,15.34,20,8,10,205.0
27,fbd2839c-11c5-48cf-aa97-1309d724cf77,2026-04-30 22:09:16.294000+00:00,NaN,NaN,NaN,NaN,21.46,84,17,42,665.0
28,027bc67d-29d0-4cad-beaf-d83c1d73fd7b,2026-05-01 11:13:36.384000+00:00,calculus-optimization,None,Calculus & Optimization,Mixed topics,-3.94,20,1,10,20.0
29,588c0d2a-72b2-4dae-9715-2dc2d5ef87c8,2026-05-01 12:08:49.217000+00:00,None,None,Mixed subjects,Mixed topics,23.87,109,26,65,273.0
30,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,calculus-optimization,None,Calculus & Optimization,Mixed topics,8.70,26,6,13,55.0

Using recorded question path for selected test 'b362dfde-97c4-4e67-95cf-4b99cae00c20': 13 steps. No generated fallback path will be used.

,selected_session_id,simulation_bank_mode,simulation_start_elo,session_steps,recommended_matches_actual_pct,session_accuracy_pct
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,complete,1600,13,0.0,46.15

,test_id,completed_at,step_number,student_elo_before_step,actual_question_id,actual_question_text,actual_subject,actual_topic,actual_difficulty,actual_question_elo,...,momentum,reward_signal,graph_mode,graph_from_question_id,graph_edge_kind,graph_edge_weight,graph_hop_distance,graph_neighbor_count,remediation_for_question_id,reasons
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,1,1600.0,co-44,Changing order of integration requires?,Calculus & Optimization,Integration,hard,1500.0,...,steady,0.00,seed,None,None,NaN,NaN,0,None,Targets your current level around ELO 1600 wit...
1,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,2,1600.0,co-56,If Hessian is positive definite then?,Calculus & Optimization,Optimization,hard,1500.0,...,steady,0.91,neighbor,co-44,same-topic,0.9789,2.0,33,None,Targets your current level around ELO 1657 wit...
2,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,3,1600.0,co-53,A function is convex if?,Calculus & Optimization,Optimization,medium,1400.0,...,steady,1.82,neighbor,co-56,same-topic,0.9789,2.0,30,None,Targets your current level around ELO 1679 wit...
3,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,4,1600.0,co-49,Update rule in gradient descent is?,Calculus & Optimization,Optimization,medium,1400.0,...,steady,0.82,remediation,co-53,same-topic,0.9844,3.0,29,co-53,Targets your current level around ELO 1560 wit...
4,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,5,1600.0,co-6,"In gradient descent, a very high learning rate...",Calculus & Optimization,Optimization,medium,1400.0,...,cold,-0.18,remediation,co-49,subject-flow,0.6789,3.0,29,co-49,Targets your current level around ELO 1446 wit...
5,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,6,1600.0,co-40,Integration by parts formula is?,Calculus & Optimization,Integration,medium,1400.0,...,steady,-0.28,remediation,co-6,same-topic,0.9789,2.0,29,co-49,Targets your current level around ELO 1628 wit...
6,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,7,1600.0,co-45,The integral ∫_0^∞ e^-x dx equals?,Calculus & Optimization,Integration,medium,1400.0,...,cold,-2.19,remediation,co-40,same-topic,0.9789,2.0,33,co-40,Targets your current level around ELO 1397 wit...
7,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,8,1600.0,co-33,Fundamental theorem of calculus connects?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-45,same-topic,0.9789,2.0,33,co-45,Targets your current level around ELO 1397 wit...
8,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,9,1600.0,co-37,The integral ∫_0^π sin x dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-33,subject-flow,0.4216,1.0,25,co-33,Targets your current level around ELO 1397 wit...
9,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,10,1600.0,co-38,If f(x) is odd then ∫_-a^a f(x)dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-37,same-topic,0.9789,2.0,25,co-33,Targets your current level around ELO 1492 wit...
10,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,11,1600.0,co-39,If f(x) is even then ∫_-a^a f(x)dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,steady,-0.38,remediation,co-38,same-topic,0.9844,3.0,25,co-33,Targets your current level around ELO 1626 wit...
11,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,12,1600.0,mock2-q8,Consider the series ∑_{n=1}^∞ 1/n(n+1). Which ...,Calculus & Optimization,Integration,medium,1450.0,...,hot,1.43,retry,co-39,same-topic,0.9789,0.0,0,co-33,Targets your current level around ELO 1744 wit...
12,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,13,1600.0,mock3-q8,Consider the series ∑_{n=2}^∞ 1/(n ln n). Whic...,Calculus & Optimization,Integration,medium,1450.0,...,steady,1.43,remediation,mock2-q8,same-topic,0.9407,1.0,33,None,Targets your current level around ELO 1574 wit...

,test_id,step_number,rank,candidate_question_id,candidate_subject,candidate_topic,candidate_difficulty,candidate_elo,heuristic_score,graph_boost,combined_score,graph_edge_kind,graph_edge_weight,hop_distance,selected
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,1,mock4-q40,machine-learning,ml-evaluation,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,True
1,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,2,mock4-q43,machine-learning,ml-supervised,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
2,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,3,mock4-q44,linear-algebra,la-matrices,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
3,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,4,mock4-q48,machine-learning,ml-supervised,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
4,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,5,mock4-q50,probability-statistics,ps-probability,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,b362dfde-97c4-4e67-95cf-4b99cae00c20,11,7,da2026-q39,calculus-optimization,co-differentiation,medium,1400.0,115.1667,13.7046,128.8713,same-topic,0.9789,3.0,False
76,b362dfde-97c4-4e67-95cf-4b99cae00c20,11,8,da2025-q57,dbms,dbms-normalization,medium,1400.0,120.1667,5.9696,126.1363,subject-flow,0.4264,3.0,False
77,b362dfde-97c4-4e67-95cf-4b99cae00c20,12,1,co-33,calculus-optimization,co-integration,medium,1350.0,103.3095,13.7046,117.0141,same-topic,0.9789,0.0,True
78,b362dfde-97c4-4e67-95cf-4b99cae00c20,13,1,co-41,calculus-optimization,co-integration,hard,1500.0,169.8333,13.1698,183.0031,same-topic,0.9407,1.0,True
79,b362dfde-97c4-4e67-95cf-4b99cae00c20,13,2,mock2-q50,calculus-optimization,co-differentiation,medium,1450.0,130.6667,9.5046,140.1713,subject-flow,0.6789,1.0,False

,forecast_step,question_id,subject,topic,difficulty,question_elo,target_elo,target_difficulty,momentum,graph_mode,graph_edge_kind,graph_hop_distance,reasons
0,1,co-41,Calculus & Optimization,Integration,hard,1500.0,1441,medium,cold,remediation,same-topic,1,Targets your current level around ELO 1441 wit...
1,2,co-51,Calculus & Optimization,Optimization,hard,1500.0,1655,hard,steady,remediation,subject-flow,2,Targets your current level around ELO 1655 wit...
2,3,co-62,Calculus & Optimization,Optimization,hard,1500.0,1682,hard,steady,remediation,same-topic,3,Targets your current level around ELO 1682 wit...
3,4,mock3-q8,Calculus & Optimization,Integration,medium,1450.0,1800,hard,hot,retry,None,0,Targets your current level around ELO 1800 wit...
4,5,ai-1,Artificial Intelligence,Search Algorithms,hard,1410.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...
5,6,co-15,Calculus & Optimization,Differentiation,medium,1350.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...
6,7,ai-3,Artificial Intelligence,Propositional & Predicate Logic,hard,1410.0,1800,hard,hot,neighbor,subject-flow,3,Targets your current level around ELO 1800 wit...
7,8,co-16,Calculus & Optimization,Differentiation,medium,1350.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...

In [10]:
# ============================================================
# 6. INTERACTIVE FULL-DATASET GRAPH + DASHBOARD PLOTS
# ============================================================

graph_nx = nx.Graph()
for node in FULL_GRAPH["nodes"]:
    graph_nx.add_node(node["id"])
for edge in FULL_GRAPH["edges"]:
    graph_nx.add_edge(
        edge["sourceId"],
        edge["targetId"],
        weight=edge["weight"],
        edge_kind=edge["kind"],
    )

if graph_nx.number_of_nodes() > 0:
    pos = nx.spring_layout(graph_nx, seed=42, k=0.42, iterations=180, weight="weight")
else:
    pos = {}

degree_map = dict(graph_nx.degree()) if graph_nx.number_of_nodes() > 0 else {}
try:
    if graph_nx.number_of_nodes() > 2:
        betweenness_map = nx.betweenness_centrality(
            graph_nx,
            k=min(250, max(30, graph_nx.number_of_nodes() - 1)),
            normalized=True,
            seed=42,
            weight="weight",
        )
    else:
        betweenness_map = {node_id: 0 for node_id in graph_nx.nodes}
except Exception:
    betweenness_map = {node_id: 0 for node_id in graph_nx.nodes}

def parse_activity_metadata(value):
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return {}
        try:
            return json.loads(text)
        except Exception:
            return {}
    return {}


def build_graph_path_details(metadata, fallback_steps_df=None):
    metadata = metadata or {}
    raw_path = metadata.get("question_path") or metadata.get("questionPath") or []
    raw_steps = metadata.get("steps") if isinstance(metadata.get("steps"), list) else []
    path_question_ids = []
    path_step_map = {}
    node_state_map = {}
    ordered_steps = []

    if raw_steps:
        for index, raw_step in enumerate(raw_steps, start=1):
            if not isinstance(raw_step, dict):
                continue
            question_id = raw_step.get("question_id") or raw_step.get("questionId")
            if not question_id:
                continue
            step_order = raw_step.get("order", index)
            try:
                step_order = int(step_order)
            except Exception:
                step_order = index
            ordered_steps.append(
                {
                    "order": step_order,
                    "question_id": question_id,
                    "correct": raw_step.get("correct"),
                }
            )
        ordered_steps = sorted(ordered_steps, key=lambda item: item["order"])
        for step in ordered_steps:
            question_id = step["question_id"]
            path_question_ids.append(question_id)
            path_step_map[question_id] = int(step["order"])
            if step["correct"] is True:
                node_state_map[question_id] = "correct"
            elif step["correct"] is False:
                node_state_map[question_id] = "wrong"
            else:
                node_state_map[question_id] = "pending"
    elif raw_path:
        for index, question_id in enumerate([item for item in raw_path if item], start=1):
            path_question_ids.append(question_id)
            path_step_map[question_id] = index
            node_state_map[question_id] = "pending"
    elif fallback_steps_df is not None and not fallback_steps_df.empty:
        for index, row in enumerate(fallback_steps_df.sort_values("step_number").itertuples(index=False), start=1):
            question_id = getattr(row, "actual_question_id", None) or getattr(row, "question_id", None)
            if not question_id:
                continue
            path_question_ids.append(question_id)
            path_step_map[question_id] = int(getattr(row, "step_number", index))
            if getattr(row, "correct", None) is True:
                node_state_map[question_id] = "correct"
            elif getattr(row, "correct", None) is False:
                node_state_map[question_id] = "wrong"
            else:
                node_state_map[question_id] = "pending"
            ordered_steps.append(
                {
                    "order": int(getattr(row, "step_number", index)),
                    "question_id": question_id,
                    "correct": getattr(row, "correct", None),
                }
            )

    current_question_id = metadata.get("current_question_id") or metadata.get("currentQuestionId")
    if current_question_id and current_question_id not in path_step_map:
        path_question_ids.append(current_question_id)
        path_step_map[current_question_id] = len(path_question_ids)
    if current_question_id and node_state_map.get(current_question_id) not in {"correct", "wrong"}:
        node_state_map[current_question_id] = "current"

    return {
        "path_question_ids": path_question_ids,
        "path_step_map": path_step_map,
        "node_state_map": node_state_map,
        "ordered_steps": ordered_steps,
        "current_question_id": current_question_id,
        "status": metadata.get("status"),
    }


def build_path_edges_df(path_question_ids):
    rows = []
    for index in range(1, len(path_question_ids)):
        left = path_question_ids[index - 1]
        right = path_question_ids[index]
        edge = get_question_graph_edge(left, right, FULL_GRAPH) or get_question_graph_edge(right, left, FULL_GRAPH)
        rows.append(
            {
                "sourceId": left,
                "targetId": right,
                "edge_kind": edge.get("kind") if edge else None,
                "edge_weight": edge.get("weight") if edge else None,
            }
        )
    return pd.DataFrame(rows)


graph_activity_df = pd.DataFrame()
if not activity_df.empty and "event_type" in activity_df.columns:
    graph_activity_df = activity_df[
        activity_df["event_type"].isin(["graph_path_progress", "graph_path_completed"])
    ].copy()
    if not graph_activity_df.empty:
        graph_activity_df["metadata_parsed"] = graph_activity_df["metadata"].apply(parse_activity_metadata)
        graph_activity_df = graph_activity_df.sort_values(["created_at", "id"]).reset_index(drop=True)

latest_graph_event = graph_activity_df.iloc[-1].to_dict() if not graph_activity_df.empty else {}
latest_graph_metadata = latest_graph_event.get("metadata_parsed", {}) if latest_graph_event else {}

selected_graph_test_id = requested_session_id if "requested_session_id" in globals() else None
selected_test_steps_for_graph_df = pd.DataFrame()
if selected_graph_test_id and not student_question_timeline_df.empty and "test_id" in student_question_timeline_df.columns:
    selected_test_steps_for_graph_df = (
        student_question_timeline_df[student_question_timeline_df["test_id"].astype(str) == str(selected_graph_test_id)]
        .sort_values(["step_number", "question_id"])
        .reset_index(drop=True)
    )

if not selected_test_steps_for_graph_df.empty:
    live_path_details = build_graph_path_details({}, selected_test_steps_for_graph_df)
else:
    live_path_details = build_graph_path_details(latest_graph_metadata, simulation_steps_df)

latest_outcome_by_question = {}
attempt_history_question_ids = []
attempt_history_seen = set()


def register_attempt(question_id, correct=None):
    if not question_id:
        return
    if question_id not in attempt_history_seen:
        attempt_history_seen.add(question_id)
        attempt_history_question_ids.append(question_id)
    if correct is True:
        latest_outcome_by_question[question_id] = "correct"
    elif correct is False:
        latest_outcome_by_question[question_id] = "wrong"


if not question_attempts_df.empty:
    for row in question_attempts_df.sort_values(["completed_at", "step_number"]).itertuples(index=False):
        if not row.answered:
            continue
        register_attempt(row.question_id, bool(row.correct))

question_answer_events_df = pd.DataFrame()
if not activity_df.empty and "event_type" in activity_df.columns:
    question_answer_events_df = activity_df[activity_df["event_type"] == "question_answered"].copy()
    if not question_answer_events_df.empty:
        question_answer_events_df["metadata_parsed"] = question_answer_events_df["metadata"].apply(parse_activity_metadata)
        question_answer_events_df = question_answer_events_df.sort_values(["created_at", "id"]).reset_index(drop=True)
        for row in question_answer_events_df.itertuples(index=False):
            metadata = getattr(row, "metadata_parsed", {}) or {}
            question_id = getattr(row, "question_id", None) or metadata.get("question_id") or metadata.get("questionId")
            was_correct = metadata.get("was_correct")
            register_attempt(question_id, was_correct)

if not answered_df.empty:
    answered_fallback_df = answered_df.copy()
    if "answered_at" in answered_fallback_df.columns:
        answered_fallback_df = answered_fallback_df.sort_values(["answered_at", "question_id"])
    for row in answered_fallback_df.itertuples(index=False):
        register_attempt(getattr(row, "question_id", None), getattr(row, "was_correct", None))

for step in live_path_details["ordered_steps"]:
    if step.get("correct") is None:
        continue
    register_attempt(step.get("question_id"), step.get("correct"))

if not simulation_steps_df.empty:
    for row in simulation_steps_df.itertuples(index=False):
        if getattr(row, "answered", False):
            register_attempt(getattr(row, "actual_question_id", None), getattr(row, "correct", None))

graph_nodes_rows = []
for question in question_bank_full.to_dict("records"):
    node_id = question["id"]
    x, y = pos.get(node_id, (0, 0))
    graph_nodes_rows.append(
        {
            "id": node_id,
            "x": float(x),
            "y": float(y),
            "subjectId": question.get("subjectId"),
            "topicId": question.get("topicId"),
            "subjectName": question.get("subjectName"),
            "topicName": question.get("topicName"),
            "difficulty": question.get("difficulty"),
            "eloRating": float(question.get("eloRating", 1400)),
            "marks": float(question.get("marks", 1)),
            "type": question.get("type"),
            "degree": int(degree_map.get(node_id, 0)),
            "betweenness": float(betweenness_map.get(node_id, 0)),
            "question_text": question.get("question"),
            "is_live_adaptive_eligible": bool(question.get("is_live_adaptive_eligible")),
        }
    )

base_graph_nodes_df = pd.DataFrame(graph_nodes_rows)


def build_hover_text(row):
    lines = [
        f"<b>{row['id']}</b>",
        f"Subject: {row['subjectName']}",
        f"Topic: {row['topicName']}",
        f"Difficulty: {row['difficulty']}",
        f"ELO: {row['eloRating']:.0f}",
        f"Type: {row['type']}",
        f"Marks: {row['marks']}",
        f"Degree: {row['degree']}",
        f"Betweenness: {row['betweenness']:.4f}",
        f"Student status: {row['status']}",
        f"Live adaptive eligible: {row['is_live_adaptive_eligible']}",
        f"Question: {str(row['question_text'])[:180]}",
    ]
    if pd.notna(row["path_step"]):
        lines.insert(1, f"Path step: {int(row['path_step'])}")
    if bool(row.get("is_current")):
        lines.insert(1, "Current live node: True")
    return "<br>".join(lines)


def build_graph_nodes_df(node_state_map, path_question_ids, current_question_id=None):
    graph_df = base_graph_nodes_df.copy()
    path_step_map = {question_id: index for index, question_id in enumerate(path_question_ids, start=1)}
    graph_df["status"] = graph_df["id"].map(node_state_map).fillna("unseen")
    graph_df["path_step"] = graph_df["id"].map(path_step_map)
    graph_df["is_current"] = graph_df["id"] == current_question_id if current_question_id else False
    graph_df["hover_text"] = graph_df.apply(build_hover_text, axis=1)
    return graph_df



def render_interactive_graph(graph_nodes_df, path_question_ids, title, note, output_html, path_label):
    path_edges_df = build_path_edges_df(path_question_ids)

    if PLOTLY_AVAILABLE and not graph_nodes_df.empty:
        edge_x = []
        edge_y = []
        for edge in FULL_GRAPH["edges"]:
            source = pos.get(edge["sourceId"])
            target = pos.get(edge["targetId"])
            if source is None or target is None:
                continue
            edge_x.extend([source[0], target[0], None])
            edge_y.extend([source[1], target[1], None])

        all_edge_trace = go.Scatter(
            x=edge_x,
            y=edge_y,
            mode="lines",
            line=dict(width=0.35, color="rgba(120, 138, 160, 0.18)"),
            hoverinfo="skip",
            name="Recommendation edges",
        )

        node_trace = go.Scatter(
            x=graph_nodes_df["x"],
            y=graph_nodes_df["y"],
            mode="markers",
            hoverinfo="text",
            text=graph_nodes_df["hover_text"],
            marker=dict(
                size=np.clip(5 + graph_nodes_df["degree"] * 0.45, 5, 14),
                color=graph_nodes_df["status"].map(STATUS_COLORS).fillna(STATUS_COLORS["unseen"]),
                line=dict(width=np.where(graph_nodes_df["is_live_adaptive_eligible"], 1.2, 0.5), color="#f0f6fc"),
                symbol=graph_nodes_df["difficulty"].map(DIFF_SYMBOL),
                opacity=0.82,
            ),
            name="All questions",
        )

        path_edge_traces = []
        if not path_edges_df.empty:
            for edge_kind, group_df in path_edges_df.groupby("edge_kind", dropna=False):
                path_x = []
                path_y = []
                for item in group_df.itertuples(index=False):
                    source = pos.get(item.sourceId)
                    target = pos.get(item.targetId)
                    if source is None or target is None:
                        continue
                    path_x.extend([source[0], target[0], None])
                    path_y.extend([source[1], target[1], None])
                path_edge_traces.append(
                    go.Scatter(
                        x=path_x,
                        y=path_y,
                        mode="lines",
                        line=dict(width=2.8, color=EDGE_KIND_COLORS.get(edge_kind, "#79c0ff")),
                        hoverinfo="skip",
                        name=f"{path_label}: {edge_kind or 'unknown'}",
                    )
                )

        path_nodes_df = graph_nodes_df[graph_nodes_df["path_step"].notna()].sort_values("path_step")
        path_node_trace = go.Scatter(
            x=path_nodes_df["x"],
            y=path_nodes_df["y"],
            mode="markers+text",
            text=path_nodes_df["path_step"].astype(int).astype(str),
            textposition="top center",
            hoverinfo="text",
            textfont=dict(color="#f0f6fc", size=11),
            marker=dict(
                size=np.where(path_nodes_df["is_current"], 22, 18),
                color=path_nodes_df["status"].map(STATUS_COLORS).fillna("#1f6feb"),
                line=dict(
                    width=np.where(path_nodes_df["is_current"], 3, 2),
                    color=np.where(path_nodes_df["is_current"], "#58a6ff", "#ffffff"),
                ),
                opacity=0.97,
            ),
            name=path_label,
            hovertext=path_nodes_df["hover_text"],
        )

        figure = go.Figure(data=[all_edge_trace, node_trace, *path_edge_traces, path_node_trace])
        figure.update_layout(
            title=title,
            width=1400,
            height=900,
            paper_bgcolor="#0d1117",
            plot_bgcolor="#0d1117",
            font=dict(color="#f0f6fc"),
            hoverlabel=dict(bgcolor="#161b22", font=dict(color="#f0f6fc")),
            xaxis=dict(showgrid=False, zeroline=False, visible=False),
            yaxis=dict(showgrid=False, zeroline=False, visible=False),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
            margin=dict(l=10, r=10, t=60, b=10),
        )
        figure.add_annotation(
            x=0.01,
            y=0.02,
            xref="paper",
            yref="paper",
            xanchor="left",
            yanchor="bottom",
            showarrow=False,
            text=note,
            font=dict(color="#8b949e", size=12),
            bgcolor="rgba(13,17,23,0.7)",
        )
        figure.write_html(output_html, include_plotlyjs="cdn")
        print("Saved interactive student graph to:", output_html)
        figure.show()
        return

    vis_nodes = []
    for row in graph_nodes_df.itertuples(index=False):
        vis_nodes.append(
            {
                "id": row.id,
                "label": str(int(row.path_step)) if pd.notna(row.path_step) else "",
                "title": row.hover_text,
                "x": row.x * 1400,
                "y": row.y * 1400,
                "physics": False,
                "shape": "dot",
                "size": 18 if pd.notna(row.path_step) else max(6, min(14, 5 + row.degree * 0.4)),
                "color": {
                    "background": STATUS_COLORS.get(row.status, "#8b949e"),
                    "border": "#58a6ff" if bool(row.is_current) else "#ffffff",
                },
                "font": {"color": "#f0f6fc", "size": 11},
            }
        )

    vis_edges = []
    for edge in FULL_GRAPH["edges"]:
        vis_edges.append(
            {
                "from": edge["sourceId"],
                "to": edge["targetId"],
                "color": {"color": "rgba(120,138,160,0.18)"},
                "width": 0.6,
                "arrows": "to",
            }
        )
    path_edges_df = build_path_edges_df(path_question_ids)
    for edge in path_edges_df.itertuples(index=False):
        vis_edges.append(
            {
                "from": edge.sourceId,
                "to": edge.targetId,
                "color": {"color": EDGE_KIND_COLORS.get(edge.edge_kind, "#79c0ff")},
                "width": 3.2,
                "arrows": "to",
            }
        )

    container_id = f"student-graph-{uuid.uuid4().hex}"
    html = f'''
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/dist/vis-network.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/vis-network.min.js"></script>
<div style="background:#0d1117;border:1px solid #30363d;border-radius:18px;padding:16px;margin-bottom:16px;">
  <div style="margin-bottom:10px;color:#f0f6fc;font-weight:700;font-size:18px;">{title}</div>
  <div style="margin-bottom:10px;color:#8b949e;font-size:12px;">{note}</div>
  <div id="{container_id}" style="height:860px;border-radius:14px;background:#010409;"></div>
</div>
<script>
(() => {{
  const container = document.getElementById("{container_id}");
  const nodes = new vis.DataSet({json.dumps(vis_nodes)});
  const edges = new vis.DataSet({json.dumps(vis_edges)});
  const network = new vis.Network(container, {{ nodes, edges }}, {{
    physics: false,
    interaction: {{ hover: true, navigationButtons: true, keyboard: true }},
    nodes: {{ borderWidth: 1.2 }},
    edges: {{ smooth: false }},
  }});
  network.fit();
}})();
</script>
'''
    output_html.write_text(html, encoding="utf-8")
    print("Saved interactive student graph to:", output_html)
    display(HTML(html))


selected_graph_available = not selected_test_steps_for_graph_df.empty
live_graph_available = bool(latest_graph_metadata) and len(live_path_details["path_question_ids"]) > 0
if selected_graph_available:
    current_graph_title = f"Selected Website Test Graph: {selected_graph_test_id}"
    current_graph_note = (
        "This graph is built from the selected test_history row's review_payload question path. "
        "Use website_test_id for a unique attempt, or recorded_test_id to pick the latest matching paper attempt."
    )
elif live_graph_available:
    current_graph_title = "Live Website Graph With Connected Student Attempt Path"
    current_graph_note = (
        "This graph is built from the latest graph_path_progress / graph_path_completed activity emitted by the website. "
        "Answered nodes stay green or red, and the active in-progress node stays blue."
    )
else:
    current_graph_title = "Full Question Graph With Student Adaptive Path Overlay"
    current_graph_note = (
        "Live graph activity was not visible, so this graph falls back to the latest reconstructable adaptive session path. "
        "Answered nodes are colored green/red and step numbers show the connected traversal."
    )

current_graph_node_states = dict(latest_outcome_by_question)
current_graph_node_states.update(live_path_details["node_state_map"])
current_graph_nodes_df = build_graph_nodes_df(
    current_graph_node_states,
    live_path_details["path_question_ids"],
    current_question_id=live_path_details["current_question_id"],
)
student_graph_suffix = str(selected_graph_test_id or STUDENT_ID)[:8]
student_graph_html = ROOT / f"student_attempt_graph_{student_graph_suffix}.html"
render_interactive_graph(
    current_graph_nodes_df,
    live_path_details["path_question_ids"],
    current_graph_title,
    current_graph_note,
    student_graph_html,
    "Current connected path",
)

attempt_history_note = (
    "This second graph connects every unique question attempted so far in chronological order across the student's visible website history. "
    "Green means the latest visible outcome is correct, red means wrong."
)
attempt_history_graph_html = ROOT / f"student_attempt_history_graph_{str(STUDENT_ID)[:8]}.html"
attempt_history_nodes_df = build_graph_nodes_df(
    latest_outcome_by_question,
    attempt_history_question_ids,
    current_question_id=None,
)
render_interactive_graph(
    attempt_history_nodes_df,
    attempt_history_question_ids,
    "Cumulative Attempt History Graph",
    attempt_history_note,
    attempt_history_graph_html,
    "All attempted questions",
)

fig = plt.figure(figsize=(22, 18), facecolor="#0d1117")
grid = GridSpec(3, 2, figure=fig, hspace=0.35, wspace=0.2)
panel = "#161b22"
text_c = "#f0f6fc"
grid_c = "#30363d"


def style_ax(ax, title):
    ax.set_facecolor(panel)
    ax.set_title(title, color=text_c, fontsize=13, pad=12)
    ax.tick_params(colors=text_c)
    for spine in ax.spines.values():
        spine.set_color(grid_c)
    ax.grid(color=grid_c, alpha=0.35, linestyle="--", linewidth=0.6)
    ax.set_axisbelow(True)



fig.suptitle("Student Account, Performance, and Recommendation Replay Dashboard", color=text_c, fontsize=18)
plt.show()

Saved interactive student graph to: c:\Users\sunil\Downloads\btech-project\student_attempt_graph_b362dfde.html

Saved interactive student graph to: c:\Users\sunil\Downloads\btech-project\student_attempt_history_graph_12efa469.html

In [11]:
# ============================================================
# 7. INTERACTIVE RECORDED TEST GRAPH FOR SELECTED TEST
# ============================================================

import json, uuid
from pathlib import Path
from IPython.display import display, HTML

# ── Colour / symbol maps (same as Cell 6) ──────────────────────────────────
STATUS_COLORS_SIM = {
    "correct":  "#3fb950",
    "wrong":    "#f85149",
    "future":   "#388bfd",
    "current":  "#58a6ff",
    "unseen":   "#484f58",
}
DIFF_SYMBOL_SIM = {"easy": "circle", "medium": "diamond", "hard": "square"}
EDGE_KIND_COLORS_SIM = {
    "prerequisite": "#58a6ff",
    "related":      "#3fb950",
    "remediation":  "#f0883e",
    "co-requisite": "#bc8cff",
}

if simulation_steps_df.empty:
    print('Selected recorded test has no visible per-question path. Skipping recorded-test graph; no generated fallback path will be used.')
else:
    # ── Build per-question state from the selected recorded test path ──────────────────────
    sim_node_state_map   = {}   # questionId → "correct" | "wrong"
    sim_path_step_map    = {}   # questionId → step_number  (last session only)
    sim_path_order       = []   # ordered list of question_ids for selected session

    if not simulation_steps_df.empty:
        for row in simulation_steps_df.sort_values("step_number").itertuples(index=False):
            qid = getattr(row, "actual_question_id", None)
            if not qid:
                continue
            correct = getattr(row, "correct", None)
            sim_node_state_map[qid]  = "correct" if correct else "wrong"
            sim_path_step_map[qid]   = int(getattr(row, "step_number", 0))
            sim_path_order.append(qid)

    # Future forecast question ids
    future_qids     = []
    future_step_map = {}   # questionId → forecast_step label ("F1", "F2", …)
    if not future_recommendations_df.empty and "question_id" in future_recommendations_df.columns:
        for row in future_recommendations_df.itertuples(index=False):
            qid = getattr(row, "question_id", None)
            if qid:
                future_qids.append(qid)
                future_step_map[qid] = f"F{int(getattr(row, 'forecast_step', len(future_qids)))}"
                if qid not in sim_node_state_map:
                    sim_node_state_map[qid] = "future"

    all_path_order = sim_path_order + future_qids   # for drawing dashed future edges

    # ── Helper: build hover text for a bank row ──────────────────────────────────
    def build_sim_hover(row, sim_node_state_map, sim_path_step_map, future_step_map,
                        simulation_steps_df, future_recommendations_df):
        qid    = row["id"]
        status = sim_node_state_map.get(qid, "unseen")
        lines  = [
            f"<b>{qid}</b>",
            f"Subject: {row.get('subjectName','—')}",
            f"Topic:   {row.get('topicName','—')}",
            f"Difficulty: {row.get('difficulty','—')}",
            f"ELO: {row.get('eloRating', '—')}",
            f"Type: {row.get('type','—')}  Marks: {row.get('marks','—')}",
            f"Status: {status}",
            f"Live adaptive eligible: {row.get('is_live_adaptive_eligible', False)}",
        ]

        # Session-step details
        if qid in sim_path_step_map and not simulation_steps_df.empty:
            step_rows = simulation_steps_df[
                simulation_steps_df["actual_question_id"] == qid
            ]
            if not step_rows.empty:
                sr = step_rows.iloc[0]
                lines.insert(1, f"Path step: {sr.get('step_number','—')}")
                lines += [
                    f"Correct: {'✓' if sr.get('correct') else '✗'}",
                    f"Time spent: {sr.get('time_spent_seconds','—')}s",
                    f"Rapid guess: {'⚡ yes' if sr.get('rapid_guess_warning') else 'no'}",
                    f"ELO before: {sr.get('student_elo_before_step','—')}",
                    f"ELO adjustment: {sr.get('elo_adjustment','—')}",
                    f"Target ELO: {sr.get('target_elo','—')}",
                    f"Momentum: {sr.get('momentum','—')}",
                    f"Graph mode: {sr.get('graph_mode','—')}",
                    f"Graph edge: {sr.get('graph_edge_kind','—')} (w={sr.get('graph_edge_weight','—')})",
                    f"Remediation for: {sr.get('remediation_for_question_id','—')}",
                    f"Reasons: {sr.get('reasons','—')}",
                ]

        # Future-step details
        if qid in future_step_map and not future_recommendations_df.empty:
            fr_rows = future_recommendations_df[
                future_recommendations_df["question_id"] == qid
            ]
            if not fr_rows.empty:
                fr = fr_rows.iloc[0]
                lines.insert(1, f"Forecast step: {future_step_map[qid]}")
                lines += [
                    f"Target ELO: {fr.get('target_elo','—')}",
                    f"Target difficulty: {fr.get('target_difficulty','—')}",
                    f"Momentum: {fr.get('momentum','—')}",
                    f"Graph mode: {fr.get('graph_mode','—')}",
                    f"Graph edge: {fr.get('graph_edge_kind','—')}",
                    f"Hop distance: {fr.get('graph_hop_distance','—')}",
                    f"Reasons: {fr.get('reasons','—')}",
                ]

        return "<br>".join(lines)


    # ── Build annotated nodes DataFrame ─────────────────────────────────────────
    if "id" not in simulation_bank_df.columns:
        print("simulation_bank_df has no 'id' column — cannot build recorded test graph.")
    else:
        sim_graph_rows = []
        for q in simulation_bank_df.to_dict("records"):
            qid    = q["id"]
            x, y   = pos.get(qid, (0, 0))
            status = sim_node_state_map.get(qid, "unseen")
            pstep  = sim_path_step_map.get(qid, None)
            fstep  = future_step_map.get(qid, None)
            sim_graph_rows.append({
                "id":                    qid,
                "x":                     float(x),
                "y":                     float(y),
                "subjectId":             q.get("subjectId"),
                "subjectName":           q.get("subjectName"),
                "topicId":               q.get("topicId"),
                "topicName":             q.get("topicName"),
                "difficulty":            q.get("difficulty"),
                "eloRating":             float(q.get("eloRating", 1400) or 1400),
                "marks":                 float(q.get("marks", 1) or 1),
                "type":                  q.get("type"),
                "is_live_adaptive_eligible": bool(q.get("is_live_adaptive_eligible")),
                "status":                status,
                "path_step":             pstep,
                "future_step":           fstep,
                "is_current":            False,
                "hover_text":            build_sim_hover(
                                             q, sim_node_state_map, sim_path_step_map,
                                             future_step_map, simulation_steps_df,
                                             future_recommendations_df
                                         ),
            })

        sim_graph_nodes_df = pd.DataFrame(sim_graph_rows)

        # ── Path-edges helper ────────────────────────────────────────────────────
        def build_sim_path_edges(path_ids):
            rows = []
            for i in range(1, len(path_ids)):
                left, right = path_ids[i - 1], path_ids[i]
                edge = (
                    get_question_graph_edge(left, right, FULL_GRAPH)
                    or get_question_graph_edge(right, left, FULL_GRAPH)
                )
                rows.append({
                    "sourceId":  left,
                    "targetId":  right,
                    "edge_kind": edge.get("kind")   if edge else None,
                    "edge_weight": edge.get("weight") if edge else None,
                })
            return pd.DataFrame(rows) if rows else pd.DataFrame(
                columns=["sourceId", "targetId", "edge_kind", "edge_weight"]
            )

        sim_path_edges_df   = build_sim_path_edges(sim_path_order)
        future_path_edges_df = build_sim_path_edges(all_path_order)  # includes future hops

        # ── Summary stats for title annotation ──────────────────────────────────
        selected_session_label = selected_session_id or "recorded-test"
        sim_acc_pct = (
            round(100 * simulation_steps_df["correct"].fillna(False).mean(), 1)
            if not simulation_steps_df.empty else float("nan")
        )
        n_steps = len(simulation_steps_df)

        graph_title  = (
            f"Recorded Test Adaptive Path Graph — session: {selected_session_label} | "
            f"steps: {n_steps} | accuracy: {sim_acc_pct}%"
        )
        graph_note = (
            "Numbered nodes = adaptive path (green=correct, red=wrong). "
            "F-numbered nodes = future recommendations. "
            "Blue solid edges = session path. Blue dashed edges = forecast path. "
            "Faint edges = full recommendation graph."
        )

        # ── Plotly branch ────────────────────────────────────────────────────────
        if PLOTLY_AVAILABLE and not sim_graph_nodes_df.empty:

            # All background edges
            edge_x, edge_y = [], []
            for edge in FULL_GRAPH["edges"]:
                src = pos.get(edge["sourceId"])
                tgt = pos.get(edge["targetId"])
                if src is None or tgt is None:
                    continue
                edge_x.extend([src[0], tgt[0], None])
                edge_y.extend([src[1], tgt[1], None])

            all_edge_trace = go.Scatter(
                x=edge_x, y=edge_y,
                mode="lines",
                line=dict(width=0.35, color="rgba(120,138,160,0.15)"),
                hoverinfo="skip",
                name="Recommendation graph edges",
            )

            # All question nodes
            node_colors = sim_graph_nodes_df["status"].map(STATUS_COLORS_SIM).fillna(STATUS_COLORS_SIM["unseen"])
            node_trace = go.Scatter(
                x=sim_graph_nodes_df["x"],
                y=sim_graph_nodes_df["y"],
                mode="markers",
                hoverinfo="text",
                text=sim_graph_nodes_df["hover_text"],
                marker=dict(
                    size=np.clip(
                        5 + sim_graph_nodes_df["eloRating"].fillna(1400).apply(
                            lambda e: max(0, (e - 1100) / 100)
                        ) * 0.6,
                        5, 14
                    ),
                    color=node_colors,
                    line=dict(
                        width=np.where(sim_graph_nodes_df["is_live_adaptive_eligible"], 1.2, 0.4),
                        color="#f0f6fc",
                    ),
                    symbol=sim_graph_nodes_df["difficulty"].map(DIFF_SYMBOL_SIM).fillna("circle"),
                    opacity=0.78,
                ),
                name="All questions",
            )

            # Session path edges — grouped by edge kind
            path_edge_traces = []
            if not sim_path_edges_df.empty:
                for edge_kind, grp in sim_path_edges_df.groupby("edge_kind", dropna=False):
                    px_, py_ = [], []
                    for item in grp.itertuples(index=False):
                        src = pos.get(item.sourceId)
                        tgt = pos.get(item.targetId)
                        if src is None or tgt is None:
                            continue
                        px_.extend([src[0], tgt[0], None])
                        py_.extend([src[1], tgt[1], None])
                    path_edge_traces.append(go.Scatter(
                        x=px_, y=py_,
                        mode="lines",
                        line=dict(
                            width=2.6,
                            color=EDGE_KIND_COLORS_SIM.get(str(edge_kind), "#79c0ff"),
                        ),
                        hoverinfo="skip",
                        name=f"Session path: {edge_kind or 'unknown'}",
                    ))

            # Future path edges (dashed)
            future_edge_traces = []
            if not future_path_edges_df.empty:
                future_only_edges = future_path_edges_df[
                    future_path_edges_df["sourceId"].isin(future_qids)
                    | future_path_edges_df["targetId"].isin(future_qids)
                ]
                if not future_only_edges.empty:
                    fpx, fpy = [], []
                    for item in future_only_edges.itertuples(index=False):
                        src = pos.get(item.sourceId)
                        tgt = pos.get(item.targetId)
                        if src is None or tgt is None:
                            continue
                        fpx.extend([src[0], tgt[0], None])
                        fpy.extend([src[1], tgt[1], None])
                    future_edge_traces.append(go.Scatter(
                        x=fpx, y=fpy,
                        mode="lines",
                        line=dict(width=1.8, color="#388bfd", dash="dot"),
                        hoverinfo="skip",
                        name="Future forecast edges",
                    ))

            # Numbered path nodes (session)
            path_nodes_df = sim_graph_nodes_df[sim_graph_nodes_df["path_step"].notna()].copy()
            path_nodes_df = path_nodes_df.sort_values("path_step")

            path_node_trace = go.Scatter(
                x=path_nodes_df["x"],
                y=path_nodes_df["y"],
                mode="markers+text",
                text=path_nodes_df["path_step"].astype(int).astype(str),
                textposition="top center",
                textfont=dict(color="#f0f6fc", size=11),
                hoverinfo="text",
                hovertext=path_nodes_df["hover_text"],
                marker=dict(
                    size=20,
                    color=path_nodes_df["status"].map(STATUS_COLORS_SIM).fillna("#1f6feb"),
                    line=dict(width=2, color="#ffffff"),
                    opacity=0.97,
                ),
                name="Session adaptive path",
            )

            # F-numbered future nodes
            future_nodes_df = sim_graph_nodes_df[sim_graph_nodes_df["future_step"].notna()].copy()
            # FIXED — dash removed from marker.line
            future_node_trace = go.Scatter(
                x=future_nodes_df["x"],
                y=future_nodes_df["y"],
                mode="markers+text",
                text=future_nodes_df["future_step"].astype(str),
                textposition="top center",
                textfont=dict(color="#c9d1d9", size=10),
                hoverinfo="text",
                hovertext=future_nodes_df["hover_text"],
                marker=dict(
                    size=16,
                    color=STATUS_COLORS_SIM["future"],
                    line=dict(width=1.6, color="#79c0ff"),   # ← dash removed
                    symbol="diamond",
                    opacity=0.92,
                ),
                name="Future recommendations",
            )
        

            fig = go.Figure(data=[
                all_edge_trace,
                node_trace,
                *path_edge_traces,
                *future_edge_traces,
                path_node_trace,
                future_node_trace,
            ])

            fig.update_layout(
                title=graph_title,
                width=1400,
                height=920,
                paper_bgcolor="#0d1117",
                plot_bgcolor="#0d1117",
                font=dict(color="#f0f6fc"),
                hoverlabel=dict(bgcolor="#161b22", font=dict(color="#f0f6fc")),
                xaxis=dict(showgrid=False, zeroline=False, visible=False),
                yaxis=dict(showgrid=False, zeroline=False, visible=False),
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
                margin=dict(l=10, r=10, t=70, b=10),
            )
            fig.add_annotation(
                x=0.01, y=0.02, xref="paper", yref="paper",
                xanchor="left", yanchor="bottom", showarrow=False,
                text=graph_note,
                font=dict(color="#8b949e", size=11),
                bgcolor="rgba(13,17,23,0.75)",
            )

            # --- Candidate ranking table below the graph ---
            if not simulation_candidates_df.empty:
                top_candidates = simulation_candidates_df.sort_values(
                    ["step_number", "rank"]
                ).head(80)
                fig.add_annotation(
                    x=0.99, y=0.02, xref="paper", yref="paper",
                    xanchor="right", yanchor="bottom", showarrow=False,
                    text=(
                        f"Top candidates shown: {len(top_candidates)} rows across "
                        f"{simulation_candidates_df['step_number'].nunique()} steps"
                    ),
                    font=dict(color="#8b949e", size=11),
                    bgcolor="rgba(13,17,23,0.75)",
                )

            sim_graph_html_path = ROOT / f"recorded_test_graph_{str(selected_session_label)[:8]}.html"
            fig.write_html(sim_graph_html_path, include_plotlyjs="cdn")
            print("Saved recorded test graph →", sim_graph_html_path)
            fig.show()

        # ── vis-network fallback (no Plotly) ────────────────────────────────────
        else:
            vis_nodes = []
            for row in sim_graph_nodes_df.itertuples(index=False):
                is_path   = pd.notna(row.path_step)
                is_future = pd.notna(row.future_step)
                vis_nodes.append({
                    "id":    row.id,
                    "label": (str(int(row.path_step)) if is_path
                              else row.future_step     if is_future
                              else ""),
                    "title": row.hover_text,
                    "x":     row.x * 1400,
                    "y":     row.y * 1400,
                    "physics": False,
                    "shape": "dot",
                    "size":  (20 if is_path else 16 if is_future
                              else max(6, min(13, 5 + int(max(0, (row.eloRating - 1100) / 100) * 0.6)))),
                    "color": {
                        "background": STATUS_COLORS_SIM.get(row.status, "#484f58"),
                        "border":     "#79c0ff" if is_path else "#388bfd" if is_future else "#30363d",
                    },
                    "borderWidth": 2.2 if is_path else 1.6 if is_future else 0.5,
                    "font": {"color": "#f0f6fc", "size": 11},
                })

            vis_edges = []
            # Background graph edges (faint)
            for edge in FULL_GRAPH["edges"]:
                vis_edges.append({
                    "from":  edge["sourceId"],
                    "to":    edge["targetId"],
                    "color": {"color": "rgba(120,138,160,0.12)", "opacity": 0.12},
                    "width": 0.5,
                    "arrows": "",
                })
            # Session path edges
            for edge in sim_path_edges_df.itertuples(index=False):
                vis_edges.append({
                    "from":  edge.sourceId,
                    "to":    edge.targetId,
                    "color": {"color": EDGE_KIND_COLORS_SIM.get(edge.edge_kind, "#79c0ff")},
                    "width": 3.0,
                    "arrows": "to",
                })
            # Future path edges (dashed)
            if not future_path_edges_df.empty:
                for edge in future_path_edges_df[
                    future_path_edges_df["sourceId"].isin(future_qids)
                    | future_path_edges_df["targetId"].isin(future_qids)
                ].itertuples(index=False):
                    vis_edges.append({
                        "from":  edge.sourceId,
                        "to":    edge.targetId,
                        "color": {"color": "#388bfd"},
                        "width": 2.0,
                        "dashes": True,
                        "arrows": "to",
                    })

            container_id = f"sim-graph-{uuid.uuid4().hex[:8]}"
            html_fallback = f"""
    <link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/dist/vis-network.min.css"/>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/vis-network.min.js">
    </script>
    <div style="background:#0d1117;border:1px solid #30363d;border-radius:18px;
                padding:16px;margin-bottom:16px;">
      <div style="margin-bottom:6px;color:#f0f6fc;font-weight:700;font-size:17px;">
        {graph_title}
      </div>
      <div style="margin-bottom:10px;color:#8b949e;font-size:12px;">{graph_note}</div>
      <div id="{container_id}"
           style="height:880px;border-radius:14px;background:#010409;"></div>
    </div>
    <script>
    (function(){{
      const nodes = new vis.DataSet({json.dumps(vis_nodes)});
      const edges = new vis.DataSet({json.dumps(vis_edges)});
      const container = document.getElementById("{container_id}");
      new vis.Network(container, {{nodes, edges}}, {{
        physics: false,
        interaction: {{hover:true, navigationButtons:true, keyboard:true}},
        nodes: {{borderWidth:1}},
        edges: {{smooth:false}},
      }});
    }})();
    </script>
    """
            sim_graph_html_path = ROOT / f"recorded_test_graph_{str(selected_session_label)[:8]}.html"
            sim_graph_html_path.write_text(html_fallback, encoding="utf-8")
            print("Saved recorded test graph (vis-network fallback) →", sim_graph_html_path)
            display(HTML(html_fallback))

        # ── Recorded Test steps detail table ────────────────────────────────────────
        print("\n── Recorded Test Steps (selected session) ──")
        display(simulation_steps_df)

        print("\n── Top Candidates per Step (up to 80 rows) ──")
        display(
            simulation_candidates_df.sort_values(["step_number", "rank"]).head(80)
            if not simulation_candidates_df.empty
            else pd.DataFrame()
        )

        print("\n── Future Recommendations ──")
        display(future_recommendations_df)

        print("\n── Recorded Test Summary ──")
        display(simulation_summary_df)

Saved recorded test graph → c:\Users\sunil\Downloads\btech-project\recorded_test_graph_b362dfde.html

── Recorded Test Steps (selected session) ──

,test_id,completed_at,step_number,student_elo_before_step,actual_question_id,actual_question_text,actual_subject,actual_topic,actual_difficulty,actual_question_elo,...,momentum,reward_signal,graph_mode,graph_from_question_id,graph_edge_kind,graph_edge_weight,graph_hop_distance,graph_neighbor_count,remediation_for_question_id,reasons
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,1,1600.0,co-44,Changing order of integration requires?,Calculus & Optimization,Integration,hard,1500.0,...,steady,0.00,seed,None,None,NaN,NaN,0,None,Targets your current level around ELO 1600 wit...
1,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,2,1600.0,co-56,If Hessian is positive definite then?,Calculus & Optimization,Optimization,hard,1500.0,...,steady,0.91,neighbor,co-44,same-topic,0.9789,2.0,33,None,Targets your current level around ELO 1657 wit...
2,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,3,1600.0,co-53,A function is convex if?,Calculus & Optimization,Optimization,medium,1400.0,...,steady,1.82,neighbor,co-56,same-topic,0.9789,2.0,30,None,Targets your current level around ELO 1679 wit...
3,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,4,1600.0,co-49,Update rule in gradient descent is?,Calculus & Optimization,Optimization,medium,1400.0,...,steady,0.82,remediation,co-53,same-topic,0.9844,3.0,29,co-53,Targets your current level around ELO 1560 wit...
4,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,5,1600.0,co-6,"In gradient descent, a very high learning rate...",Calculus & Optimization,Optimization,medium,1400.0,...,cold,-0.18,remediation,co-49,subject-flow,0.6789,3.0,29,co-49,Targets your current level around ELO 1446 wit...
5,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,6,1600.0,co-40,Integration by parts formula is?,Calculus & Optimization,Integration,medium,1400.0,...,steady,-0.28,remediation,co-6,same-topic,0.9789,2.0,29,co-49,Targets your current level around ELO 1628 wit...
6,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,7,1600.0,co-45,The integral ∫_0^∞ e^-x dx equals?,Calculus & Optimization,Integration,medium,1400.0,...,cold,-2.19,remediation,co-40,same-topic,0.9789,2.0,33,co-40,Targets your current level around ELO 1397 wit...
7,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,8,1600.0,co-33,Fundamental theorem of calculus connects?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-45,same-topic,0.9789,2.0,33,co-45,Targets your current level around ELO 1397 wit...
8,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,9,1600.0,co-37,The integral ∫_0^π sin x dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-33,subject-flow,0.4216,1.0,25,co-33,Targets your current level around ELO 1397 wit...
9,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,10,1600.0,co-38,If f(x) is odd then ∫_-a^a f(x)dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,cold,-2.19,remediation,co-37,same-topic,0.9789,2.0,25,co-33,Targets your current level around ELO 1492 wit...
10,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,11,1600.0,co-39,If f(x) is even then ∫_-a^a f(x)dx equals?,Calculus & Optimization,Integration,medium,1350.0,...,steady,-0.38,remediation,co-38,same-topic,0.9844,3.0,25,co-33,Targets your current level around ELO 1626 wit...
11,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,12,1600.0,mock2-q8,Consider the series ∑_{n=1}^∞ 1/n(n+1). Which ...,Calculus & Optimization,Integration,medium,1450.0,...,hot,1.43,retry,co-39,same-topic,0.9789,0.0,0,co-33,Targets your current level around ELO 1744 wit...
12,b362dfde-97c4-4e67-95cf-4b99cae00c20,2026-05-13 05:11:08.970000+00:00,13,1600.0,mock3-q8,Consider the series ∑_{n=2}^∞ 1/(n ln n). Whic...,Calculus & Optimization,Integration,medium,1450.0,...,steady,1.43,remediation,mock2-q8,same-topic,0.9407,1.0,33,None,Targets your current level around ELO 1574 wit...

── Top Candidates per Step (up to 80 rows) ──

,test_id,step_number,rank,candidate_question_id,candidate_subject,candidate_topic,candidate_difficulty,candidate_elo,heuristic_score,graph_boost,combined_score,graph_edge_kind,graph_edge_weight,hop_distance,selected
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,1,mock4-q40,machine-learning,ml-evaluation,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,True
1,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,2,mock4-q43,machine-learning,ml-supervised,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
2,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,3,mock4-q44,linear-algebra,la-matrices,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
3,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,4,mock4-q48,machine-learning,ml-supervised,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
4,b362dfde-97c4-4e67-95cf-4b99cae00c20,1,5,mock4-q50,probability-statistics,ps-probability,hard,1600.0,139.0000,0.0000,139.0000,None,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,b362dfde-97c4-4e67-95cf-4b99cae00c20,11,7,da2026-q39,calculus-optimization,co-differentiation,medium,1400.0,115.1667,13.7046,128.8713,same-topic,0.9789,3.0,False
76,b362dfde-97c4-4e67-95cf-4b99cae00c20,11,8,da2025-q57,dbms,dbms-normalization,medium,1400.0,120.1667,5.9696,126.1363,subject-flow,0.4264,3.0,False
77,b362dfde-97c4-4e67-95cf-4b99cae00c20,12,1,co-33,calculus-optimization,co-integration,medium,1350.0,103.3095,13.7046,117.0141,same-topic,0.9789,0.0,True
78,b362dfde-97c4-4e67-95cf-4b99cae00c20,13,1,co-41,calculus-optimization,co-integration,hard,1500.0,169.8333,13.1698,183.0031,same-topic,0.9407,1.0,True
79,b362dfde-97c4-4e67-95cf-4b99cae00c20,13,2,mock2-q50,calculus-optimization,co-differentiation,medium,1450.0,130.6667,9.5046,140.1713,subject-flow,0.6789,1.0,False

── Future Recommendations ──

,forecast_step,question_id,subject,topic,difficulty,question_elo,target_elo,target_difficulty,momentum,graph_mode,graph_edge_kind,graph_hop_distance,reasons
0,1,co-41,Calculus & Optimization,Integration,hard,1500.0,1441,medium,cold,remediation,same-topic,1,Targets your current level around ELO 1441 wit...
1,2,co-51,Calculus & Optimization,Optimization,hard,1500.0,1655,hard,steady,remediation,subject-flow,2,Targets your current level around ELO 1655 wit...
2,3,co-62,Calculus & Optimization,Optimization,hard,1500.0,1682,hard,steady,remediation,same-topic,3,Targets your current level around ELO 1682 wit...
3,4,mock3-q8,Calculus & Optimization,Integration,medium,1450.0,1800,hard,hot,retry,None,0,Targets your current level around ELO 1800 wit...
4,5,ai-1,Artificial Intelligence,Search Algorithms,hard,1410.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...
5,6,co-15,Calculus & Optimization,Differentiation,medium,1350.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...
6,7,ai-3,Artificial Intelligence,Propositional & Predicate Logic,hard,1410.0,1800,hard,hot,neighbor,subject-flow,3,Targets your current level around ELO 1800 wit...
7,8,co-16,Calculus & Optimization,Differentiation,medium,1350.0,1800,hard,hot,neighbor,same-topic,3,Targets your current level around ELO 1800 wit...

── Recorded Test Summary ──

,selected_session_id,simulation_bank_mode,simulation_start_elo,session_steps,recommended_matches_actual_pct,session_accuracy_pct
0,b362dfde-97c4-4e67-95cf-4b99cae00c20,complete,1600,13,0.0,46.15

In [12]:
# ============================================================
# 7. SIMULATION GRAPH → MP4 VIDEO (step-by-step reveal)
# ============================================================
# Requires: matplotlib, networkx, numpy  (already imported)
# ffmpeg must be available: pip install ffmpeg-python  OR  conda install ffmpeg
#
# What the video shows
# ────────────────────
# Frame 0          : full question-bank graph, all nodes grey/unseen
# Frames 1…N       : each adaptive step revealed one at a time
#                    – node colour flips to green (correct) or red (wrong)
#                    – path edge drawn between previous → current node
#                    – animated "pulse" ring appears on the active node
#                    – sidebar panel updates with step metadata
# Frames N+1…N+F   : future-forecast nodes revealed (blue diamond, dashed edge)
# Final hold frame : complete picture held for 2 s
#
# Output: ROOT / recorded_test_graph_{selected_session_id[:8]}.mp4
# ============================================================

import math
import textwrap
import warnings
import matplotlib
matplotlib.use("Agg")                          # must be before pyplot import
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
from matplotlib.animation import FFMpegWriter, FuncAnimation
from matplotlib.lines import Line2D
import matplotlib.colors as mcolors
import numpy as np

warnings.filterwarnings("ignore", category=UserWarning)

# ── 0. Constants ─────────────────────────────────────────────────────────────
FPS          = 24          # frames per second
STEP_HOLD    = FPS * 2     # frames each adaptive step is held (2 s)
PULSE_FRAMES = FPS         # frames for the pulse animation per step
FUTURE_HOLD  = FPS * 1     # frames each future-step is held (1 s)
FINAL_HOLD   = FPS * 3     # final hold (3 s)

VIDEO_DPI    = 120
FIG_W, FIG_H = 20, 11      # inches

STATUS_COLOR = {
    "correct": "#3fb950",
    "wrong":   "#f85149",
    "future":  "#388bfd",
    "unseen":  "#484f58",
}
EDGE_COLOR = {
    "prerequisite": "#58a6ff",
    "related":      "#3fb950",
    "remediation":  "#f0883e",
    None:           "#79c0ff",
}
BG      = "#0d1117"
PANEL   = "#161b22"
TEXT_C  = "#f0f6fc"
GRID_C  = "#30363d"
FAINT   = (0.47, 0.54, 0.63, 0.12)   # rgba for background edges

# ── 1. Validate inputs from Cell 5 ───────────────────────────────────────────
if simulation_steps_df.empty:
    print('Selected recorded test has no visible per-question path. Skipping recorded-test video; no generated fallback path will be used.')
else:
    # ── 2. Build ordered step list from simulation_steps_df ──────────────────────
    step_records = []
    for row in simulation_steps_df.sort_values("step_number").itertuples(index=False):
        qid = getattr(row, "actual_question_id", None)
        if not qid:
            continue
        step_records.append({
            "step":        int(getattr(row, "step_number", 0)),
            "qid":         qid,
            "correct":     bool(getattr(row, "correct", False)),
            "answered":    bool(getattr(row, "answered", True)),
            "subject":     getattr(row, "actual_subject", "—"),
            "topic":       getattr(row, "actual_topic", "—"),
            "difficulty":  getattr(row, "actual_difficulty", "—"),
            "q_elo":       getattr(row, "actual_question_elo", 1400),
            "elo_before":  getattr(row, "student_elo_before_step", 1500),
            "elo_adj":     getattr(row, "elo_adjustment", 0),
            "time_s":      getattr(row, "time_spent_seconds", 0),
            "rapid":       bool(getattr(row, "rapid_guess_warning", False)),
            "graph_mode":  getattr(row, "graph_mode", "—"),
            "edge_kind":   getattr(row, "graph_edge_kind", None),
            "momentum":    getattr(row, "momentum", "—"),
            "reasons":     getattr(row, "reasons", ""),
            "remediation": getattr(row, "remediation_for_question_id", None),
        })

    # Future forecast steps
    future_records = []
    if not future_recommendations_df.empty and "question_id" in future_recommendations_df.columns:
        for row in future_recommendations_df.itertuples(index=False):
            qid = getattr(row, "question_id", None)
            if not qid:
                continue
            future_records.append({
                "step":       f"F{int(getattr(row, 'forecast_step', 0))}",
                "qid":        qid,
                "subject":    getattr(row, "subject", "—"),
                "topic":      getattr(row, "topic", "—"),
                "difficulty": getattr(row, "difficulty", "—"),
                "q_elo":      getattr(row, "question_elo", 1400),
                "target_elo": getattr(row, "target_elo", "—"),
                "momentum":   getattr(row, "momentum", "—"),
                "graph_mode": getattr(row, "graph_mode", "—"),
                "edge_kind":  getattr(row, "graph_edge_kind", None),
                "reasons":    getattr(row, "reasons", ""),
            })

    # ── 3. Build node/edge arrays for drawing ────────────────────────────────────
    all_node_ids = [q["id"] for q in question_bank_full.to_dict("records")]
    node_xy      = {nid: pos.get(nid, (0.0, 0.0)) for nid in all_node_ids}

    # Pre-compute edge arrays for the faint background graph
    bg_edge_segs = []
    # FIXED — use `is not None` instead of truthiness check, cast to float:
    for edge in FULL_GRAPH["edges"]:
        s = node_xy.get(edge["sourceId"])
        t = node_xy.get(edge["targetId"])
        if s is not None and t is not None:
            bg_edge_segs.append(([float(s[0]), float(t[0])], [float(s[1]), float(t[1])]))

    # ── 4. Layout figure ─────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(FIG_W, FIG_H), facecolor=BG)
    fig.subplots_adjust(left=0.0, right=0.72, top=0.95, bottom=0.03)

    ax_graph = fig.add_axes([0.0, 0.03, 0.70, 0.92])   # main graph
    ax_graph.set_facecolor(BG)
    ax_graph.set_xticks([]); ax_graph.set_yticks([])
    for spine in ax_graph.spines.values():
        spine.set_visible(False)

    ax_info = fig.add_axes([0.71, 0.03, 0.28, 0.92])    # sidebar
    ax_info.set_facecolor(PANEL)
    ax_info.set_xticks([]); ax_info.set_yticks([])
    for spine in ax_info.spines.values():
        spine.set_color(GRID_C)

    # ── 5. Draw static background (edges + unseen nodes) ─────────────────────────
    # Background edges
    for xs, ys in bg_edge_segs:
        ax_graph.plot(xs, ys, color=FAINT, lw=0.4, zorder=1)

    # Draw all nodes as unseen first (we'll update colours per-frame)
    xs_all = [node_xy[nid][0] for nid in all_node_ids]
    ys_all = [node_xy[nid][1] for nid in all_node_ids]

    node_scatter = ax_graph.scatter(
        xs_all, ys_all,
        s=28, c=[STATUS_COLOR["unseen"]] * len(all_node_ids),
        zorder=3, linewidths=0.4, edgecolors="#f0f6fc",
        alpha=0.75,
    )

    # Title
    title_text = ax_graph.text(
        0.5, 0.995,
        f"Recorded Test Replay - session: {selected_session_id or 'recorded-test'}",
        transform=ax_graph.transAxes,
        ha="center", va="top",
        color=TEXT_C, fontsize=13, fontweight="bold",
    )

    # Step counter
    step_label = ax_graph.text(
        0.01, 0.995, "Step: —",
        transform=ax_graph.transAxes,
        ha="left", va="top",
        color="#8b949e", fontsize=10,
    )

    # Legend
    legend_handles = [
        mpatches.Patch(color=STATUS_COLOR["correct"], label="Correct"),
        mpatches.Patch(color=STATUS_COLOR["wrong"],   label="Wrong"),
        mpatches.Patch(color=STATUS_COLOR["future"],  label="Future rec."),
        mpatches.Patch(color=STATUS_COLOR["unseen"],  label="Unseen"),
        Line2D([0], [0], color="#79c0ff", lw=2, label="Adaptive path edge"),
        Line2D([0], [0], color="#388bfd", lw=1.5, linestyle="--", label="Forecast edge"),
    ]
    ax_graph.legend(
        handles=legend_handles,
        loc="lower left", fontsize=8,
        facecolor=PANEL, edgecolor=GRID_C,
        labelcolor=TEXT_C, framealpha=0.9,
    )

    # ── 6. Mutable drawing state ──────────────────────────────────────────────────
    node_colors   = {nid: STATUS_COLOR["unseen"] for nid in all_node_ids}
    path_lines    = []          # list of Line2D for session path edges
    future_lines  = []          # list of Line2D for future path edges
    step_labels   = []          # list of Text objects (step numbers on nodes)
    pulse_artists = []          # temp pulse ring

    prev_qid = None             # last session qid (for drawing edges)
    prev_future_qid = None      # last future qid

    def _update_scatter():
        colors = [node_colors[nid] for nid in all_node_ids]
        node_scatter.set_facecolor(colors)

    def _add_path_edge(src_qid, tgt_qid, color, lw, linestyle="-"):
        _s = node_xy.get(src_qid, (0.0, 0.0))
        _t = node_xy.get(tgt_qid, (0.0, 0.0))
        sx, sy = float(_s[0]), float(_s[1])
        tx, ty = float(_t[0]), float(_t[1])
        line, = ax_graph.plot(
            [sx, tx], [sy, ty],
            color=color, lw=lw, linestyle=linestyle,
            zorder=2, solid_capstyle="round",
        )
        return line

    def _add_step_label(qid, label, color):
        _p = node_xy.get(qid, (0.0, 0.0))
        x, y = float(_p[0]), float(_p[1])
        txt = ax_graph.text(
            x, y, str(label),
            ha="center", va="center",
            color="#f0f6fc", fontsize=7, fontweight="bold",
            zorder=6,
            path_effects=[pe.withStroke(linewidth=2, foreground=BG)],
        )
        return txt

    def _draw_pulse(qid, radius_frac):
        """Draw expanding circle ring around node."""
        for a in pulse_artists:
            a.remove()
        pulse_artists.clear()
        _p = node_xy.get(qid, (0.0, 0.0))
        x, y = float(_p[0]), float(_p[1])
        # radius_frac: 0.0 → 1.0 controlling ring size
        r = 0.008 + 0.022 * radius_frac
        circ = mpatches.Circle(
            (x, y), r,
            fill=False,
            edgecolor="#f0f6fc",
            linewidth=1.5,
            alpha=max(0, 1.0 - radius_frac),
            zorder=7,
            transform=ax_graph.transData,
        )
        ax_graph.add_patch(circ)
        pulse_artists.append(circ)

    def _render_sidebar(rec, is_future=False):
        ax_info.cla()
        ax_info.set_facecolor(PANEL)
        ax_info.set_xticks([]); ax_info.set_yticks([])
        for spine in ax_info.spines.values():
            spine.set_color(GRID_C)

        y = 0.97
        dy = 0.055

        def _line(label, value, color=TEXT_C, bold=False):
            nonlocal y
            ax_info.text(0.05, y, label,
                         transform=ax_info.transAxes,
                         color="#8b949e", fontsize=8, va="top")
            ax_info.text(0.42, y, str(value),
                         transform=ax_info.transAxes,
                         color=color, fontsize=8, va="top",
                         fontweight="bold" if bold else "normal")
            y -= dy

        step_str = str(rec["step"])
        header_color = STATUS_COLOR["future"] if is_future else (
            STATUS_COLOR["correct"] if rec.get("correct") else STATUS_COLOR["wrong"]
        )
        ax_info.text(0.05, y, f"{'Forecast' if is_future else 'Step'}  {step_str}",
                     transform=ax_info.transAxes,
                     color=header_color, fontsize=12, fontweight="bold", va="top")
        y -= dy * 1.4

        _line("Question ID",  rec["qid"][:22])
        _line("Subject",      rec["subject"])
        _line("Topic",        rec["topic"][:28])
        _line("Difficulty",   rec["difficulty"])
        _line("Question ELO", f"{rec['q_elo']:.0f}")

        if not is_future:
            outcome = "✓  Correct" if rec["correct"] else "✗  Wrong"
            _line("Outcome",  outcome,
                  color=STATUS_COLOR["correct"] if rec["correct"] else STATUS_COLOR["wrong"],
                  bold=True)
            _line("ELO before",   f"{rec['elo_before']:.0f}")
            adj = rec["elo_adj"]
            _line("ELO adjust",
                  f"{'+' if adj >= 0 else ''}{adj}",
                  color=STATUS_COLOR["correct"] if adj >= 0 else STATUS_COLOR["wrong"])
            _line("Time spent",   f"{rec['time_s']} s")
            if rec["rapid"]:
                _line("⚡ Rapid guess", "Yes", color="#f0883e", bold=True)
            _line("Momentum",     rec["momentum"])
        else:
            _line("Target ELO",  f"{rec.get('target_elo', '—')}")
            _line("Momentum",    rec["momentum"])

        _line("Graph mode",   rec["graph_mode"])
        _line("Edge kind",    rec["edge_kind"] or "—")

        if rec.get("remediation"):
            _line("Remediation", rec["remediation"][:22], color="#f0883e")

        # Reasons — word-wrap
        reasons_raw = rec.get("reasons", "") or ""
        if reasons_raw:
            y -= 0.01
            ax_info.text(0.05, y, "Reasons:",
                         transform=ax_info.transAxes,
                         color="#8b949e", fontsize=8, va="top")
            y -= dy * 0.9
            wrapped = textwrap.wrap(reasons_raw.replace(" | ", "  ·  "), width=34)
            for line in wrapped[:5]:
                ax_info.text(0.05, y, line,
                             transform=ax_info.transAxes,
                             color="#79c0ff", fontsize=7.5, va="top")
                y -= dy * 0.85

        # Bottom: ELO progress bar (session steps only)
        # Bottom: ELO progress bar (session steps only)
        if not is_future and step_records:
            # Separator line at 10% height in axes-fraction coords
            ax_info.plot(
                [0.05, 0.95], [0.10, 0.10],
                color=GRID_C, lw=0.6,
                transform=ax_info.transAxes,
                clip_on=False,
            )
            total = len(step_records)
            done  = rec["step"]
            frac  = done / total
            ax_info.text(
                0.05, 0.065,
                f"Progress: {done}/{total} steps",
                transform=ax_info.transAxes,
                color="#8b949e", fontsize=7.5, va="center",
            )
            # Progress bar as inset axes
            bar_ax = ax_info.inset_axes([0.05, 0.02, 0.90, 0.030])
            bar_ax.set_xlim(0, 1)
            bar_ax.set_ylim(0, 1)
            bar_ax.set_facecolor(GRID_C)
            bar_ax.barh(0.5, frac, color=STATUS_COLOR["correct"], height=1)
            bar_ax.set_xticks([])
            bar_ax.set_yticks([])
            for sp in bar_ax.spines.values():
                sp.set_visible(False)

    # ── 7. Build frame schedule ───────────────────────────────────────────────────
    # Each entry: (kind, data, sub_frame, total_sub_frames)
    # kind: "init" | "step" | "future" | "final"
    frame_schedule = []

    # Init hold: show empty graph for 1 s
    for _ in range(FPS):
        frame_schedule.append(("init", None, 0, 1))

    # Adaptive steps
    for rec in step_records:
        # Pulse phase
        for pf in range(PULSE_FRAMES):
            frame_schedule.append(("step_pulse", rec, pf, PULSE_FRAMES))
        # Hold phase
        for hf in range(STEP_HOLD):
            frame_schedule.append(("step_hold", rec, hf, STEP_HOLD))

    # Future steps
    for rec in future_records:
        for pf in range(PULSE_FRAMES // 2):
            frame_schedule.append(("future_pulse", rec, pf, PULSE_FRAMES // 2))
        for hf in range(FUTURE_HOLD):
            frame_schedule.append(("future_hold", rec, hf, FUTURE_HOLD))

    # Final hold
    for _ in range(FINAL_HOLD):
        frame_schedule.append(("final", None, 0, 1))

    total_frames = len(frame_schedule)
    print(f"Total frames: {total_frames}  ({total_frames/FPS:.1f} s at {FPS} fps)")

    # ── 8. Per-frame renderer ─────────────────────────────────────────────────────
    # Track which steps/futures have been committed to the canvas
    committed_steps   = set()
    committed_futures = set()

    # We need one sidebar render per step; cache last rendered step to avoid flicker
    _last_sidebar_rec    = None
    _last_sidebar_future = False

    def update(frame_idx):
        global prev_qid, prev_future_qid
        global _last_sidebar_rec, _last_sidebar_future

        kind, rec, sub_frame, total_sub = frame_schedule[frame_idx]

        # Clear transient pulse
        for a in pulse_artists:
            try: a.remove()
            except Exception: pass
        pulse_artists.clear()

        if kind == "init":
            step_label.set_text("Step: —")
            if _last_sidebar_rec is None:
                _render_sidebar(step_records[0] if step_records else {"step": "—", "qid": "—",
                    "subject":"—","topic":"—","difficulty":"—","q_elo":1400,
                    "correct":False,"elo_before":1500,"elo_adj":0,"time_s":0,
                    "rapid":False,"momentum":"—","graph_mode":"—","edge_kind":None,
                    "remediation":None,"reasons":""},
                    is_future=False)
                _last_sidebar_rec = True
            _update_scatter()
            return

        if kind in ("step_pulse", "step_hold"):
            step_num = rec["step"]
            qid      = rec["qid"]

            # Commit this step if not done yet
            if step_num not in committed_steps:
                committed_steps.add(step_num)
                # Update node colour
                node_colors[qid] = STATUS_COLOR["correct"] if rec["correct"] else STATUS_COLOR["wrong"]
                _update_scatter()
                # Draw path edge from previous
                if prev_qid and prev_qid != qid:
                    ek    = rec.get("edge_kind")
                    color = EDGE_COLOR.get(ek, EDGE_COLOR[None])
                    path_lines.append(_add_path_edge(prev_qid, qid, color, lw=2.2))
                # Step number label
                step_labels.append(_add_step_label(qid, step_num, STATUS_COLOR["correct"]))
                prev_qid = qid

            # Render sidebar once per step
            if _last_sidebar_rec is not rec or _last_sidebar_future:
                _render_sidebar(rec, is_future=False)
                _last_sidebar_rec    = rec
                _last_sidebar_future = False

            # Pulse ring
            if kind == "step_pulse":
                frac = sub_frame / max(total_sub - 1, 1)
                _draw_pulse(qid, frac)

            step_label.set_text(f"Step: {step_num} / {len(step_records)}")

        elif kind in ("future_pulse", "future_hold"):
            step_lbl = rec["step"]
            qid      = rec["qid"]

            if step_lbl not in committed_futures:
                committed_futures.add(step_lbl)
                node_colors[qid] = STATUS_COLOR["future"]
                _update_scatter()
                if prev_future_qid and prev_future_qid != qid:
                    future_lines.append(
                        _add_path_edge(prev_future_qid, qid, "#388bfd", lw=1.6, linestyle="--")
                    )
                elif prev_qid and not prev_future_qid:
                    future_lines.append(
                        _add_path_edge(prev_qid, qid, "#388bfd", lw=1.6, linestyle="--")
                    )
                step_labels.append(_add_step_label(qid, step_lbl, STATUS_COLOR["future"]))
                prev_future_qid = qid

            if _last_sidebar_rec is not rec or not _last_sidebar_future:
                _render_sidebar(rec, is_future=True)
                _last_sidebar_rec    = rec
                _last_sidebar_future = True

            if kind == "future_pulse":
                frac = sub_frame / max(total_sub - 1, 1)
                _draw_pulse(qid, frac)

            step_label.set_text(f"Forecast: {step_lbl}")

        elif kind == "final":
            step_label.set_text(f"Complete  ({len(committed_steps)} steps  +  {len(committed_futures)} forecasts)")

    # ── 9. Write video ────────────────────────────────────────────────────────────
    video_path = ROOT / f"recorded_test_graph_{str(selected_session_id or STUDENT_ID)[:8]}.mp4"

    writer = FFMpegWriter(
        fps=FPS,
        metadata=dict(title="Recorded Test Replay", artist="Notebook Cell 7"),
        codec="libx264",
        extra_args=["-pix_fmt", "yuv420p", "-crf", "20"],
    )

    anim = FuncAnimation(
        fig,
        update,
        frames=total_frames,
        interval=1000 // FPS,
        blit=False,
    )

    print(f"Rendering {total_frames} frames → {video_path} …")
    with writer.saving(fig, str(video_path), dpi=VIDEO_DPI):
        for i in range(total_frames):
            update(i)
            writer.grab_frame()
            if i % FPS == 0:
                pct = 100 * i / total_frames
                print(f"  {pct:5.1f}%  frame {i}/{total_frames}", end="\r")

    plt.close(fig)
    print(f"\n✓ Video saved → {video_path}")
    print(f"  Duration : {total_frames/FPS:.1f} s")
    print(f"  Steps    : {len(step_records)}  adaptive  +  {len(future_records)}  forecast")

Total frames: 1320  (55.0 s at 24 fps)
Rendering 1320 frames → c:\Users\sunil\Downloads\btech-project\recorded_test_graph_b362dfde.mp4 …
   98.2%  frame 1296/1320
✓ Video saved → c:\Users\sunil\Downloads\btech-project\recorded_test_graph_b362dfde.mp4
  Duration : 55.0 s
  Steps    : 13  adaptive  +  8  forecast

In [14]:
# ============================================================
# 8. SUBJECT PERFORMANCE VIDEO — full subject breakdown
#    Shows: per-subject animated bar race + topic drill-down
#    + cumulative accuracy line + question-type pie evolution
# ============================================================

import math, textwrap, warnings
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as mgridspec
from matplotlib.animation import FFMpegWriter
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=UserWarning)

# ── 0. Config ─────────────────────────────────────────────────────────────────
FPS          = 24
HOLD_FRAMES  = FPS * 2          # hold each "reveal" step for 2 s
PULSE_FRAMES = FPS // 2         # short pulse per new bar
FINAL_HOLD   = FPS * 4
VIDEO_DPI    = 120
FIG_W, FIG_H = 22, 12

BG     = "#0d1117"
PANEL  = "#161b22"
TEXT_C = "#f0f6fc"
GRID_C = "#30363d"
ACCENT = "#58a6ff"

SUBJECT_PALETTE = [
    "#58a6ff","#3fb950","#f0883e","#bc8cff",
    "#ff7b72","#ffa657","#79c0ff","#56d364",
]
CORRECT_C  = "#3fb950"
WRONG_C    = "#f85149"
NEUTRAL_C  = "#484f58"

# ── 1. Build subject + topic summary from available DataFrames ────────────────
# Priority: answered_attempts_df → question_attempts_df → recorded replay steps

def _pick_attempts_df():
    for df_name in ["answered_attempts_df", "question_attempts_df"]:
        df = globals().get(df_name, pd.DataFrame())
        if not isinstance(df, pd.DataFrame):
            continue
        if df.empty:
            continue
        has_subject = "subjectName" in df.columns or "subjectId" in df.columns
        has_correct = "correct" in df.columns
        if has_subject and has_correct:
            return df.copy()
    # last resort: simulation_steps_df
    df = globals().get("simulation_steps_df", pd.DataFrame())
    if not df.empty and "actual_subject" in df.columns:
        rename = {
            "actual_subject":   "subjectName",
            "actual_topic":     "topicName",
            "actual_difficulty":"difficulty",
            "actual_question_id":"question_id",
        }
        df = df.rename(columns={k:v for k,v in rename.items() if k in df.columns})
        return df.copy()
    return pd.DataFrame()

attempts_src = _pick_attempts_df()

if attempts_src.empty:
    print('No attempt data found for subject performance video. Skipping this video; no generated fallback data will be used.')
else:
    # Normalise column names
    if "subjectName" not in attempts_src.columns and "subjectId" in attempts_src.columns:
        attempts_src["subjectName"] = attempts_src["subjectId"].astype(str)
    if "topicName" not in attempts_src.columns and "topicId" in attempts_src.columns:
        attempts_src["topicName"] = attempts_src["topicId"].astype(str)
    for col in ["subjectName","topicName","difficulty","question_id"]:
        if col not in attempts_src.columns:
            attempts_src[col] = "—"

    attempts_src["correct"] = attempts_src["correct"].fillna(False).astype(bool)

    # ── 2. Subject-level aggregation ─────────────────────────────────────────────
    subj_grp = (
        attempts_src
        .groupby("subjectName", dropna=False)
        .agg(
            total     = ("correct", "count"),
            correct   = ("correct", "sum"),
        )
        .reset_index()
    )
    subj_grp["wrong"]    = subj_grp["total"] - subj_grp["correct"]
    subj_grp["accuracy"] = np.where(
        subj_grp["total"] > 0,
        100 * subj_grp["correct"] / subj_grp["total"], 0
    )
    subj_grp = subj_grp.sort_values("total", ascending=False).reset_index(drop=True)

    subjects      = subj_grp["subjectName"].tolist()
    n_subjects    = len(subjects)
    subj_color    = {s: SUBJECT_PALETTE[i % len(SUBJECT_PALETTE)]
                     for i, s in enumerate(subjects)}

    # ── 3. Topic-level aggregation per subject ────────────────────────────────────
    topic_grp = (
        attempts_src
        .groupby(["subjectName","topicName"], dropna=False)
        .agg(total=("correct","count"), correct=("correct","sum"))
        .reset_index()
    )
    topic_grp["wrong"]    = topic_grp["total"] - topic_grp["correct"]
    topic_grp["accuracy"] = np.where(
        topic_grp["total"] > 0,
        100 * topic_grp["correct"] / topic_grp["total"], 0
    )

    def topics_for(subject):
        df = topic_grp[topic_grp["subjectName"] == subject].copy()
        return df.sort_values("total", ascending=False).reset_index(drop=True)

    # ── 4. Difficulty breakdown per subject ───────────────────────────────────────
    diff_grp = (
        attempts_src
        .groupby(["subjectName","difficulty"], dropna=False)
        .agg(total=("correct","count"), correct=("correct","sum"))
        .reset_index()
    )

    def diff_for(subject):
        return diff_grp[diff_grp["subjectName"] == subject].copy()

    # ── 5. Cumulative accuracy timeline per subject ───────────────────────────────
    # Build a simple index-ordered cumulative trace
    cumul_records = {}
    for subj in subjects:
        sdf = attempts_src[attempts_src["subjectName"] == subj].reset_index(drop=True)
        cumul_correct = sdf["correct"].cumsum()
        cumul_total   = pd.Series(range(1, len(sdf)+1))
        cumul_acc     = (cumul_correct / cumul_total * 100).tolist()
        cumul_records[subj] = cumul_acc

    # ── 6. Figure layout ──────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(FIG_W, FIG_H), facecolor=BG)
    fig.subplots_adjust(left=0.01, right=0.99, top=0.93, bottom=0.06,
                        hspace=0.45, wspace=0.35)

    gs = mgridspec.GridSpec(2, 3, figure=fig,
                             height_ratios=[1.2, 1],
                             hspace=0.45, wspace=0.38)

    ax_bar    = fig.add_subplot(gs[0, :2])   # top-left wide: horizontal bar race
    ax_side   = fig.add_subplot(gs[0, 2])    # top-right: info panel (drawn manually)
    ax_topic  = fig.add_subplot(gs[1, 0])    # bottom-left: topic bars for active subject
    ax_diff   = fig.add_subplot(gs[1, 1])    # bottom-mid: difficulty breakdown
    ax_cumul  = fig.add_subplot(gs[1, 2])    # bottom-right: cumulative accuracy

    for ax in [ax_bar, ax_topic, ax_diff, ax_cumul]:
        ax.set_facecolor(PANEL)
        ax.tick_params(colors=TEXT_C, labelsize=8)
        for sp in ax.spines.values():
            sp.set_color(GRID_C)
        ax.grid(color=GRID_C, alpha=0.3, linestyle="--", linewidth=0.5)
        ax.set_axisbelow(True)

    ax_side.set_facecolor(PANEL)
    ax_side.set_xticks([]); ax_side.set_yticks([])
    for sp in ax_side.spines.values(): sp.set_color(GRID_C)

    fig.suptitle(
        "Subject Performance Overview — Questions Attempted",
        color=TEXT_C, fontsize=15, fontweight="bold", y=0.98,
    )

    # ── 7. Frame schedule ─────────────────────────────────────────────────────────
    # One "reveal" per subject in descending order of total attempts
    # Each reveal: PULSE_FRAMES pulse + HOLD_FRAMES hold
    frame_schedule = []

    for f in range(FPS):                           # 1 s intro
        frame_schedule.append(("intro", -1, f, FPS))

    for si, subj in enumerate(subjects):
        for pf in range(PULSE_FRAMES):
            frame_schedule.append(("pulse", si, pf, PULSE_FRAMES))
        for hf in range(HOLD_FRAMES):
            frame_schedule.append(("hold", si, hf, HOLD_FRAMES))

    for f in range(FINAL_HOLD):
        frame_schedule.append(("final", n_subjects-1, f, FINAL_HOLD))

    total_frames = len(frame_schedule)
    print(f"Total frames: {total_frames}  ({total_frames/FPS:.1f} s at {FPS} fps)")

    # ── 8. Drawing helpers ────────────────────────────────────────────────────────
    def _style(ax, title, xlabel="", ylabel=""):
        ax.set_facecolor(PANEL)
        ax.set_title(title, color=TEXT_C, fontsize=9, pad=6, fontweight="bold")
        ax.tick_params(colors=TEXT_C, labelsize=7.5)
        for sp in ax.spines.values(): sp.set_color(GRID_C)
        ax.grid(color=GRID_C, alpha=0.3, linestyle="--", linewidth=0.5)
        ax.set_axisbelow(True)
        if xlabel: ax.set_xlabel(xlabel, color="#8b949e", fontsize=7.5)
        if ylabel: ax.set_ylabel(ylabel, color="#8b949e", fontsize=7.5)

    def _draw_bar_panel(active_idx, pulse_frac=0.0):
        ax_bar.cla()
        revealed = subjects[:active_idx+1]
        rows     = subj_grp[subj_grp["subjectName"].isin(revealed)].copy()
        rows     = rows.sort_values("total", ascending=True)   # ascending for barh

        ypos   = range(len(rows))
        colors = [subj_color[s] for s in rows["subjectName"]]

        # correct bar
        bars_c = ax_bar.barh(list(ypos), rows["correct"].tolist(),
                              color=colors, alpha=0.9, height=0.55, zorder=3)
        # wrong bar stacked
        ax_bar.barh(list(ypos), rows["wrong"].tolist(),
                    left=rows["correct"].tolist(),
                    color=WRONG_C, alpha=0.45, height=0.55, zorder=3)

        # pulse glow on last bar
        if pulse_frac > 0 and len(rows) > 0:
            last_total = rows["total"].iloc[-1]
            glow_alpha = max(0, 0.35 * (1 - pulse_frac))
            ax_bar.barh(len(rows)-1, last_total,
                        color="#ffffff", alpha=glow_alpha, height=0.65, zorder=2)

        # labels
        for i, (_, row) in enumerate(rows.iterrows()):
            ax_bar.text(row["total"] + max(rows["total"].max() * 0.01, 0.3),
                        i, f'{int(row["total"])}  ({row["accuracy"]:.0f}%)',
                        va="center", color=TEXT_C, fontsize=7.5, fontweight="bold")

        ax_bar.set_yticks(list(ypos))
        ax_bar.set_yticklabels(rows["subjectName"].tolist(), color=TEXT_C, fontsize=8)
        max_total = subj_grp["total"].max()
        ax_bar.set_xlim(0, max_total * 1.22)
        _style(ax_bar,
               f"Questions Attempted per Subject  (revealed: {active_idx+1}/{n_subjects})",
               xlabel="Questions attempted")
        legend_handles = [
            mpatches.Patch(color=SUBJECT_PALETTE[0], label="Correct (subject colour)"),
            mpatches.Patch(color=WRONG_C, alpha=0.5, label="Wrong"),
        ]
        ax_bar.legend(handles=legend_handles, loc="lower right",
                      facecolor=PANEL, edgecolor=GRID_C,
                      labelcolor=TEXT_C, fontsize=7, framealpha=0.85)

    def _draw_topic_panel(subject):
        ax_topic.cla()
        tdf = topics_for(subject).head(10)
        if tdf.empty:
            _style(ax_topic, "Topics"); return
        ypos   = range(len(tdf))
        color  = subj_color.get(subject, ACCENT)
        ax_topic.barh(list(ypos), tdf["correct"].tolist(),
                      color=color, alpha=0.9, height=0.55, zorder=3)
        ax_topic.barh(list(ypos), tdf["wrong"].tolist(),
                      left=tdf["correct"].tolist(),
                      color=WRONG_C, alpha=0.45, height=0.55, zorder=3)
        labels = [textwrap.shorten(str(t), width=22, placeholder="…")
                  for t in tdf["topicName"]]
        ax_topic.set_yticks(list(ypos))
        ax_topic.set_yticklabels(labels, color=TEXT_C, fontsize=7)
        for i, (_, row) in enumerate(tdf.iterrows()):
            ax_topic.text(row["total"] + 0.1, i,
                          f'{int(row["total"])} ({row["accuracy"]:.0f}%)',
                          va="center", color=TEXT_C, fontsize=6.5)
        ax_topic.set_xlim(0, tdf["total"].max() * 1.3)
        _style(ax_topic, f"Top Topics - {textwrap.shorten(subject, width=24, placeholder='...')}",
               xlabel="Attempted")

    def _draw_diff_panel(subject):
        ax_diff.cla()
        ddf = diff_for(subject)
        if ddf.empty:
            _style(ax_diff, "Difficulty"); return
        diff_order = ["easy","medium","hard"]
        ddf = ddf[ddf["difficulty"].isin(diff_order)].copy()
        ddf["difficulty"] = pd.Categorical(ddf["difficulty"], diff_order, ordered=True)
        ddf = ddf.sort_values("difficulty")
        diff_colors = {"easy": CORRECT_C, "medium": "#f0883e", "hard": WRONG_C}
        colors = [diff_colors.get(d, NEUTRAL_C) for d in ddf["difficulty"]]
        x = range(len(ddf))
        ax_diff.bar(list(x), ddf["correct"].tolist(),
                    color=colors, alpha=0.9, width=0.45, zorder=3, label="Correct")
        ax_diff.bar(list(x), ddf["wrong"].tolist(),
                    bottom=ddf["correct"].tolist(),
                    color=WRONG_C, alpha=0.35, width=0.45, zorder=3, label="Wrong")
        ax_diff.set_xticks(list(x))
        ax_diff.set_xticklabels(ddf["difficulty"].tolist(), color=TEXT_C, fontsize=8)
        for i, (_, row) in enumerate(ddf.iterrows()):
            ax_diff.text(i, row["total"] + 0.1,
                         f'{int(row["total"])}\n{row["accuracy"]:.0f}%',
                         ha="center", va="bottom", color=TEXT_C, fontsize=7)
        _style(ax_diff, f"Difficulty - {textwrap.shorten(subject, width=20, placeholder='...')}",
               ylabel="Questions")

    def _draw_cumul_panel(subject):
        ax_cumul.cla()
        trace = cumul_records.get(subject, [])
        if not trace:
            _style(ax_cumul, "Cumulative Accuracy"); return
        x = list(range(1, len(trace)+1))
        color = subj_color.get(subject, ACCENT)
        ax_cumul.plot(x, trace, color=color, lw=2, zorder=3)
        ax_cumul.fill_between(x, trace, alpha=0.15, color=color, zorder=2)
        ax_cumul.axhline(50, color=WRONG_C, lw=0.8, linestyle="--", alpha=0.6)
        ax_cumul.set_ylim(0, 105)
        ax_cumul.set_xlim(1, max(len(trace), 2))
        _style(ax_cumul, f"Cumulative Accuracy - {textwrap.shorten(subject, width=18, placeholder='...')}",
               xlabel="Question #", ylabel="Accuracy %")

    def _draw_side_panel(subject, active_idx):
        ax_side.cla()
        ax_side.set_facecolor(PANEL)
        ax_side.set_xticks([]); ax_side.set_yticks([])
        for sp in ax_side.spines.values(): sp.set_color(GRID_C)

        row = subj_grp[subj_grp["subjectName"] == subject]
        if row.empty: return
        row = row.iloc[0]

        y = 0.96; dy = 0.072
        def _line(label, value, color=TEXT_C, bold=False):
            nonlocal y
            ax_side.text(0.04, y, label, transform=ax_side.transAxes,
                         color="#8b949e", fontsize=8, va="top")
            ax_side.text(0.46, y, str(value), transform=ax_side.transAxes,
                         color=color, fontsize=8, va="top",
                         fontweight="bold" if bold else "normal")
            y -= dy

        color = subj_color.get(subject, ACCENT)
        ax_side.text(0.04, y,
                     textwrap.shorten(subject, width=24, placeholder="…"),
                     transform=ax_side.transAxes,
                     color=color, fontsize=11, fontweight="bold", va="top")
        y -= dy * 1.3

        _line("Total attempted", int(row["total"]), bold=True)
        _line("Correct",  int(row["correct"]),  color=CORRECT_C, bold=True)
        _line("Wrong",    int(row["wrong"]),    color=WRONG_C,   bold=True)
        _line("Accuracy", f'{row["accuracy"]:.1f}%',
              color=CORRECT_C if row["accuracy"] >= 50 else WRONG_C, bold=True)

        # Topic count
        n_topics = topic_grp[topic_grp["subjectName"] == subject]["topicName"].nunique()
        _line("Topics covered", n_topics)

        # Best topic
        tdf = topics_for(subject)
        if not tdf.empty:
            best = tdf.sort_values("accuracy", ascending=False).iloc[0]
            _line("Best topic",
                  textwrap.shorten(str(best["topicName"]), width=20, placeholder="..."),
                  color=CORRECT_C)
            worst = tdf.sort_values("accuracy").iloc[0]
            _line("Weak topic",
                  textwrap.shorten(str(worst["topicName"]), width=20, placeholder="..."),
                  color=WRONG_C)

        # Progress bar
        ax_side.plot([0.04, 0.96], [0.13, 0.13],
                     color=GRID_C, lw=0.7, transform=ax_side.transAxes, clip_on=False)
        ax_side.text(0.04, 0.085, f"Subject {active_idx+1} of {n_subjects}",
                     transform=ax_side.transAxes, color="#8b949e", fontsize=7.5, va="center")
        bar_ax = ax_side.inset_axes([0.04, 0.02, 0.92, 0.04])
        bar_ax.set_xlim(0,1); bar_ax.set_ylim(0,1)
        bar_ax.set_facecolor(GRID_C)
        bar_ax.barh(0.5, (active_idx+1)/n_subjects, color=color, height=1)
        bar_ax.set_xticks([]); bar_ax.set_yticks([])
        for sp in bar_ax.spines.values(): sp.set_visible(False)

    # ── 9. Per-frame update ───────────────────────────────────────────────────────
    _last_drawn_si = -1

    def update(frame_idx):
        global _last_drawn_si
        kind, si, sub_frame, total_sub = frame_schedule[frame_idx]

        if kind == "intro":
            if _last_drawn_si == -1:
                _draw_bar_panel(-1) if False else None   # empty bar on first frame
                ax_bar.cla()
                _style(ax_bar, "Questions Attempted per Subject", xlabel="Questions attempted")
                ax_topic.cla(); _style(ax_topic, "Topics")
                ax_diff.cla();  _style(ax_diff,  "Difficulty")
                ax_cumul.cla(); _style(ax_cumul, "Cumulative Accuracy")
                ax_side.cla()
                ax_side.set_facecolor(PANEL)
                ax_side.text(0.5, 0.55, "Simulation\nSubject Report",
                             transform=ax_side.transAxes, ha="center", va="center",
                             color=ACCENT, fontsize=13, fontweight="bold")
                ax_side.set_xticks([]); ax_side.set_yticks([])
            return

        active_subject = subjects[si]
        pulse_frac = sub_frame / max(total_sub - 1, 1) if kind == "pulse" else 0.0

        # Only redraw subplots when subject changes or pulsing
        if si != _last_drawn_si or kind == "pulse":
            _draw_bar_panel(si, pulse_frac if kind == "pulse" else 0.0)
            _draw_topic_panel(active_subject)
            _draw_diff_panel(active_subject)
            _draw_cumul_panel(active_subject)
            _draw_side_panel(active_subject, si)
            _last_drawn_si = si

        elif kind == "final":
            pass   # hold last frame as-is

    # ── 10. Render video ──────────────────────────────────────────────────────────
    video_path = ROOT / f"subject_performance_{str(STUDENT_ID)[:8]}.mp4"

    writer = FFMpegWriter(
        fps=FPS,
        metadata=dict(title="Subject Performance Overview", artist="Notebook Cell 8"),
        codec="libx264",
        extra_args=["-pix_fmt", "yuv420p", "-crf", "20"],
    )

    print(f"Rendering {total_frames} frames → {video_path} …")
    with writer.saving(fig, str(video_path), dpi=VIDEO_DPI):
        for i in range(total_frames):
            update(i)
            writer.grab_frame()
            if i % FPS == 0:
                print(f"  {100*i/total_frames:5.1f}%  frame {i}/{total_frames}", end="\r")

    plt.close(fig)
    print(f"\n✓ Video saved → {video_path}")
    print(f"  Duration : {total_frames/FPS:.1f} s")
    print(f"  Subjects : {n_subjects}")
    print(f"  Total Qs : {int(subj_grp['total'].sum())}")

Total frames: 420  (17.5 s at 24 fps)
Rendering 420 frames → c:\Users\sunil\Downloads\btech-project\subject_performance_12efa469.mp4 …

C:\Users\sunil\AppData\Local\Temp\ipykernel_29852\2065077014.py:83: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

KeyError: 'wrong'

In [13]:
# ============================================================
# 9. REAL-TIME WEBSITE TEST HISTORY DASHBOARD
# ============================================================
# Re-run this cell while your website is open. It polls Supabase test_history,
# keeps every website test_history.id as the unique attempt id, and shows the
# embedded full GATE paper id from review_payload.full_test_id when present.

import time
from IPython.display import clear_output

REALTIME_REFRESH_SECONDS = int(globals().get("REALTIME_REFRESH_SECONDS", 10))
REALTIME_REFRESH_ITERATIONS = int(globals().get("REALTIME_REFRESH_ITERATIONS", 30))
REALTIME_TEST_TYPES = ["full-mock", "topic-wise", "adaptive"]


def load_live_test_history():
    rows = safe_supabase_select("test_history", user_id=STUDENT_ID, allow_network_failure=True)
    frame = pd.DataFrame(rows)
    if frame.empty:
        return frame
    if "completed_at" in frame.columns:
        frame["completed_at"] = pd.to_datetime(frame["completed_at"], errors="coerce", utc=True)
    for numeric_column in ["score", "max_score", "questions_attempted", "correct_answers", "total_questions", "violations", "duration_seconds"]:
        if numeric_column in frame.columns:
            frame[numeric_column] = pd.to_numeric(frame[numeric_column], errors="coerce")
    frame = frame[frame["test_type"].isin(REALTIME_TEST_TYPES)].copy()
    return enrich_test_history_frame(frame)


def plot_live_test_history(frame):
    if frame.empty:
        print("No visible full GATE paper, topic-wise, or adaptive test rows yet.")
        return

    display_columns = [
        "completed_at",
        "website_test_id",
        "recorded_test_id",
        "test_label",
        "score",
        "max_score",
        "score_pct",
        "accuracy_pct",
        "correct_answers",
        "total_questions",
        "subject_name",
        "topic_name",
    ]
    print(f"Last refresh: {pd.Timestamp.now(tz='UTC').tz_convert('Asia/Kolkata'):%Y-%m-%d %H:%M:%S %Z}")
    print(f"Loaded {len(frame)} real website tests for STUDENT_ID={STUDENT_ID}")
    print("Each row uses test_history.id as website_test_id; full mocks also show review_payload.full_test_id as recorded_test_id.")
    display(frame[[column for column in display_columns if column in frame.columns]].tail(12))

    if PLOTLY_AVAILABLE:
        plot_df = frame.dropna(subset=["completed_at"]).copy()
        plot_df["hover"] = plot_df.apply(
            lambda row: (
                f"website_test_id: {row.get('website_test_id')}<br>"
                f"recorded_test_id: {row.get('recorded_test_id')}<br>"
                f"type: {row.get('test_label')}<br>"
                f"score: {row.get('score')} / {row.get('max_score')}<br>"
                f"accuracy: {row.get('accuracy_pct'):.1f}%" if pd.notna(row.get('accuracy_pct')) else "accuracy: n/a"
            ),
            axis=1,
        )
        fig = go.Figure()
        for label, group in plot_df.groupby("test_label", dropna=False):
            fig.add_trace(
                go.Scatter(
                    x=group["completed_at"],
                    y=group["score_pct"],
                    mode="lines+markers",
                    name=str(label),
                    text=group["hover"],
                    hoverinfo="text+x+y",
                    marker=dict(size=10),
                )
            )
        fig.update_layout(
            title="Real-Time Website Test Progress",
            xaxis_title="Completion time",
            yaxis_title="Score %",
            yaxis=dict(range=[0, 105]),
            height=520,
            template="plotly_white",
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        )
        fig.show()
    else:
        fig, ax = plt.subplots(figsize=(14, 6))
        for label, group in frame.dropna(subset=["completed_at"]).groupby("test_label", dropna=False):
            ax.plot(group["completed_at"], group["score_pct"], marker="o", linewidth=2, label=str(label))
        ax.set_title("Real-Time Website Test Progress")
        ax.set_xlabel("Completion time")
        ax.set_ylabel("Score %")
        ax.set_ylim(0, 105)
        ax.grid(True, alpha=0.3)
        ax.legend()
        plt.show()


def watch_live_test_history(iterations=REALTIME_REFRESH_ITERATIONS, refresh_seconds=REALTIME_REFRESH_SECONDS):
    latest_seen_ids = set()
    for iteration in range(iterations):
        live_frame = load_live_test_history()
        current_ids = set(live_frame["website_test_id"].astype(str)) if not live_frame.empty else set()
        new_ids = sorted(current_ids - latest_seen_ids)
        latest_seen_ids = current_ids
        clear_output(wait=True)
        plot_live_test_history(live_frame)
        if new_ids:
            print("New test ids since previous refresh:", new_ids)
        if iteration < iterations - 1:
            time.sleep(refresh_seconds)
    return live_frame

# One immediate render. To keep watching, run:
# live_test_history_df = watch_live_test_history(iterations=60, refresh_seconds=5)
live_test_history_df = load_live_test_history()
plot_live_test_history(live_test_history_df)

Supabase network access failed for 'test_history'. Continuing with empty rows. Recorded-test graph/video mode will not generate replacement attempts.
No visible full GATE paper, topic-wise, or adaptive test rows yet.